/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AdminSetupMonitoringServices = {
  exclude?: Array<string> | undefined;
  include?: Array<string> | undefined;
};

export type AdminSetupMonitoringContainers = {
  refreshRate: number;
  services: AdminSetupMonitoringServices;
};

export type AdminSetupMonitoringThresholds = {
  cpu: number;
  memory: number;
};

export type AdminSetupMonitoringServer = {
  cronJob: string;
  port: number;
  refreshRate: number;
  retentionDays: number;
  thresholds: AdminSetupMonitoringThresholds;
  token: string;
  urlCallback: string;
};

export type AdminSetupMonitoringMetricsConfig = {
  containers: AdminSetupMonitoringContainers;
  server: AdminSetupMonitoringServer;
};

export type AdminSetupMonitoringRequest = {
  metricsConfig: AdminSetupMonitoringMetricsConfig;
};

/** @internal */
export type AdminSetupMonitoringServices$Outbound = {
  exclude?: Array<string> | undefined;
  include?: Array<string> | undefined;
};

/** @internal */
export const AdminSetupMonitoringServices$outboundSchema: z.ZodType<
  AdminSetupMonitoringServices$Outbound,
  z.ZodTypeDef,
  AdminSetupMonitoringServices
> = z.object({
  exclude: z.array(z.string()).optional(),
  include: z.array(z.string()).optional(),
});

export function adminSetupMonitoringServicesToJSON(
  adminSetupMonitoringServices: AdminSetupMonitoringServices,
): string {
  return JSON.stringify(
    AdminSetupMonitoringServices$outboundSchema.parse(
      adminSetupMonitoringServices,
    ),
  );
}

/** @internal */
export type AdminSetupMonitoringContainers$Outbound = {
  refreshRate: number;
  services: AdminSetupMonitoringServices$Outbound;
};

/** @internal */
export const AdminSetupMonitoringContainers$outboundSchema: z.ZodType<
  AdminSetupMonitoringContainers$Outbound,
  z.ZodTypeDef,
  AdminSetupMonitoringContainers
> = z.object({
  refreshRate: z.number(),
  services: z.lazy(() => AdminSetupMonitoringServices$outboundSchema),
});

export function adminSetupMonitoringContainersToJSON(
  adminSetupMonitoringContainers: AdminSetupMonitoringContainers,
): string {
  return JSON.stringify(
    AdminSetupMonitoringContainers$outboundSchema.parse(
      adminSetupMonitoringContainers,
    ),
  );
}

/** @internal */
export type AdminSetupMonitoringThresholds$Outbound = {
  cpu: number;
  memory: number;
};

/** @internal */
export const AdminSetupMonitoringThresholds$outboundSchema: z.ZodType<
  AdminSetupMonitoringThresholds$Outbound,
  z.ZodTypeDef,
  AdminSetupMonitoringThresholds
> = z.object({
  cpu: z.number(),
  memory: z.number(),
});

export function adminSetupMonitoringThresholdsToJSON(
  adminSetupMonitoringThresholds: AdminSetupMonitoringThresholds,
): string {
  return JSON.stringify(
    AdminSetupMonitoringThresholds$outboundSchema.parse(
      adminSetupMonitoringThresholds,
    ),
  );
}

/** @internal */
export type AdminSetupMonitoringServer$Outbound = {
  cronJob: string;
  port: number;
  refreshRate: number;
  retentionDays: number;
  thresholds: AdminSetupMonitoringThresholds$Outbound;
  token: string;
  urlCallback: string;
};

/** @internal */
export const AdminSetupMonitoringServer$outboundSchema: z.ZodType<
  AdminSetupMonitoringServer$Outbound,
  z.ZodTypeDef,
  AdminSetupMonitoringServer
> = z.object({
  cronJob: z.string(),
  port: z.number(),
  refreshRate: z.number(),
  retentionDays: z.number(),
  thresholds: z.lazy(() => AdminSetupMonitoringThresholds$outboundSchema),
  token: z.string(),
  urlCallback: z.string(),
});

export function adminSetupMonitoringServerToJSON(
  adminSetupMonitoringServer: AdminSetupMonitoringServer,
): string {
  return JSON.stringify(
    AdminSetupMonitoringServer$outboundSchema.parse(adminSetupMonitoringServer),
  );
}

/** @internal */
export type AdminSetupMonitoringMetricsConfig$Outbound = {
  containers: AdminSetupMonitoringContainers$Outbound;
  server: AdminSetupMonitoringServer$Outbound;
};

/** @internal */
export const AdminSetupMonitoringMetricsConfig$outboundSchema: z.ZodType<
  AdminSetupMonitoringMetricsConfig$Outbound,
  z.ZodTypeDef,
  AdminSetupMonitoringMetricsConfig
> = z.object({
  containers: z.lazy(() => AdminSetupMonitoringContainers$outboundSchema),
  server: z.lazy(() => AdminSetupMonitoringServer$outboundSchema),
});

export function adminSetupMonitoringMetricsConfigToJSON(
  adminSetupMonitoringMetricsConfig: AdminSetupMonitoringMetricsConfig,
): string {
  return JSON.stringify(
    AdminSetupMonitoringMetricsConfig$outboundSchema.parse(
      adminSetupMonitoringMetricsConfig,
    ),
  );
}

/** @internal */
export type AdminSetupMonitoringRequest$Outbound = {
  metricsConfig: AdminSetupMonitoringMetricsConfig$Outbound;
};

/** @internal */
export const AdminSetupMonitoringRequest$outboundSchema: z.ZodType<
  AdminSetupMonitoringRequest$Outbound,
  z.ZodTypeDef,
  AdminSetupMonitoringRequest
> = z.object({
  metricsConfig: z.lazy(() => AdminSetupMonitoringMetricsConfig$outboundSchema),
});

export function adminSetupMonitoringRequestToJSON(
  adminSetupMonitoringRequest: AdminSetupMonitoringRequest,
): string {
  return JSON.stringify(
    AdminSetupMonitoringRequest$outboundSchema.parse(
      adminSetupMonitoringRequest,
    ),
  );
}
