/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AiOneRequest = {
  aiId: string;
};

/** @internal */
export type AiOneRequest$Outbound = {
  aiId: string;
};

/** @internal */
export const AiOneRequest$outboundSchema: z.ZodType<
  AiOneRequest$Outbound,
  z.ZodTypeDef,
  AiOneRequest
> = z.object({
  aiId: z.string(),
});

export function aiOneRequestToJSON(aiOneRequest: AiOneRequest): string {
  return JSON.stringify(AiOneRequest$outboundSchema.parse(aiOneRequest));
}
