/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ApplicationReloadRequest = {
  appName: string;
  applicationId: string;
};

export type ApplicationReloadResponse = models.ErrorT | boolean;

/** @internal */
export type ApplicationReloadRequest$Outbound = {
  appName: string;
  applicationId: string;
};

/** @internal */
export const ApplicationReloadRequest$outboundSchema: z.ZodType<
  ApplicationReloadRequest$Outbound,
  z.ZodTypeDef,
  ApplicationReloadRequest
> = z.object({
  appName: z.string(),
  applicationId: z.string(),
});

export function applicationReloadRequestToJSON(
  applicationReloadRequest: ApplicationReloadRequest,
): string {
  return JSON.stringify(
    ApplicationReloadRequest$outboundSchema.parse(applicationReloadRequest),
  );
}

/** @internal */
export const ApplicationReloadResponse$inboundSchema: z.ZodType<
  ApplicationReloadResponse,
  z.ZodTypeDef,
  unknown
> = z.union([models.ErrorT$inboundSchema, z.boolean()]);

export function applicationReloadResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationReloadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationReloadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationReloadResponse' from JSON`,
  );
}
