/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ApplicationDisconnectGitProviderRequest = {
  applicationId: string;
};

export type ApplicationDisconnectGitProviderResponse = models.ErrorT | boolean;

/** @internal */
export type ApplicationDisconnectGitProviderRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const ApplicationDisconnectGitProviderRequest$outboundSchema: z.ZodType<
  ApplicationDisconnectGitProviderRequest$Outbound,
  z.ZodTypeDef,
  ApplicationDisconnectGitProviderRequest
> = z.object({
  applicationId: z.string(),
});

export function applicationDisconnectGitProviderRequestToJSON(
  applicationDisconnectGitProviderRequest:
    ApplicationDisconnectGitProviderRequest,
): string {
  return JSON.stringify(
    ApplicationDisconnectGitProviderRequest$outboundSchema.parse(
      applicationDisconnectGitProviderRequest,
    ),
  );
}

/** @internal */
export const ApplicationDisconnectGitProviderResponse$inboundSchema: z.ZodType<
  ApplicationDisconnectGitProviderResponse,
  z.ZodTypeDef,
  unknown
> = z.union([models.ErrorT$inboundSchema, z.boolean()]);

export function applicationDisconnectGitProviderResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ApplicationDisconnectGitProviderResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ApplicationDisconnectGitProviderResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ApplicationDisconnectGitProviderResponse' from JSON`,
  );
}
