/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ApplicationRefreshTokenRequest = {
  applicationId: string;
};

/** @internal */
export type ApplicationRefreshTokenRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const ApplicationRefreshTokenRequest$outboundSchema: z.ZodType<
  ApplicationRefreshTokenRequest$Outbound,
  z.ZodTypeDef,
  ApplicationRefreshTokenRequest
> = z.object({
  applicationId: z.string(),
});

export function applicationRefreshTokenRequestToJSON(
  applicationRefreshTokenRequest: ApplicationRefreshTokenRequest,
): string {
  return JSON.stringify(
    ApplicationRefreshTokenRequest$outboundSchema.parse(
      applicationRefreshTokenRequest,
    ),
  );
}
