/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ApplicationStartRequest = {
  applicationId: string;
};

export const ApplicationStartApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type ApplicationStartApplicationStatus = ClosedEnum<
  typeof ApplicationStartApplicationStatus
>;

export type ApplicationStartBitbucket = {
  appPassword: string | null;
  bitbucketId: string;
  bitbucketUsername: string | null;
  bitbucketWorkspaceName: string | null;
  gitProviderId: string;
};

export const ApplicationStartBuildType = {
  Dockerfile: "dockerfile",
  HerokuBuildpacks: "heroku_buildpacks",
  PaketoBuildpacks: "paketo_buildpacks",
  Nixpacks: "nixpacks",
  Static: "static",
  Railpack: "railpack",
} as const;
export type ApplicationStartBuildType = ClosedEnum<
  typeof ApplicationStartBuildType
>;

export const ApplicationStartStatus = {
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type ApplicationStartStatus = ClosedEnum<typeof ApplicationStartStatus>;

export type ApplicationStartDeployment = {
  applicationId: string | null;
  backupId: string | null;
  composeId: string | null;
  createdAt: string;
  deploymentId: string;
  description: string | null;
  errorMessage: string | null;
  finishedAt: string | null;
  isPreviewDeployment: boolean | null;
  logPath: string;
  pid: string | null;
  previewDeploymentId: string | null;
  rollbackId: string | null;
  scheduleId: string | null;
  serverId: string | null;
  startedAt: string | null;
  status: ApplicationStartStatus | null;
  title: string;
  volumeBackupId: string | null;
};

export const ApplicationStartCertificateType = {
  Letsencrypt: "letsencrypt",
  None: "none",
  Custom: "custom",
} as const;
export type ApplicationStartCertificateType = ClosedEnum<
  typeof ApplicationStartCertificateType
>;

export const ApplicationStartDomainType = {
  Compose: "compose",
  Application: "application",
  Preview: "preview",
} as const;
export type ApplicationStartDomainType = ClosedEnum<
  typeof ApplicationStartDomainType
>;

export type ApplicationStartDomain = {
  applicationId: string | null;
  certificateType: ApplicationStartCertificateType;
  composeId: string | null;
  createdAt: string;
  customCertResolver: string | null;
  domainId: string;
  domainType: ApplicationStartDomainType | null;
  host: string;
  https: boolean;
  internalPath: string | null;
  path: string | null;
  port: number | null;
  previewDeploymentId: string | null;
  serviceName: string | null;
  stripPath: boolean;
  uniqueConfigKey: number;
};

export type ApplicationStartProject = {
  createdAt: string;
  description: string | null;
  env: string;
  name: string;
  organizationId: string;
  projectId: string;
};

export type ApplicationStartEnvironment = {
  createdAt: string;
  description: string | null;
  env: string;
  environmentId: string;
  name: string;
  project: ApplicationStartProject;
  projectId: string;
};

export type ApplicationStartGitea = {
  accessToken: string | null;
  clientId: string | null;
  clientSecret: string | null;
  expiresAt: number | null;
  gitProviderId: string;
  giteaId: string;
  giteaUrl: string;
  lastAuthenticatedAt: number | null;
  redirectUri: string | null;
  refreshToken: string | null;
  scopes: string | null;
};

export type ApplicationStartGithub = {
  gitProviderId: string;
  githubAppId: number | null;
  githubAppName: string | null;
  githubClientId: string | null;
  githubClientSecret: string | null;
  githubId: string;
  githubInstallationId: string | null;
  githubPrivateKey: string | null;
  githubWebhookSecret: string | null;
};

export type ApplicationStartGitlab = {
  accessToken: string | null;
  applicationId: string | null;
  expiresAt: number | null;
  gitProviderId: string;
  gitlabId: string;
  gitlabUrl: string;
  groupName: string | null;
  redirectUri: string | null;
  refreshToken: string | null;
  secret: string | null;
};

export type ApplicationStartHealthCheckSwarm = {
  interval?: number | undefined;
  retries?: number | undefined;
  startPeriod?: number | undefined;
  test?: Array<string> | undefined;
  timeout?: number | undefined;
};

export type ApplicationStartGlobal = {};

export type ApplicationStartGlobalJob = {};

export type ApplicationStartReplicated = {
  replicas?: number | undefined;
};

export type ApplicationStartReplicatedJob = {
  maxConcurrent?: number | undefined;
  totalCompletions?: number | undefined;
};

export type ApplicationStartModeSwarm = {
  global?: ApplicationStartGlobal | undefined;
  globalJob?: ApplicationStartGlobalJob | undefined;
  replicated?: ApplicationStartReplicated | undefined;
  replicatedJob?: ApplicationStartReplicatedJob | undefined;
};

export const ApplicationStartServiceType = {
  Application: "application",
  Postgres: "postgres",
  Mysql: "mysql",
  Mariadb: "mariadb",
  Mongo: "mongo",
  Redis: "redis",
  Compose: "compose",
} as const;
export type ApplicationStartServiceType = ClosedEnum<
  typeof ApplicationStartServiceType
>;

export const ApplicationStartType = {
  Bind: "bind",
  Volume: "volume",
  File: "file",
} as const;
export type ApplicationStartType = ClosedEnum<typeof ApplicationStartType>;

export type ApplicationStartMount = {
  applicationId: string | null;
  composeId: string | null;
  content: string | null;
  filePath: string | null;
  hostPath: string | null;
  mariadbId: string | null;
  mongoId: string | null;
  mountId: string;
  mountPath: string;
  mysqlId: string | null;
  postgresId: string | null;
  redisId: string | null;
  serviceType: ApplicationStartServiceType;
  type: ApplicationStartType;
  volumeName: string | null;
};

export type ApplicationStartDriverOpts = {};

export type ApplicationStartNetworkSwarm = {
  aliases?: Array<string> | undefined;
  driverOpts?: ApplicationStartDriverOpts | undefined;
  target?: string | undefined;
};

export type ApplicationStartPlatform = {
  architecture: string;
  os: string;
};

export type ApplicationStartSpread = {
  spreadDescriptor: string;
};

export type ApplicationStartPreference = {
  spread: ApplicationStartSpread;
};

export type ApplicationStartPlacementSwarm = {
  constraints?: Array<string> | undefined;
  maxReplicas?: number | undefined;
  platforms?: Array<ApplicationStartPlatform> | undefined;
  preferences?: Array<ApplicationStartPreference> | undefined;
};

export const ApplicationStartProtocol = {
  Tcp: "tcp",
  Udp: "udp",
} as const;
export type ApplicationStartProtocol = ClosedEnum<
  typeof ApplicationStartProtocol
>;

export const ApplicationStartPublishMode = {
  Ingress: "ingress",
  Host: "host",
} as const;
export type ApplicationStartPublishMode = ClosedEnum<
  typeof ApplicationStartPublishMode
>;

export type ApplicationStartPort = {
  applicationId: string;
  portId: string;
  protocol: ApplicationStartProtocol;
  publishMode: ApplicationStartPublishMode;
  publishedPort: number;
  targetPort: number;
};

export const ApplicationStartPreviewCertificateType = {
  Letsencrypt: "letsencrypt",
  None: "none",
  Custom: "custom",
} as const;
export type ApplicationStartPreviewCertificateType = ClosedEnum<
  typeof ApplicationStartPreviewCertificateType
>;

export const ApplicationStartPreviewStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type ApplicationStartPreviewStatus = ClosedEnum<
  typeof ApplicationStartPreviewStatus
>;

export type ApplicationStartPreviewDeployment = {
  appName: string;
  applicationId: string;
  branch: string;
  createdAt: string;
  domainId: string | null;
  expiresAt: string | null;
  previewDeploymentId: string;
  previewStatus: ApplicationStartPreviewStatus;
  pullRequestCommentId: string;
  pullRequestId: string;
  pullRequestNumber: string;
  pullRequestTitle: string;
  pullRequestURL: string;
};

export type ApplicationStartRedirect = {
  applicationId: string;
  createdAt: string;
  permanent: boolean;
  redirectId: string;
  regex: string;
  replacement: string;
  uniqueConfigKey: number;
};

export const ApplicationStartRegistryType = {
  SelfHosted: "selfHosted",
  Cloud: "cloud",
} as const;
export type ApplicationStartRegistryType = ClosedEnum<
  typeof ApplicationStartRegistryType
>;

export type ApplicationStartRegistry = {
  createdAt: string;
  imagePrefix: string | null;
  organizationId: string;
  password: string;
  registryId: string;
  registryName: string;
  registryType: ApplicationStartRegistryType;
  registryUrl: string;
  username: string;
};

export type ApplicationStartRestartPolicySwarm = {
  condition?: string | undefined;
  delay?: number | undefined;
  maxAttempts?: number | undefined;
  window?: number | undefined;
};

export type ApplicationStartRollbackConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

export type ApplicationStartSecurity = {
  applicationId: string;
  createdAt: string;
  password: string;
  securityId: string;
  username: string;
};

export const ApplicationStartMetricsConfigEnum = {
  Null: "null",
} as const;
export type ApplicationStartMetricsConfigEnum = ClosedEnum<
  typeof ApplicationStartMetricsConfigEnum
>;

export type ApplicationStartMetricsConfigUnion1 =
  | string
  | number
  | boolean
  | ApplicationStartMetricsConfigEnum;

export type ApplicationStartMetricsConfigUnion2 =
  | string
  | number
  | boolean
  | ApplicationStartMetricsConfigEnum
  | Array<any>
  | { [k: string]: any };

export const ApplicationStartServerStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
export type ApplicationStartServerStatus = ClosedEnum<
  typeof ApplicationStartServerStatus
>;

export type ApplicationStartServer = {
  appName: string;
  command: string;
  createdAt: string;
  description: string | null;
  enableDockerCleanup: boolean;
  ipAddress: string;
  metricsConfig:
    | string
    | number
    | boolean
    | ApplicationStartMetricsConfigEnum
    | Array<any>
    | { [k: string]: any };
  name: string;
  organizationId: string;
  port: number;
  serverId: string;
  serverStatus: ApplicationStartServerStatus;
  sshKeyId: string | null;
  username: string;
};

export const ApplicationStartSourceType = {
  Github: "github",
  Docker: "docker",
  Git: "git",
  Gitlab: "gitlab",
  Bitbucket: "bitbucket",
  Gitea: "gitea",
  Drop: "drop",
} as const;
export type ApplicationStartSourceType = ClosedEnum<
  typeof ApplicationStartSourceType
>;

export const ApplicationStartTriggerType = {
  Push: "push",
  Tag: "tag",
} as const;
export type ApplicationStartTriggerType = ClosedEnum<
  typeof ApplicationStartTriggerType
>;

export type ApplicationStartUpdateConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

/**
 * Successful response
 */
export type ApplicationStartResponseBody = {
  appName?: string | undefined;
  applicationId?: string | undefined;
  applicationStatus?: ApplicationStartApplicationStatus | undefined;
  autoDeploy?: boolean | null | undefined;
  bitbucket: ApplicationStartBitbucket | null;
  bitbucketBranch?: string | null | undefined;
  bitbucketBuildPath?: string | null | undefined;
  bitbucketId?: string | null | undefined;
  bitbucketOwner?: string | null | undefined;
  bitbucketRepository?: string | null | undefined;
  branch?: string | null | undefined;
  buildArgs?: string | null | undefined;
  buildPath?: string | null | undefined;
  buildType?: ApplicationStartBuildType | undefined;
  cleanCache?: boolean | null | undefined;
  command?: string | null | undefined;
  cpuLimit?: string | null | undefined;
  cpuReservation?: string | null | undefined;
  createdAt?: string | undefined;
  customGitBranch?: string | null | undefined;
  customGitBuildPath?: string | null | undefined;
  customGitSSHKeyId?: string | null | undefined;
  customGitUrl?: string | null | undefined;
  deployments: Array<ApplicationStartDeployment>;
  description?: string | null | undefined;
  dockerBuildStage?: string | null | undefined;
  dockerContextPath?: string | null | undefined;
  dockerImage?: string | null | undefined;
  dockerfile?: string | null | undefined;
  domains: Array<ApplicationStartDomain>;
  dropBuildPath?: string | null | undefined;
  enableSubmodules?: boolean | undefined;
  enabled?: boolean | null | undefined;
  env?: string | null | undefined;
  environment: ApplicationStartEnvironment;
  environmentId: string;
  gitea: ApplicationStartGitea | null;
  giteaBranch?: string | null | undefined;
  giteaBuildPath?: string | null | undefined;
  giteaId?: string | null | undefined;
  giteaOwner?: string | null | undefined;
  giteaRepository?: string | null | undefined;
  github: ApplicationStartGithub | null;
  githubId?: string | null | undefined;
  gitlab: ApplicationStartGitlab | null;
  gitlabBranch?: string | null | undefined;
  gitlabBuildPath?: string | null | undefined;
  gitlabId?: string | null | undefined;
  gitlabOwner?: string | null | undefined;
  gitlabPathNamespace?: string | null | undefined;
  gitlabProjectId?: number | null | undefined;
  gitlabRepository?: string | null | undefined;
  healthCheckSwarm?: ApplicationStartHealthCheckSwarm | null | undefined;
  herokuVersion?: string | null | undefined;
  isPreviewDeploymentsActive?: boolean | null | undefined;
  isStaticSpa?: boolean | null | undefined;
  labelsSwarm?: { [k: string]: string } | null | undefined;
  memoryLimit?: string | null | undefined;
  memoryReservation?: string | null | undefined;
  modeSwarm?: ApplicationStartModeSwarm | null | undefined;
  mounts: Array<ApplicationStartMount>;
  name: string;
  networkSwarm?: Array<ApplicationStartNetworkSwarm> | null | undefined;
  owner?: string | null | undefined;
  password?: string | null | undefined;
  placementSwarm?: ApplicationStartPlacementSwarm | null | undefined;
  ports: Array<ApplicationStartPort>;
  previewBuildArgs?: string | null | undefined;
  previewCertificateType?: ApplicationStartPreviewCertificateType | undefined;
  previewCustomCertResolver?: string | null | undefined;
  previewDeployments: Array<ApplicationStartPreviewDeployment>;
  previewEnv?: string | null | undefined;
  previewHttps?: boolean | undefined;
  previewLabels?: Array<string> | null | undefined;
  previewLimit?: number | null | undefined;
  previewPath?: string | null | undefined;
  previewPort?: number | null | undefined;
  previewRequireCollaboratorPermissions?: boolean | null | undefined;
  previewWildcard?: string | null | undefined;
  publishDirectory?: string | null | undefined;
  railpackVersion?: string | null | undefined;
  redirects: Array<ApplicationStartRedirect>;
  refreshToken?: string | null | undefined;
  registry: ApplicationStartRegistry | null;
  registryId?: string | null | undefined;
  registryUrl?: string | null | undefined;
  replicas?: number | undefined;
  repository?: string | null | undefined;
  restartPolicySwarm?: ApplicationStartRestartPolicySwarm | null | undefined;
  rollbackActive?: boolean | null | undefined;
  rollbackConfigSwarm?: ApplicationStartRollbackConfigSwarm | null | undefined;
  security: Array<ApplicationStartSecurity>;
  server: ApplicationStartServer | null;
  serverId?: string | null | undefined;
  sourceType?: ApplicationStartSourceType | undefined;
  subtitle?: string | null | undefined;
  title?: string | null | undefined;
  triggerType?: ApplicationStartTriggerType | null | undefined;
  updateConfigSwarm?: ApplicationStartUpdateConfigSwarm | null | undefined;
  username?: string | null | undefined;
  watchPaths?: Array<string> | null | undefined;
};

export type ApplicationStartResponse =
  | ApplicationStartResponseBody
  | models.ErrorT;

/** @internal */
export type ApplicationStartRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const ApplicationStartRequest$outboundSchema: z.ZodType<
  ApplicationStartRequest$Outbound,
  z.ZodTypeDef,
  ApplicationStartRequest
> = z.object({
  applicationId: z.string(),
});

export function applicationStartRequestToJSON(
  applicationStartRequest: ApplicationStartRequest,
): string {
  return JSON.stringify(
    ApplicationStartRequest$outboundSchema.parse(applicationStartRequest),
  );
}

/** @internal */
export const ApplicationStartApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartApplicationStatus
> = z.nativeEnum(ApplicationStartApplicationStatus);

/** @internal */
export const ApplicationStartBitbucket$inboundSchema: z.ZodType<
  ApplicationStartBitbucket,
  z.ZodTypeDef,
  unknown
> = z.object({
  appPassword: z.nullable(z.string()),
  bitbucketId: z.string(),
  bitbucketUsername: z.nullable(z.string()),
  bitbucketWorkspaceName: z.nullable(z.string()),
  gitProviderId: z.string(),
});

export function applicationStartBitbucketFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartBitbucket, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartBitbucket$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartBitbucket' from JSON`,
  );
}

/** @internal */
export const ApplicationStartBuildType$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartBuildType
> = z.nativeEnum(ApplicationStartBuildType);

/** @internal */
export const ApplicationStartStatus$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartStatus
> = z.nativeEnum(ApplicationStartStatus);

/** @internal */
export const ApplicationStartDeployment$inboundSchema: z.ZodType<
  ApplicationStartDeployment,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.nullable(z.string()),
  backupId: z.nullable(z.string()),
  composeId: z.nullable(z.string()),
  createdAt: z.string(),
  deploymentId: z.string(),
  description: z.nullable(z.string()),
  errorMessage: z.nullable(z.string()),
  finishedAt: z.nullable(z.string()),
  isPreviewDeployment: z.nullable(z.boolean()),
  logPath: z.string(),
  pid: z.nullable(z.string()),
  previewDeploymentId: z.nullable(z.string()),
  rollbackId: z.nullable(z.string()),
  scheduleId: z.nullable(z.string()),
  serverId: z.nullable(z.string()),
  startedAt: z.nullable(z.string()),
  status: z.nullable(ApplicationStartStatus$inboundSchema),
  title: z.string(),
  volumeBackupId: z.nullable(z.string()),
});

export function applicationStartDeploymentFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartDeployment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartDeployment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartDeployment' from JSON`,
  );
}

/** @internal */
export const ApplicationStartCertificateType$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartCertificateType
> = z.nativeEnum(ApplicationStartCertificateType);

/** @internal */
export const ApplicationStartDomainType$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartDomainType
> = z.nativeEnum(ApplicationStartDomainType);

/** @internal */
export const ApplicationStartDomain$inboundSchema: z.ZodType<
  ApplicationStartDomain,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.nullable(z.string()),
  certificateType: ApplicationStartCertificateType$inboundSchema,
  composeId: z.nullable(z.string()),
  createdAt: z.string(),
  customCertResolver: z.nullable(z.string()),
  domainId: z.string(),
  domainType: z.nullable(ApplicationStartDomainType$inboundSchema),
  host: z.string(),
  https: z.boolean(),
  internalPath: z.nullable(z.string()),
  path: z.nullable(z.string()),
  port: z.nullable(z.number()),
  previewDeploymentId: z.nullable(z.string()),
  serviceName: z.nullable(z.string()),
  stripPath: z.boolean(),
  uniqueConfigKey: z.number(),
});

export function applicationStartDomainFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartDomain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartDomain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartDomain' from JSON`,
  );
}

/** @internal */
export const ApplicationStartProject$inboundSchema: z.ZodType<
  ApplicationStartProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  name: z.string(),
  organizationId: z.string(),
  projectId: z.string(),
});

export function applicationStartProjectFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartProject' from JSON`,
  );
}

/** @internal */
export const ApplicationStartEnvironment$inboundSchema: z.ZodType<
  ApplicationStartEnvironment,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  environmentId: z.string(),
  name: z.string(),
  project: z.lazy(() => ApplicationStartProject$inboundSchema),
  projectId: z.string(),
});

export function applicationStartEnvironmentFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartEnvironment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartEnvironment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartEnvironment' from JSON`,
  );
}

/** @internal */
export const ApplicationStartGitea$inboundSchema: z.ZodType<
  ApplicationStartGitea,
  z.ZodTypeDef,
  unknown
> = z.object({
  accessToken: z.nullable(z.string()),
  clientId: z.nullable(z.string()),
  clientSecret: z.nullable(z.string()),
  expiresAt: z.nullable(z.number()),
  gitProviderId: z.string(),
  giteaId: z.string(),
  giteaUrl: z.string(),
  lastAuthenticatedAt: z.nullable(z.number()),
  redirectUri: z.nullable(z.string()),
  refreshToken: z.nullable(z.string()),
  scopes: z.nullable(z.string()),
});

export function applicationStartGiteaFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartGitea, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartGitea$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartGitea' from JSON`,
  );
}

/** @internal */
export const ApplicationStartGithub$inboundSchema: z.ZodType<
  ApplicationStartGithub,
  z.ZodTypeDef,
  unknown
> = z.object({
  gitProviderId: z.string(),
  githubAppId: z.nullable(z.number()),
  githubAppName: z.nullable(z.string()),
  githubClientId: z.nullable(z.string()),
  githubClientSecret: z.nullable(z.string()),
  githubId: z.string(),
  githubInstallationId: z.nullable(z.string()),
  githubPrivateKey: z.nullable(z.string()),
  githubWebhookSecret: z.nullable(z.string()),
});

export function applicationStartGithubFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartGithub, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartGithub$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartGithub' from JSON`,
  );
}

/** @internal */
export const ApplicationStartGitlab$inboundSchema: z.ZodType<
  ApplicationStartGitlab,
  z.ZodTypeDef,
  unknown
> = z.object({
  accessToken: z.nullable(z.string()),
  applicationId: z.nullable(z.string()),
  expiresAt: z.nullable(z.number()),
  gitProviderId: z.string(),
  gitlabId: z.string(),
  gitlabUrl: z.string(),
  groupName: z.nullable(z.string()),
  redirectUri: z.nullable(z.string()),
  refreshToken: z.nullable(z.string()),
  secret: z.nullable(z.string()),
});

export function applicationStartGitlabFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartGitlab, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartGitlab$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartGitlab' from JSON`,
  );
}

/** @internal */
export const ApplicationStartHealthCheckSwarm$inboundSchema: z.ZodType<
  ApplicationStartHealthCheckSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Interval: z.number().optional(),
  Retries: z.number().optional(),
  StartPeriod: z.number().optional(),
  Test: z.array(z.string()).optional(),
  Timeout: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Interval": "interval",
    "Retries": "retries",
    "StartPeriod": "startPeriod",
    "Test": "test",
    "Timeout": "timeout",
  });
});

export function applicationStartHealthCheckSwarmFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartHealthCheckSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartHealthCheckSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartHealthCheckSwarm' from JSON`,
  );
}

/** @internal */
export const ApplicationStartGlobal$inboundSchema: z.ZodType<
  ApplicationStartGlobal,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function applicationStartGlobalFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartGlobal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartGlobal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartGlobal' from JSON`,
  );
}

/** @internal */
export const ApplicationStartGlobalJob$inboundSchema: z.ZodType<
  ApplicationStartGlobalJob,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function applicationStartGlobalJobFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartGlobalJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartGlobalJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartGlobalJob' from JSON`,
  );
}

/** @internal */
export const ApplicationStartReplicated$inboundSchema: z.ZodType<
  ApplicationStartReplicated,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicas": "replicas",
  });
});

export function applicationStartReplicatedFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartReplicated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartReplicated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartReplicated' from JSON`,
  );
}

/** @internal */
export const ApplicationStartReplicatedJob$inboundSchema: z.ZodType<
  ApplicationStartReplicatedJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  MaxConcurrent: z.number().optional(),
  TotalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "MaxConcurrent": "maxConcurrent",
    "TotalCompletions": "totalCompletions",
  });
});

export function applicationStartReplicatedJobFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartReplicatedJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartReplicatedJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartReplicatedJob' from JSON`,
  );
}

/** @internal */
export const ApplicationStartModeSwarm$inboundSchema: z.ZodType<
  ApplicationStartModeSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Global: z.lazy(() => ApplicationStartGlobal$inboundSchema).optional(),
  GlobalJob: z.lazy(() => ApplicationStartGlobalJob$inboundSchema).optional(),
  Replicated: z.lazy(() => ApplicationStartReplicated$inboundSchema).optional(),
  ReplicatedJob: z.lazy(() => ApplicationStartReplicatedJob$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Global": "global",
    "GlobalJob": "globalJob",
    "Replicated": "replicated",
    "ReplicatedJob": "replicatedJob",
  });
});

export function applicationStartModeSwarmFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartModeSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartModeSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartModeSwarm' from JSON`,
  );
}

/** @internal */
export const ApplicationStartServiceType$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartServiceType
> = z.nativeEnum(ApplicationStartServiceType);

/** @internal */
export const ApplicationStartType$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartType
> = z.nativeEnum(ApplicationStartType);

/** @internal */
export const ApplicationStartMount$inboundSchema: z.ZodType<
  ApplicationStartMount,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.nullable(z.string()),
  composeId: z.nullable(z.string()),
  content: z.nullable(z.string()),
  filePath: z.nullable(z.string()),
  hostPath: z.nullable(z.string()),
  mariadbId: z.nullable(z.string()),
  mongoId: z.nullable(z.string()),
  mountId: z.string(),
  mountPath: z.string(),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  redisId: z.nullable(z.string()),
  serviceType: ApplicationStartServiceType$inboundSchema,
  type: ApplicationStartType$inboundSchema,
  volumeName: z.nullable(z.string()),
});

export function applicationStartMountFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartMount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartMount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartMount' from JSON`,
  );
}

/** @internal */
export const ApplicationStartDriverOpts$inboundSchema: z.ZodType<
  ApplicationStartDriverOpts,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function applicationStartDriverOptsFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartDriverOpts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartDriverOpts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartDriverOpts' from JSON`,
  );
}

/** @internal */
export const ApplicationStartNetworkSwarm$inboundSchema: z.ZodType<
  ApplicationStartNetworkSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Aliases: z.array(z.string()).optional(),
  DriverOpts: z.lazy(() => ApplicationStartDriverOpts$inboundSchema).optional(),
  Target: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Aliases": "aliases",
    "DriverOpts": "driverOpts",
    "Target": "target",
  });
});

export function applicationStartNetworkSwarmFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartNetworkSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartNetworkSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartNetworkSwarm' from JSON`,
  );
}

/** @internal */
export const ApplicationStartPlatform$inboundSchema: z.ZodType<
  ApplicationStartPlatform,
  z.ZodTypeDef,
  unknown
> = z.object({
  Architecture: z.string(),
  OS: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Architecture": "architecture",
    "OS": "os",
  });
});

export function applicationStartPlatformFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartPlatform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartPlatform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartPlatform' from JSON`,
  );
}

/** @internal */
export const ApplicationStartSpread$inboundSchema: z.ZodType<
  ApplicationStartSpread,
  z.ZodTypeDef,
  unknown
> = z.object({
  SpreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    "SpreadDescriptor": "spreadDescriptor",
  });
});

export function applicationStartSpreadFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartSpread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartSpread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartSpread' from JSON`,
  );
}

/** @internal */
export const ApplicationStartPreference$inboundSchema: z.ZodType<
  ApplicationStartPreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  Spread: z.lazy(() => ApplicationStartSpread$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Spread": "spread",
  });
});

export function applicationStartPreferenceFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartPreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartPreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartPreference' from JSON`,
  );
}

/** @internal */
export const ApplicationStartPlacementSwarm$inboundSchema: z.ZodType<
  ApplicationStartPlacementSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Constraints: z.array(z.string()).optional(),
  MaxReplicas: z.number().optional(),
  Platforms: z.array(z.lazy(() => ApplicationStartPlatform$inboundSchema))
    .optional(),
  Preferences: z.array(z.lazy(() => ApplicationStartPreference$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Constraints": "constraints",
    "MaxReplicas": "maxReplicas",
    "Platforms": "platforms",
    "Preferences": "preferences",
  });
});

export function applicationStartPlacementSwarmFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartPlacementSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartPlacementSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartPlacementSwarm' from JSON`,
  );
}

/** @internal */
export const ApplicationStartProtocol$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartProtocol
> = z.nativeEnum(ApplicationStartProtocol);

/** @internal */
export const ApplicationStartPublishMode$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartPublishMode
> = z.nativeEnum(ApplicationStartPublishMode);

/** @internal */
export const ApplicationStartPort$inboundSchema: z.ZodType<
  ApplicationStartPort,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
  portId: z.string(),
  protocol: ApplicationStartProtocol$inboundSchema,
  publishMode: ApplicationStartPublishMode$inboundSchema,
  publishedPort: z.number(),
  targetPort: z.number(),
});

export function applicationStartPortFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartPort, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartPort$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartPort' from JSON`,
  );
}

/** @internal */
export const ApplicationStartPreviewCertificateType$inboundSchema:
  z.ZodNativeEnum<typeof ApplicationStartPreviewCertificateType> = z.nativeEnum(
    ApplicationStartPreviewCertificateType,
  );

/** @internal */
export const ApplicationStartPreviewStatus$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartPreviewStatus
> = z.nativeEnum(ApplicationStartPreviewStatus);

/** @internal */
export const ApplicationStartPreviewDeployment$inboundSchema: z.ZodType<
  ApplicationStartPreviewDeployment,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  applicationId: z.string(),
  branch: z.string(),
  createdAt: z.string(),
  domainId: z.nullable(z.string()),
  expiresAt: z.nullable(z.string()),
  previewDeploymentId: z.string(),
  previewStatus: ApplicationStartPreviewStatus$inboundSchema,
  pullRequestCommentId: z.string(),
  pullRequestId: z.string(),
  pullRequestNumber: z.string(),
  pullRequestTitle: z.string(),
  pullRequestURL: z.string(),
});

export function applicationStartPreviewDeploymentFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartPreviewDeployment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartPreviewDeployment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartPreviewDeployment' from JSON`,
  );
}

/** @internal */
export const ApplicationStartRedirect$inboundSchema: z.ZodType<
  ApplicationStartRedirect,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
  createdAt: z.string(),
  permanent: z.boolean(),
  redirectId: z.string(),
  regex: z.string(),
  replacement: z.string(),
  uniqueConfigKey: z.number(),
});

export function applicationStartRedirectFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartRedirect, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartRedirect$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartRedirect' from JSON`,
  );
}

/** @internal */
export const ApplicationStartRegistryType$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartRegistryType
> = z.nativeEnum(ApplicationStartRegistryType);

/** @internal */
export const ApplicationStartRegistry$inboundSchema: z.ZodType<
  ApplicationStartRegistry,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  imagePrefix: z.nullable(z.string()),
  organizationId: z.string(),
  password: z.string(),
  registryId: z.string(),
  registryName: z.string(),
  registryType: ApplicationStartRegistryType$inboundSchema,
  registryUrl: z.string(),
  username: z.string(),
});

export function applicationStartRegistryFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartRegistry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartRegistry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartRegistry' from JSON`,
  );
}

/** @internal */
export const ApplicationStartRestartPolicySwarm$inboundSchema: z.ZodType<
  ApplicationStartRestartPolicySwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Condition: z.string().optional(),
  Delay: z.number().optional(),
  MaxAttempts: z.number().optional(),
  Window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Condition": "condition",
    "Delay": "delay",
    "MaxAttempts": "maxAttempts",
    "Window": "window",
  });
});

export function applicationStartRestartPolicySwarmFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartRestartPolicySwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApplicationStartRestartPolicySwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartRestartPolicySwarm' from JSON`,
  );
}

/** @internal */
export const ApplicationStartRollbackConfigSwarm$inboundSchema: z.ZodType<
  ApplicationStartRollbackConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function applicationStartRollbackConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartRollbackConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApplicationStartRollbackConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartRollbackConfigSwarm' from JSON`,
  );
}

/** @internal */
export const ApplicationStartSecurity$inboundSchema: z.ZodType<
  ApplicationStartSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
  createdAt: z.string(),
  password: z.string(),
  securityId: z.string(),
  username: z.string(),
});

export function applicationStartSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartSecurity' from JSON`,
  );
}

/** @internal */
export const ApplicationStartMetricsConfigEnum$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartMetricsConfigEnum
> = z.nativeEnum(ApplicationStartMetricsConfigEnum);

/** @internal */
export const ApplicationStartMetricsConfigUnion1$inboundSchema: z.ZodType<
  ApplicationStartMetricsConfigUnion1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  ApplicationStartMetricsConfigEnum$inboundSchema,
]);

export function applicationStartMetricsConfigUnion1FromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartMetricsConfigUnion1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApplicationStartMetricsConfigUnion1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartMetricsConfigUnion1' from JSON`,
  );
}

/** @internal */
export const ApplicationStartMetricsConfigUnion2$inboundSchema: z.ZodType<
  ApplicationStartMetricsConfigUnion2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    ApplicationStartMetricsConfigEnum$inboundSchema,
  ]),
  z.array(z.any()),
  z.record(z.any()),
]);

export function applicationStartMetricsConfigUnion2FromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartMetricsConfigUnion2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ApplicationStartMetricsConfigUnion2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartMetricsConfigUnion2' from JSON`,
  );
}

/** @internal */
export const ApplicationStartServerStatus$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartServerStatus
> = z.nativeEnum(ApplicationStartServerStatus);

/** @internal */
export const ApplicationStartServer$inboundSchema: z.ZodType<
  ApplicationStartServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  command: z.string(),
  createdAt: z.string(),
  description: z.nullable(z.string()),
  enableDockerCleanup: z.boolean(),
  ipAddress: z.string(),
  metricsConfig: z.union([
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      ApplicationStartMetricsConfigEnum$inboundSchema,
    ]),
    z.array(z.any()),
    z.record(z.any()),
  ]),
  name: z.string(),
  organizationId: z.string(),
  port: z.number(),
  serverId: z.string(),
  serverStatus: ApplicationStartServerStatus$inboundSchema,
  sshKeyId: z.nullable(z.string()),
  username: z.string(),
});

export function applicationStartServerFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartServer' from JSON`,
  );
}

/** @internal */
export const ApplicationStartSourceType$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartSourceType
> = z.nativeEnum(ApplicationStartSourceType);

/** @internal */
export const ApplicationStartTriggerType$inboundSchema: z.ZodNativeEnum<
  typeof ApplicationStartTriggerType
> = z.nativeEnum(ApplicationStartTriggerType);

/** @internal */
export const ApplicationStartUpdateConfigSwarm$inboundSchema: z.ZodType<
  ApplicationStartUpdateConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function applicationStartUpdateConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartUpdateConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartUpdateConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartUpdateConfigSwarm' from JSON`,
  );
}

/** @internal */
export const ApplicationStartResponseBody$inboundSchema: z.ZodType<
  ApplicationStartResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string().optional(),
  applicationId: z.string().optional(),
  applicationStatus: ApplicationStartApplicationStatus$inboundSchema.optional(),
  autoDeploy: z.nullable(z.boolean()).optional(),
  bitbucket: z.nullable(z.lazy(() => ApplicationStartBitbucket$inboundSchema)),
  bitbucketBranch: z.nullable(z.string()).optional(),
  bitbucketBuildPath: z.nullable(z.string()).optional(),
  bitbucketId: z.nullable(z.string()).optional(),
  bitbucketOwner: z.nullable(z.string()).optional(),
  bitbucketRepository: z.nullable(z.string()).optional(),
  branch: z.nullable(z.string()).optional(),
  buildArgs: z.nullable(z.string()).optional(),
  buildPath: z.nullable(z.string()).optional(),
  buildType: ApplicationStartBuildType$inboundSchema.optional(),
  cleanCache: z.nullable(z.boolean()).optional(),
  command: z.nullable(z.string()).optional(),
  cpuLimit: z.nullable(z.string()).optional(),
  cpuReservation: z.nullable(z.string()).optional(),
  createdAt: z.string().optional(),
  customGitBranch: z.nullable(z.string()).optional(),
  customGitBuildPath: z.nullable(z.string()).optional(),
  customGitSSHKeyId: z.nullable(z.string()).optional(),
  customGitUrl: z.nullable(z.string()).optional(),
  deployments: z.array(z.lazy(() => ApplicationStartDeployment$inboundSchema)),
  description: z.nullable(z.string()).optional(),
  dockerBuildStage: z.nullable(z.string()).optional(),
  dockerContextPath: z.nullable(z.string()).optional(),
  dockerImage: z.nullable(z.string()).optional(),
  dockerfile: z.nullable(z.string()).optional(),
  domains: z.array(z.lazy(() => ApplicationStartDomain$inboundSchema)),
  dropBuildPath: z.nullable(z.string()).optional(),
  enableSubmodules: z.boolean().optional(),
  enabled: z.nullable(z.boolean()).optional(),
  env: z.nullable(z.string()).optional(),
  environment: z.lazy(() => ApplicationStartEnvironment$inboundSchema),
  environmentId: z.string(),
  gitea: z.nullable(z.lazy(() => ApplicationStartGitea$inboundSchema)),
  giteaBranch: z.nullable(z.string()).optional(),
  giteaBuildPath: z.nullable(z.string()).optional(),
  giteaId: z.nullable(z.string()).optional(),
  giteaOwner: z.nullable(z.string()).optional(),
  giteaRepository: z.nullable(z.string()).optional(),
  github: z.nullable(z.lazy(() => ApplicationStartGithub$inboundSchema)),
  githubId: z.nullable(z.string()).optional(),
  gitlab: z.nullable(z.lazy(() => ApplicationStartGitlab$inboundSchema)),
  gitlabBranch: z.nullable(z.string()).optional(),
  gitlabBuildPath: z.nullable(z.string()).optional(),
  gitlabId: z.nullable(z.string()).optional(),
  gitlabOwner: z.nullable(z.string()).optional(),
  gitlabPathNamespace: z.nullable(z.string()).optional(),
  gitlabProjectId: z.nullable(z.number()).optional(),
  gitlabRepository: z.nullable(z.string()).optional(),
  healthCheckSwarm: z.nullable(
    z.lazy(() => ApplicationStartHealthCheckSwarm$inboundSchema),
  ).optional(),
  herokuVersion: z.nullable(z.string()).optional(),
  isPreviewDeploymentsActive: z.nullable(z.boolean()).optional(),
  isStaticSpa: z.nullable(z.boolean()).optional(),
  labelsSwarm: z.nullable(z.record(z.string())).optional(),
  memoryLimit: z.nullable(z.string()).optional(),
  memoryReservation: z.nullable(z.string()).optional(),
  modeSwarm: z.nullable(z.lazy(() => ApplicationStartModeSwarm$inboundSchema))
    .optional(),
  mounts: z.array(z.lazy(() => ApplicationStartMount$inboundSchema)),
  name: z.string(),
  networkSwarm: z.nullable(
    z.array(z.lazy(() => ApplicationStartNetworkSwarm$inboundSchema)),
  ).optional(),
  owner: z.nullable(z.string()).optional(),
  password: z.nullable(z.string()).optional(),
  placementSwarm: z.nullable(
    z.lazy(() => ApplicationStartPlacementSwarm$inboundSchema),
  ).optional(),
  ports: z.array(z.lazy(() => ApplicationStartPort$inboundSchema)),
  previewBuildArgs: z.nullable(z.string()).optional(),
  previewCertificateType: ApplicationStartPreviewCertificateType$inboundSchema
    .optional(),
  previewCustomCertResolver: z.nullable(z.string()).optional(),
  previewDeployments: z.array(
    z.lazy(() => ApplicationStartPreviewDeployment$inboundSchema),
  ),
  previewEnv: z.nullable(z.string()).optional(),
  previewHttps: z.boolean().optional(),
  previewLabels: z.nullable(z.array(z.string())).optional(),
  previewLimit: z.nullable(z.number()).optional(),
  previewPath: z.nullable(z.string()).optional(),
  previewPort: z.nullable(z.number()).optional(),
  previewRequireCollaboratorPermissions: z.nullable(z.boolean()).optional(),
  previewWildcard: z.nullable(z.string()).optional(),
  publishDirectory: z.nullable(z.string()).optional(),
  railpackVersion: z.nullable(z.string()).optional(),
  redirects: z.array(z.lazy(() => ApplicationStartRedirect$inboundSchema)),
  refreshToken: z.nullable(z.string()).optional(),
  registry: z.nullable(z.lazy(() => ApplicationStartRegistry$inboundSchema)),
  registryId: z.nullable(z.string()).optional(),
  registryUrl: z.nullable(z.string()).optional(),
  replicas: z.number().optional(),
  repository: z.nullable(z.string()).optional(),
  restartPolicySwarm: z.nullable(
    z.lazy(() => ApplicationStartRestartPolicySwarm$inboundSchema),
  ).optional(),
  rollbackActive: z.nullable(z.boolean()).optional(),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => ApplicationStartRollbackConfigSwarm$inboundSchema),
  ).optional(),
  security: z.array(z.lazy(() => ApplicationStartSecurity$inboundSchema)),
  server: z.nullable(z.lazy(() => ApplicationStartServer$inboundSchema)),
  serverId: z.nullable(z.string()).optional(),
  sourceType: ApplicationStartSourceType$inboundSchema.optional(),
  subtitle: z.nullable(z.string()).optional(),
  title: z.nullable(z.string()).optional(),
  triggerType: z.nullable(ApplicationStartTriggerType$inboundSchema).optional(),
  updateConfigSwarm: z.nullable(
    z.lazy(() => ApplicationStartUpdateConfigSwarm$inboundSchema),
  ).optional(),
  username: z.nullable(z.string()).optional(),
  watchPaths: z.nullable(z.array(z.string())).optional(),
});

export function applicationStartResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartResponseBody' from JSON`,
  );
}

/** @internal */
export const ApplicationStartResponse$inboundSchema: z.ZodType<
  ApplicationStartResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ApplicationStartResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function applicationStartResponseFromJSON(
  jsonString: string,
): SafeParseResult<ApplicationStartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApplicationStartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApplicationStartResponse' from JSON`,
  );
}
