/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ApplicationMarkRunningRequest = {
  applicationId: string;
};

/** @internal */
export type ApplicationMarkRunningRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const ApplicationMarkRunningRequest$outboundSchema: z.ZodType<
  ApplicationMarkRunningRequest$Outbound,
  z.ZodTypeDef,
  ApplicationMarkRunningRequest
> = z.object({
  applicationId: z.string(),
});

export function applicationMarkRunningRequestToJSON(
  applicationMarkRunningRequest: ApplicationMarkRunningRequest,
): string {
  return JSON.stringify(
    ApplicationMarkRunningRequest$outboundSchema.parse(
      applicationMarkRunningRequest,
    ),
  );
}
