/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ApplicationCancelDeploymentRequest = {
  applicationId: string;
};

/** @internal */
export type ApplicationCancelDeploymentRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const ApplicationCancelDeploymentRequest$outboundSchema: z.ZodType<
  ApplicationCancelDeploymentRequest$Outbound,
  z.ZodTypeDef,
  ApplicationCancelDeploymentRequest
> = z.object({
  applicationId: z.string(),
});

export function applicationCancelDeploymentRequestToJSON(
  applicationCancelDeploymentRequest: ApplicationCancelDeploymentRequest,
): string {
  return JSON.stringify(
    ApplicationCancelDeploymentRequest$outboundSchema.parse(
      applicationCancelDeploymentRequest,
    ),
  );
}
