/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ApplicationCleanQueuesRequest = {
  applicationId: string;
};

/** @internal */
export type ApplicationCleanQueuesRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const ApplicationCleanQueuesRequest$outboundSchema: z.ZodType<
  ApplicationCleanQueuesRequest$Outbound,
  z.ZodTypeDef,
  ApplicationCleanQueuesRequest
> = z.object({
  applicationId: z.string(),
});

export function applicationCleanQueuesRequestToJSON(
  applicationCleanQueuesRequest: ApplicationCleanQueuesRequest,
): string {
  return JSON.stringify(
    ApplicationCleanQueuesRequest$outboundSchema.parse(
      applicationCleanQueuesRequest,
    ),
  );
}
