/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type BackupManualBackupMongoRequest = {
  backupId: string;
};

/** @internal */
export type BackupManualBackupMongoRequest$Outbound = {
  backupId: string;
};

/** @internal */
export const BackupManualBackupMongoRequest$outboundSchema: z.ZodType<
  BackupManualBackupMongoRequest$Outbound,
  z.ZodTypeDef,
  BackupManualBackupMongoRequest
> = z.object({
  backupId: z.string(),
});

export function backupManualBackupMongoRequestToJSON(
  backupManualBackupMongoRequest: BackupManualBackupMongoRequest,
): string {
  return JSON.stringify(
    BackupManualBackupMongoRequest$outboundSchema.parse(
      backupManualBackupMongoRequest,
    ),
  );
}
