/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type BackupOneRequest = {
  backupId: string;
};

/** @internal */
export type BackupOneRequest$Outbound = {
  backupId: string;
};

/** @internal */
export const BackupOneRequest$outboundSchema: z.ZodType<
  BackupOneRequest$Outbound,
  z.ZodTypeDef,
  BackupOneRequest
> = z.object({
  backupId: z.string(),
});

export function backupOneRequestToJSON(
  backupOneRequest: BackupOneRequest,
): string {
  return JSON.stringify(
    BackupOneRequest$outboundSchema.parse(backupOneRequest),
  );
}
