/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type BackupManualBackupMySqlRequest = {
  backupId: string;
};

/** @internal */
export type BackupManualBackupMySqlRequest$Outbound = {
  backupId: string;
};

/** @internal */
export const BackupManualBackupMySqlRequest$outboundSchema: z.ZodType<
  BackupManualBackupMySqlRequest$Outbound,
  z.ZodTypeDef,
  BackupManualBackupMySqlRequest
> = z.object({
  backupId: z.string(),
});

export function backupManualBackupMySqlRequestToJSON(
  backupManualBackupMySqlRequest: BackupManualBackupMySqlRequest,
): string {
  return JSON.stringify(
    BackupManualBackupMySqlRequest$outboundSchema.parse(
      backupManualBackupMySqlRequest,
    ),
  );
}
