/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type BackupListBackupFilesRequest = {
  destinationId: string;
  search: string;
  serverId?: string | undefined;
};

/** @internal */
export type BackupListBackupFilesRequest$Outbound = {
  destinationId: string;
  search: string;
  serverId?: string | undefined;
};

/** @internal */
export const BackupListBackupFilesRequest$outboundSchema: z.ZodType<
  BackupListBackupFilesRequest$Outbound,
  z.ZodTypeDef,
  BackupListBackupFilesRequest
> = z.object({
  destinationId: z.string(),
  search: z.string(),
  serverId: z.string().optional(),
});

export function backupListBackupFilesRequestToJSON(
  backupListBackupFilesRequest: BackupListBackupFilesRequest,
): string {
  return JSON.stringify(
    BackupListBackupFilesRequest$outboundSchema.parse(
      backupListBackupFilesRequest,
    ),
  );
}
