/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type BackupManualBackupWebServerRequest = {
  backupId: string;
};

/** @internal */
export type BackupManualBackupWebServerRequest$Outbound = {
  backupId: string;
};

/** @internal */
export const BackupManualBackupWebServerRequest$outboundSchema: z.ZodType<
  BackupManualBackupWebServerRequest$Outbound,
  z.ZodTypeDef,
  BackupManualBackupWebServerRequest
> = z.object({
  backupId: z.string(),
});

export function backupManualBackupWebServerRequestToJSON(
  backupManualBackupWebServerRequest: BackupManualBackupWebServerRequest,
): string {
  return JSON.stringify(
    BackupManualBackupWebServerRequest$outboundSchema.parse(
      backupManualBackupWebServerRequest,
    ),
  );
}
