/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type BitbucketUpdateRequest = {
  appPassword?: string | null | undefined;
  bitbucketId: string;
  bitbucketUsername?: string | undefined;
  bitbucketWorkspaceName?: string | undefined;
  gitProviderId: string;
  name: string;
  organizationId?: string | undefined;
};

/**
 * Successful response
 */
export type BitbucketUpdateResponseBody = {
  appPassword: string | null;
  bitbucketId: string;
  bitbucketUsername: string | null;
  bitbucketWorkspaceName: string | null;
  gitProviderId: string;
};

export type BitbucketUpdateResponse =
  | BitbucketUpdateResponseBody
  | models.ErrorT;

/** @internal */
export type BitbucketUpdateRequest$Outbound = {
  appPassword?: string | null | undefined;
  bitbucketId: string;
  bitbucketUsername?: string | undefined;
  bitbucketWorkspaceName?: string | undefined;
  gitProviderId: string;
  name: string;
  organizationId?: string | undefined;
};

/** @internal */
export const BitbucketUpdateRequest$outboundSchema: z.ZodType<
  BitbucketUpdateRequest$Outbound,
  z.ZodTypeDef,
  BitbucketUpdateRequest
> = z.object({
  appPassword: z.nullable(z.string()).optional(),
  bitbucketId: z.string(),
  bitbucketUsername: z.string().optional(),
  bitbucketWorkspaceName: z.string().optional(),
  gitProviderId: z.string(),
  name: z.string(),
  organizationId: z.string().optional(),
});

export function bitbucketUpdateRequestToJSON(
  bitbucketUpdateRequest: BitbucketUpdateRequest,
): string {
  return JSON.stringify(
    BitbucketUpdateRequest$outboundSchema.parse(bitbucketUpdateRequest),
  );
}

/** @internal */
export const BitbucketUpdateResponseBody$inboundSchema: z.ZodType<
  BitbucketUpdateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appPassword: z.nullable(z.string()),
  bitbucketId: z.string(),
  bitbucketUsername: z.nullable(z.string()),
  bitbucketWorkspaceName: z.nullable(z.string()),
  gitProviderId: z.string(),
});

export function bitbucketUpdateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<BitbucketUpdateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BitbucketUpdateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BitbucketUpdateResponseBody' from JSON`,
  );
}

/** @internal */
export const BitbucketUpdateResponse$inboundSchema: z.ZodType<
  BitbucketUpdateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => BitbucketUpdateResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function bitbucketUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<BitbucketUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BitbucketUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BitbucketUpdateResponse' from JSON`,
  );
}
