/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type BitbucketTestConnectionRequest = {
  bitbucketId: string;
  bitbucketUsername?: string | undefined;
  workspaceName?: string | undefined;
};

export type BitbucketTestConnectionResponse = models.ErrorT | string;

/** @internal */
export type BitbucketTestConnectionRequest$Outbound = {
  bitbucketId: string;
  bitbucketUsername?: string | undefined;
  workspaceName?: string | undefined;
};

/** @internal */
export const BitbucketTestConnectionRequest$outboundSchema: z.ZodType<
  BitbucketTestConnectionRequest$Outbound,
  z.ZodTypeDef,
  BitbucketTestConnectionRequest
> = z.object({
  bitbucketId: z.string(),
  bitbucketUsername: z.string().optional(),
  workspaceName: z.string().optional(),
});

export function bitbucketTestConnectionRequestToJSON(
  bitbucketTestConnectionRequest: BitbucketTestConnectionRequest,
): string {
  return JSON.stringify(
    BitbucketTestConnectionRequest$outboundSchema.parse(
      bitbucketTestConnectionRequest,
    ),
  );
}

/** @internal */
export const BitbucketTestConnectionResponse$inboundSchema: z.ZodType<
  BitbucketTestConnectionResponse,
  z.ZodTypeDef,
  unknown
> = z.union([models.ErrorT$inboundSchema, z.string()]);

export function bitbucketTestConnectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<BitbucketTestConnectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BitbucketTestConnectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BitbucketTestConnectionResponse' from JSON`,
  );
}
