/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type BitbucketOneRequest = {
  bitbucketId: string;
};

export const BitbucketOneProviderType = {
  Github: "github",
  Gitlab: "gitlab",
  Bitbucket: "bitbucket",
  Gitea: "gitea",
} as const;
export type BitbucketOneProviderType = ClosedEnum<
  typeof BitbucketOneProviderType
>;

export type BitbucketOneGitProvider = {
  createdAt: string;
  gitProviderId: string;
  name: string;
  organizationId: string;
  providerType: BitbucketOneProviderType;
  userId: string;
};

/**
 * Successful response
 */
export type BitbucketOneResponseBody = {
  appPassword: string | null;
  bitbucketId: string;
  bitbucketUsername: string | null;
  bitbucketWorkspaceName: string | null;
  gitProvider: BitbucketOneGitProvider;
  gitProviderId: string;
};

export type BitbucketOneResponse = BitbucketOneResponseBody | models.ErrorT;

/** @internal */
export type BitbucketOneRequest$Outbound = {
  bitbucketId: string;
};

/** @internal */
export const BitbucketOneRequest$outboundSchema: z.ZodType<
  BitbucketOneRequest$Outbound,
  z.ZodTypeDef,
  BitbucketOneRequest
> = z.object({
  bitbucketId: z.string(),
});

export function bitbucketOneRequestToJSON(
  bitbucketOneRequest: BitbucketOneRequest,
): string {
  return JSON.stringify(
    BitbucketOneRequest$outboundSchema.parse(bitbucketOneRequest),
  );
}

/** @internal */
export const BitbucketOneProviderType$inboundSchema: z.ZodNativeEnum<
  typeof BitbucketOneProviderType
> = z.nativeEnum(BitbucketOneProviderType);

/** @internal */
export const BitbucketOneGitProvider$inboundSchema: z.ZodType<
  BitbucketOneGitProvider,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  gitProviderId: z.string(),
  name: z.string(),
  organizationId: z.string(),
  providerType: BitbucketOneProviderType$inboundSchema,
  userId: z.string(),
});

export function bitbucketOneGitProviderFromJSON(
  jsonString: string,
): SafeParseResult<BitbucketOneGitProvider, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BitbucketOneGitProvider$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BitbucketOneGitProvider' from JSON`,
  );
}

/** @internal */
export const BitbucketOneResponseBody$inboundSchema: z.ZodType<
  BitbucketOneResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appPassword: z.nullable(z.string()),
  bitbucketId: z.string(),
  bitbucketUsername: z.nullable(z.string()),
  bitbucketWorkspaceName: z.nullable(z.string()),
  gitProvider: z.lazy(() => BitbucketOneGitProvider$inboundSchema),
  gitProviderId: z.string(),
});

export function bitbucketOneResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<BitbucketOneResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BitbucketOneResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BitbucketOneResponseBody' from JSON`,
  );
}

/** @internal */
export const BitbucketOneResponse$inboundSchema: z.ZodType<
  BitbucketOneResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => BitbucketOneResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function bitbucketOneResponseFromJSON(
  jsonString: string,
): SafeParseResult<BitbucketOneResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BitbucketOneResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BitbucketOneResponse' from JSON`,
  );
}
