/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type CertificatesOneRequest = {
  certificateId: string;
};

/**
 * Successful response
 */
export type CertificatesOneResponseBody = {
  autoRenew: boolean | null;
  certificateData: string;
  certificateId: string;
  certificatePath: string;
  name: string;
  organizationId: string;
  privateKey: string;
  serverId: string | null;
};

export type CertificatesOneResponse =
  | CertificatesOneResponseBody
  | models.ErrorT;

/** @internal */
export type CertificatesOneRequest$Outbound = {
  certificateId: string;
};

/** @internal */
export const CertificatesOneRequest$outboundSchema: z.ZodType<
  CertificatesOneRequest$Outbound,
  z.ZodTypeDef,
  CertificatesOneRequest
> = z.object({
  certificateId: z.string(),
});

export function certificatesOneRequestToJSON(
  certificatesOneRequest: CertificatesOneRequest,
): string {
  return JSON.stringify(
    CertificatesOneRequest$outboundSchema.parse(certificatesOneRequest),
  );
}

/** @internal */
export const CertificatesOneResponseBody$inboundSchema: z.ZodType<
  CertificatesOneResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  autoRenew: z.nullable(z.boolean()),
  certificateData: z.string(),
  certificateId: z.string(),
  certificatePath: z.string(),
  name: z.string(),
  organizationId: z.string(),
  privateKey: z.string(),
  serverId: z.nullable(z.string()),
});

export function certificatesOneResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CertificatesOneResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CertificatesOneResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CertificatesOneResponseBody' from JSON`,
  );
}

/** @internal */
export const CertificatesOneResponse$inboundSchema: z.ZodType<
  CertificatesOneResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => CertificatesOneResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function certificatesOneResponseFromJSON(
  jsonString: string,
): SafeParseResult<CertificatesOneResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CertificatesOneResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CertificatesOneResponse' from JSON`,
  );
}
