/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ClusterRemoveWorkerRequest = {
  nodeId: string;
  serverId?: string | undefined;
};

/** @internal */
export type ClusterRemoveWorkerRequest$Outbound = {
  nodeId: string;
  serverId?: string | undefined;
};

/** @internal */
export const ClusterRemoveWorkerRequest$outboundSchema: z.ZodType<
  ClusterRemoveWorkerRequest$Outbound,
  z.ZodTypeDef,
  ClusterRemoveWorkerRequest
> = z.object({
  nodeId: z.string(),
  serverId: z.string().optional(),
});

export function clusterRemoveWorkerRequestToJSON(
  clusterRemoveWorkerRequest: ClusterRemoveWorkerRequest,
): string {
  return JSON.stringify(
    ClusterRemoveWorkerRequest$outboundSchema.parse(clusterRemoveWorkerRequest),
  );
}
