/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ComposeImportRequest = {
  base64: string;
  composeId: string;
};

/** @internal */
export type ComposeImportRequest$Outbound = {
  base64: string;
  composeId: string;
};

/** @internal */
export const ComposeImportRequest$outboundSchema: z.ZodType<
  ComposeImportRequest$Outbound,
  z.ZodTypeDef,
  ComposeImportRequest
> = z.object({
  base64: z.string(),
  composeId: z.string(),
});

export function composeImportRequestToJSON(
  composeImportRequest: ComposeImportRequest,
): string {
  return JSON.stringify(
    ComposeImportRequest$outboundSchema.parse(composeImportRequest),
  );
}
