/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ComposeGetDefaultCommandRequest = {
  composeId: string;
};

/** @internal */
export type ComposeGetDefaultCommandRequest$Outbound = {
  composeId: string;
};

/** @internal */
export const ComposeGetDefaultCommandRequest$outboundSchema: z.ZodType<
  ComposeGetDefaultCommandRequest$Outbound,
  z.ZodTypeDef,
  ComposeGetDefaultCommandRequest
> = z.object({
  composeId: z.string(),
});

export function composeGetDefaultCommandRequestToJSON(
  composeGetDefaultCommandRequest: ComposeGetDefaultCommandRequest,
): string {
  return JSON.stringify(
    ComposeGetDefaultCommandRequest$outboundSchema.parse(
      composeGetDefaultCommandRequest,
    ),
  );
}
