/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ComposeTemplatesRequest = {
  baseUrl?: string | undefined;
};

/** @internal */
export type ComposeTemplatesRequest$Outbound = {
  baseUrl?: string | undefined;
};

/** @internal */
export const ComposeTemplatesRequest$outboundSchema: z.ZodType<
  ComposeTemplatesRequest$Outbound,
  z.ZodTypeDef,
  ComposeTemplatesRequest
> = z.object({
  baseUrl: z.string().optional(),
});

export function composeTemplatesRequestToJSON(
  composeTemplatesRequest: ComposeTemplatesRequest,
): string {
  return JSON.stringify(
    ComposeTemplatesRequest$outboundSchema.parse(composeTemplatesRequest),
  );
}
