/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ComposeRandomizeComposeRequest = {
  composeId: string;
  suffix?: string | undefined;
};

/** @internal */
export type ComposeRandomizeComposeRequest$Outbound = {
  composeId: string;
  suffix?: string | undefined;
};

/** @internal */
export const ComposeRandomizeComposeRequest$outboundSchema: z.ZodType<
  ComposeRandomizeComposeRequest$Outbound,
  z.ZodTypeDef,
  ComposeRandomizeComposeRequest
> = z.object({
  composeId: z.string(),
  suffix: z.string().optional(),
});

export function composeRandomizeComposeRequestToJSON(
  composeRandomizeComposeRequest: ComposeRandomizeComposeRequest,
): string {
  return JSON.stringify(
    ComposeRandomizeComposeRequest$outboundSchema.parse(
      composeRandomizeComposeRequest,
    ),
  );
}
