/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ComposeOneRequest = {
  composeId: string;
};

/** @internal */
export type ComposeOneRequest$Outbound = {
  composeId: string;
};

/** @internal */
export const ComposeOneRequest$outboundSchema: z.ZodType<
  ComposeOneRequest$Outbound,
  z.ZodTypeDef,
  ComposeOneRequest
> = z.object({
  composeId: z.string(),
});

export function composeOneRequestToJSON(
  composeOneRequest: ComposeOneRequest,
): string {
  return JSON.stringify(
    ComposeOneRequest$outboundSchema.parse(composeOneRequest),
  );
}
