/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ComposeRedeployRequest = {
  composeId: string;
  description?: string | undefined;
  title?: string | undefined;
};

/** @internal */
export type ComposeRedeployRequest$Outbound = {
  composeId: string;
  description?: string | undefined;
  title?: string | undefined;
};

/** @internal */
export const ComposeRedeployRequest$outboundSchema: z.ZodType<
  ComposeRedeployRequest$Outbound,
  z.ZodTypeDef,
  ComposeRedeployRequest
> = z.object({
  composeId: z.string(),
  description: z.string().optional(),
  title: z.string().optional(),
});

export function composeRedeployRequestToJSON(
  composeRedeployRequest: ComposeRedeployRequest,
): string {
  return JSON.stringify(
    ComposeRedeployRequest$outboundSchema.parse(composeRedeployRequest),
  );
}
