/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeploymentAllRequest = {
  applicationId: string;
};

export const DeploymentAllStatus = {
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type DeploymentAllStatus = ClosedEnum<typeof DeploymentAllStatus>;

export type DeploymentAllResponseBody = {
  applicationId: string | null;
  backupId: string | null;
  composeId: string | null;
  createdAt: string;
  deploymentId: string;
  description: string | null;
  errorMessage: string | null;
  finishedAt: string | null;
  isPreviewDeployment: boolean | null;
  logPath: string;
  pid: string | null;
  previewDeploymentId: string | null;
  rollbackId: string | null;
  scheduleId: string | null;
  serverId: string | null;
  startedAt: string | null;
  status: DeploymentAllStatus | null;
  title: string;
  volumeBackupId: string | null;
};

export type DeploymentAllResponse =
  | models.ErrorT
  | Array<DeploymentAllResponseBody>;

/** @internal */
export type DeploymentAllRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const DeploymentAllRequest$outboundSchema: z.ZodType<
  DeploymentAllRequest$Outbound,
  z.ZodTypeDef,
  DeploymentAllRequest
> = z.object({
  applicationId: z.string(),
});

export function deploymentAllRequestToJSON(
  deploymentAllRequest: DeploymentAllRequest,
): string {
  return JSON.stringify(
    DeploymentAllRequest$outboundSchema.parse(deploymentAllRequest),
  );
}

/** @internal */
export const DeploymentAllStatus$inboundSchema: z.ZodNativeEnum<
  typeof DeploymentAllStatus
> = z.nativeEnum(DeploymentAllStatus);

/** @internal */
export const DeploymentAllResponseBody$inboundSchema: z.ZodType<
  DeploymentAllResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.nullable(z.string()),
  backupId: z.nullable(z.string()),
  composeId: z.nullable(z.string()),
  createdAt: z.string(),
  deploymentId: z.string(),
  description: z.nullable(z.string()),
  errorMessage: z.nullable(z.string()),
  finishedAt: z.nullable(z.string()),
  isPreviewDeployment: z.nullable(z.boolean()),
  logPath: z.string(),
  pid: z.nullable(z.string()),
  previewDeploymentId: z.nullable(z.string()),
  rollbackId: z.nullable(z.string()),
  scheduleId: z.nullable(z.string()),
  serverId: z.nullable(z.string()),
  startedAt: z.nullable(z.string()),
  status: z.nullable(DeploymentAllStatus$inboundSchema),
  title: z.string(),
  volumeBackupId: z.nullable(z.string()),
});

export function deploymentAllResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentAllResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentAllResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentAllResponseBody' from JSON`,
  );
}

/** @internal */
export const DeploymentAllResponse$inboundSchema: z.ZodType<
  DeploymentAllResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.ErrorT$inboundSchema,
  z.array(z.lazy(() => DeploymentAllResponseBody$inboundSchema)),
]);

export function deploymentAllResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentAllResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentAllResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentAllResponse' from JSON`,
  );
}
