/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DestinationUpdateRequest = {
  accessKey: string;
  bucket: string;
  destinationId: string;
  endpoint: string;
  name: string;
  provider: string | null;
  region: string;
  secretAccessKey: string;
  serverId?: string | undefined;
};

/** @internal */
export type DestinationUpdateRequest$Outbound = {
  accessKey: string;
  bucket: string;
  destinationId: string;
  endpoint: string;
  name: string;
  provider: string | null;
  region: string;
  secretAccessKey: string;
  serverId?: string | undefined;
};

/** @internal */
export const DestinationUpdateRequest$outboundSchema: z.ZodType<
  DestinationUpdateRequest$Outbound,
  z.ZodTypeDef,
  DestinationUpdateRequest
> = z.object({
  accessKey: z.string(),
  bucket: z.string(),
  destinationId: z.string(),
  endpoint: z.string(),
  name: z.string(),
  provider: z.nullable(z.string()),
  region: z.string(),
  secretAccessKey: z.string(),
  serverId: z.string().optional(),
});

export function destinationUpdateRequestToJSON(
  destinationUpdateRequest: DestinationUpdateRequest,
): string {
  return JSON.stringify(
    DestinationUpdateRequest$outboundSchema.parse(destinationUpdateRequest),
  );
}
