/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DestinationTestConnectionRequest = {
  accessKey: string;
  bucket: string;
  endpoint: string;
  name: string;
  provider: string | null;
  region: string;
  secretAccessKey: string;
  serverId?: string | undefined;
};

/** @internal */
export type DestinationTestConnectionRequest$Outbound = {
  accessKey: string;
  bucket: string;
  endpoint: string;
  name: string;
  provider: string | null;
  region: string;
  secretAccessKey: string;
  serverId?: string | undefined;
};

/** @internal */
export const DestinationTestConnectionRequest$outboundSchema: z.ZodType<
  DestinationTestConnectionRequest$Outbound,
  z.ZodTypeDef,
  DestinationTestConnectionRequest
> = z.object({
  accessKey: z.string(),
  bucket: z.string(),
  endpoint: z.string(),
  name: z.string(),
  provider: z.nullable(z.string()),
  region: z.string(),
  secretAccessKey: z.string(),
  serverId: z.string().optional(),
});

export function destinationTestConnectionRequestToJSON(
  destinationTestConnectionRequest: DestinationTestConnectionRequest,
): string {
  return JSON.stringify(
    DestinationTestConnectionRequest$outboundSchema.parse(
      destinationTestConnectionRequest,
    ),
  );
}
