/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DestinationRemoveRequest = {
  destinationId: string;
};

/** @internal */
export type DestinationRemoveRequest$Outbound = {
  destinationId: string;
};

/** @internal */
export const DestinationRemoveRequest$outboundSchema: z.ZodType<
  DestinationRemoveRequest$Outbound,
  z.ZodTypeDef,
  DestinationRemoveRequest
> = z.object({
  destinationId: z.string(),
});

export function destinationRemoveRequestToJSON(
  destinationRemoveRequest: DestinationRemoveRequest,
): string {
  return JSON.stringify(
    DestinationRemoveRequest$outboundSchema.parse(destinationRemoveRequest),
  );
}
