/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DockerGetConfigRequest = {
  containerId: string;
  serverId?: string | undefined;
};

/** @internal */
export type DockerGetConfigRequest$Outbound = {
  containerId: string;
  serverId?: string | undefined;
};

/** @internal */
export const DockerGetConfigRequest$outboundSchema: z.ZodType<
  DockerGetConfigRequest$Outbound,
  z.ZodTypeDef,
  DockerGetConfigRequest
> = z.object({
  containerId: z.string(),
  serverId: z.string().optional(),
});

export function dockerGetConfigRequestToJSON(
  dockerGetConfigRequest: DockerGetConfigRequest,
): string {
  return JSON.stringify(
    DockerGetConfigRequest$outboundSchema.parse(dockerGetConfigRequest),
  );
}
