/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const DockerGetContainersByAppLabelType = {
  Standalone: "standalone",
  Swarm: "swarm",
} as const;
export type DockerGetContainersByAppLabelType = ClosedEnum<
  typeof DockerGetContainersByAppLabelType
>;

export type DockerGetContainersByAppLabelRequest = {
  appName: string;
  serverId?: string | undefined;
  type: DockerGetContainersByAppLabelType;
};

/** @internal */
export const DockerGetContainersByAppLabelType$outboundSchema: z.ZodNativeEnum<
  typeof DockerGetContainersByAppLabelType
> = z.nativeEnum(DockerGetContainersByAppLabelType);

/** @internal */
export type DockerGetContainersByAppLabelRequest$Outbound = {
  appName: string;
  serverId?: string | undefined;
  type: string;
};

/** @internal */
export const DockerGetContainersByAppLabelRequest$outboundSchema: z.ZodType<
  DockerGetContainersByAppLabelRequest$Outbound,
  z.ZodTypeDef,
  DockerGetContainersByAppLabelRequest
> = z.object({
  appName: z.string(),
  serverId: z.string().optional(),
  type: DockerGetContainersByAppLabelType$outboundSchema,
});

export function dockerGetContainersByAppLabelRequestToJSON(
  dockerGetContainersByAppLabelRequest: DockerGetContainersByAppLabelRequest,
): string {
  return JSON.stringify(
    DockerGetContainersByAppLabelRequest$outboundSchema.parse(
      dockerGetContainersByAppLabelRequest,
    ),
  );
}
