/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DomainCanGenerateTraefikMeDomainsRequest = {
  serverId: string;
};

/** @internal */
export type DomainCanGenerateTraefikMeDomainsRequest$Outbound = {
  serverId: string;
};

/** @internal */
export const DomainCanGenerateTraefikMeDomainsRequest$outboundSchema: z.ZodType<
  DomainCanGenerateTraefikMeDomainsRequest$Outbound,
  z.ZodTypeDef,
  DomainCanGenerateTraefikMeDomainsRequest
> = z.object({
  serverId: z.string(),
});

export function domainCanGenerateTraefikMeDomainsRequestToJSON(
  domainCanGenerateTraefikMeDomainsRequest:
    DomainCanGenerateTraefikMeDomainsRequest,
): string {
  return JSON.stringify(
    DomainCanGenerateTraefikMeDomainsRequest$outboundSchema.parse(
      domainCanGenerateTraefikMeDomainsRequest,
    ),
  );
}
