/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DomainGenerateDomainRequest = {
  appName: string;
  serverId?: string | undefined;
};

/** @internal */
export type DomainGenerateDomainRequest$Outbound = {
  appName: string;
  serverId?: string | undefined;
};

/** @internal */
export const DomainGenerateDomainRequest$outboundSchema: z.ZodType<
  DomainGenerateDomainRequest$Outbound,
  z.ZodTypeDef,
  DomainGenerateDomainRequest
> = z.object({
  appName: z.string(),
  serverId: z.string().optional(),
});

export function domainGenerateDomainRequestToJSON(
  domainGenerateDomainRequest: DomainGenerateDomainRequest,
): string {
  return JSON.stringify(
    DomainGenerateDomainRequest$outboundSchema.parse(
      domainGenerateDomainRequest,
    ),
  );
}
