/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type EnvironmentUpdateRequest = {
  createdAt?: string | undefined;
  description?: string | null | undefined;
  env?: string | undefined;
  environmentId: string;
  name?: string | undefined;
  projectId?: string | undefined;
};

/**
 * Successful response
 */
export type EnvironmentUpdateResponseBody = {
  createdAt: string;
  description: string | null;
  env: string;
  environmentId: string;
  name: string;
  projectId: string;
};

export type EnvironmentUpdateResponse =
  | EnvironmentUpdateResponseBody
  | models.ErrorT;

/** @internal */
export type EnvironmentUpdateRequest$Outbound = {
  createdAt?: string | undefined;
  description?: string | null | undefined;
  env?: string | undefined;
  environmentId: string;
  name?: string | undefined;
  projectId?: string | undefined;
};

/** @internal */
export const EnvironmentUpdateRequest$outboundSchema: z.ZodType<
  EnvironmentUpdateRequest$Outbound,
  z.ZodTypeDef,
  EnvironmentUpdateRequest
> = z.object({
  createdAt: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  env: z.string().optional(),
  environmentId: z.string(),
  name: z.string().optional(),
  projectId: z.string().optional(),
});

export function environmentUpdateRequestToJSON(
  environmentUpdateRequest: EnvironmentUpdateRequest,
): string {
  return JSON.stringify(
    EnvironmentUpdateRequest$outboundSchema.parse(environmentUpdateRequest),
  );
}

/** @internal */
export const EnvironmentUpdateResponseBody$inboundSchema: z.ZodType<
  EnvironmentUpdateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  environmentId: z.string(),
  name: z.string(),
  projectId: z.string(),
});

export function environmentUpdateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<EnvironmentUpdateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvironmentUpdateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvironmentUpdateResponseBody' from JSON`,
  );
}

/** @internal */
export const EnvironmentUpdateResponse$inboundSchema: z.ZodType<
  EnvironmentUpdateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => EnvironmentUpdateResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function environmentUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<EnvironmentUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvironmentUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvironmentUpdateResponse' from JSON`,
  );
}
