/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type EnvironmentRemoveRequest = {
  environmentId: string;
};

/**
 * Successful response
 */
export type EnvironmentRemoveResponseBody = {
  createdAt: string;
  description: string | null;
  env: string;
  environmentId: string;
  name: string;
  projectId: string;
};

export type EnvironmentRemoveResponse =
  | EnvironmentRemoveResponseBody
  | models.ErrorT;

/** @internal */
export type EnvironmentRemoveRequest$Outbound = {
  environmentId: string;
};

/** @internal */
export const EnvironmentRemoveRequest$outboundSchema: z.ZodType<
  EnvironmentRemoveRequest$Outbound,
  z.ZodTypeDef,
  EnvironmentRemoveRequest
> = z.object({
  environmentId: z.string(),
});

export function environmentRemoveRequestToJSON(
  environmentRemoveRequest: EnvironmentRemoveRequest,
): string {
  return JSON.stringify(
    EnvironmentRemoveRequest$outboundSchema.parse(environmentRemoveRequest),
  );
}

/** @internal */
export const EnvironmentRemoveResponseBody$inboundSchema: z.ZodType<
  EnvironmentRemoveResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  environmentId: z.string(),
  name: z.string(),
  projectId: z.string(),
});

export function environmentRemoveResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<EnvironmentRemoveResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvironmentRemoveResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvironmentRemoveResponseBody' from JSON`,
  );
}

/** @internal */
export const EnvironmentRemoveResponse$inboundSchema: z.ZodType<
  EnvironmentRemoveResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => EnvironmentRemoveResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function environmentRemoveResponseFromJSON(
  jsonString: string,
): SafeParseResult<EnvironmentRemoveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvironmentRemoveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvironmentRemoveResponse' from JSON`,
  );
}
