/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GiteaGetGiteaRepositoriesRequest = {
  giteaId: string;
};

/** @internal */
export type GiteaGetGiteaRepositoriesRequest$Outbound = {
  giteaId: string;
};

/** @internal */
export const GiteaGetGiteaRepositoriesRequest$outboundSchema: z.ZodType<
  GiteaGetGiteaRepositoriesRequest$Outbound,
  z.ZodTypeDef,
  GiteaGetGiteaRepositoriesRequest
> = z.object({
  giteaId: z.string(),
});

export function giteaGetGiteaRepositoriesRequestToJSON(
  giteaGetGiteaRepositoriesRequest: GiteaGetGiteaRepositoriesRequest,
): string {
  return JSON.stringify(
    GiteaGetGiteaRepositoriesRequest$outboundSchema.parse(
      giteaGetGiteaRepositoriesRequest,
    ),
  );
}
