/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const GithubGithubProvidersProviderType = {
  Github: "github",
  Gitlab: "gitlab",
  Bitbucket: "bitbucket",
  Gitea: "gitea",
} as const;
export type GithubGithubProvidersProviderType = ClosedEnum<
  typeof GithubGithubProvidersProviderType
>;

export type GithubGithubProvidersGitProvider = {
  createdAt: string;
  gitProviderId: string;
  name: string;
  organizationId: string;
  providerType: GithubGithubProvidersProviderType;
  userId: string;
};

export type GithubGithubProvidersResponseBody = {
  gitProvider: GithubGithubProvidersGitProvider;
  githubId: string;
};

export type GithubGithubProvidersResponse =
  | models.ErrorT
  | Array<GithubGithubProvidersResponseBody>;

/** @internal */
export const GithubGithubProvidersProviderType$inboundSchema: z.ZodNativeEnum<
  typeof GithubGithubProvidersProviderType
> = z.nativeEnum(GithubGithubProvidersProviderType);

/** @internal */
export const GithubGithubProvidersGitProvider$inboundSchema: z.ZodType<
  GithubGithubProvidersGitProvider,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  gitProviderId: z.string(),
  name: z.string(),
  organizationId: z.string(),
  providerType: GithubGithubProvidersProviderType$inboundSchema,
  userId: z.string(),
});

export function githubGithubProvidersGitProviderFromJSON(
  jsonString: string,
): SafeParseResult<GithubGithubProvidersGitProvider, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GithubGithubProvidersGitProvider$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GithubGithubProvidersGitProvider' from JSON`,
  );
}

/** @internal */
export const GithubGithubProvidersResponseBody$inboundSchema: z.ZodType<
  GithubGithubProvidersResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  gitProvider: z.lazy(() => GithubGithubProvidersGitProvider$inboundSchema),
  githubId: z.string(),
});

export function githubGithubProvidersResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GithubGithubProvidersResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GithubGithubProvidersResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GithubGithubProvidersResponseBody' from JSON`,
  );
}

/** @internal */
export const GithubGithubProvidersResponse$inboundSchema: z.ZodType<
  GithubGithubProvidersResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.ErrorT$inboundSchema,
  z.array(z.lazy(() => GithubGithubProvidersResponseBody$inboundSchema)),
]);

export function githubGithubProvidersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GithubGithubProvidersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GithubGithubProvidersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GithubGithubProvidersResponse' from JSON`,
  );
}
