/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GitlabGetGitlabRepositoriesRequest = {
  gitlabId: string;
};

/** @internal */
export type GitlabGetGitlabRepositoriesRequest$Outbound = {
  gitlabId: string;
};

/** @internal */
export const GitlabGetGitlabRepositoriesRequest$outboundSchema: z.ZodType<
  GitlabGetGitlabRepositoriesRequest$Outbound,
  z.ZodTypeDef,
  GitlabGetGitlabRepositoriesRequest
> = z.object({
  gitlabId: z.string(),
});

export function gitlabGetGitlabRepositoriesRequestToJSON(
  gitlabGetGitlabRepositoriesRequest: GitlabGetGitlabRepositoriesRequest,
): string {
  return JSON.stringify(
    GitlabGetGitlabRepositoriesRequest$outboundSchema.parse(
      gitlabGetGitlabRepositoriesRequest,
    ),
  );
}
