/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type MariadbReloadRequest = {
  appName: string;
  mariadbId: string;
};

export type MariadbReloadResponse = models.ErrorT | boolean;

/** @internal */
export type MariadbReloadRequest$Outbound = {
  appName: string;
  mariadbId: string;
};

/** @internal */
export const MariadbReloadRequest$outboundSchema: z.ZodType<
  MariadbReloadRequest$Outbound,
  z.ZodTypeDef,
  MariadbReloadRequest
> = z.object({
  appName: z.string(),
  mariadbId: z.string(),
});

export function mariadbReloadRequestToJSON(
  mariadbReloadRequest: MariadbReloadRequest,
): string {
  return JSON.stringify(
    MariadbReloadRequest$outboundSchema.parse(mariadbReloadRequest),
  );
}

/** @internal */
export const MariadbReloadResponse$inboundSchema: z.ZodType<
  MariadbReloadResponse,
  z.ZodTypeDef,
  unknown
> = z.union([models.ErrorT$inboundSchema, z.boolean()]);

export function mariadbReloadResponseFromJSON(
  jsonString: string,
): SafeParseResult<MariadbReloadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MariadbReloadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MariadbReloadResponse' from JSON`,
  );
}
