/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type MariadbCreateRequest = {
  appName: string;
  databaseName: string;
  databasePassword: string;
  databaseRootPassword: string;
  databaseUser: string;
  description?: string | null | undefined;
  dockerImage?: string | undefined;
  environmentId: string;
  name: string;
  serverId?: string | null | undefined;
};

export type MariadbCreateResponse = models.ErrorT | boolean;

/** @internal */
export type MariadbCreateRequest$Outbound = {
  appName: string;
  databaseName: string;
  databasePassword: string;
  databaseRootPassword: string;
  databaseUser: string;
  description?: string | null | undefined;
  dockerImage: string;
  environmentId: string;
  name: string;
  serverId?: string | null | undefined;
};

/** @internal */
export const MariadbCreateRequest$outboundSchema: z.ZodType<
  MariadbCreateRequest$Outbound,
  z.ZodTypeDef,
  MariadbCreateRequest
> = z.object({
  appName: z.string(),
  databaseName: z.string(),
  databasePassword: z.string(),
  databaseRootPassword: z.string(),
  databaseUser: z.string(),
  description: z.nullable(z.string()).optional(),
  dockerImage: z.string().default("mariadb:6"),
  environmentId: z.string(),
  name: z.string(),
  serverId: z.nullable(z.string()).optional(),
});

export function mariadbCreateRequestToJSON(
  mariadbCreateRequest: MariadbCreateRequest,
): string {
  return JSON.stringify(
    MariadbCreateRequest$outboundSchema.parse(mariadbCreateRequest),
  );
}

/** @internal */
export const MariadbCreateResponse$inboundSchema: z.ZodType<
  MariadbCreateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([models.ErrorT$inboundSchema, z.boolean()]);

export function mariadbCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<MariadbCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MariadbCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MariadbCreateResponse' from JSON`,
  );
}
