/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const MongoUpdateApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type MongoUpdateApplicationStatus = ClosedEnum<
  typeof MongoUpdateApplicationStatus
>;

export type MongoUpdateHealthCheckSwarm = {
  interval?: number | undefined;
  retries?: number | undefined;
  startPeriod?: number | undefined;
  test?: Array<string> | undefined;
  timeout?: number | undefined;
};

export type MongoUpdateGlobal = {};

export type MongoUpdateGlobalJob = {};

export type MongoUpdateReplicated = {
  replicas?: number | undefined;
};

export type MongoUpdateReplicatedJob = {
  maxConcurrent?: number | undefined;
  totalCompletions?: number | undefined;
};

export type MongoUpdateModeSwarm = {
  global?: MongoUpdateGlobal | undefined;
  globalJob?: MongoUpdateGlobalJob | undefined;
  replicated?: MongoUpdateReplicated | undefined;
  replicatedJob?: MongoUpdateReplicatedJob | undefined;
};

export type MongoUpdateDriverOpts = {};

export type MongoUpdateNetworkSwarm = {
  aliases?: Array<string> | undefined;
  driverOpts?: MongoUpdateDriverOpts | undefined;
  target?: string | undefined;
};

export type MongoUpdatePlatform = {
  architecture: string;
  os: string;
};

export type MongoUpdateSpread = {
  spreadDescriptor: string;
};

export type MongoUpdatePreference = {
  spread: MongoUpdateSpread;
};

export type MongoUpdatePlacementSwarm = {
  constraints?: Array<string> | undefined;
  maxReplicas?: number | undefined;
  platforms?: Array<MongoUpdatePlatform> | undefined;
  preferences?: Array<MongoUpdatePreference> | undefined;
};

export type MongoUpdateRestartPolicySwarm = {
  condition?: string | undefined;
  delay?: number | undefined;
  maxAttempts?: number | undefined;
  window?: number | undefined;
};

export type MongoUpdateRollbackConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

export type MongoUpdateUpdateConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

export type MongoUpdateRequest = {
  appName?: string | undefined;
  applicationStatus?: MongoUpdateApplicationStatus | undefined;
  command?: string | null | undefined;
  cpuLimit?: string | null | undefined;
  cpuReservation?: string | null | undefined;
  createdAt?: string | undefined;
  databasePassword?: string | undefined;
  databaseUser?: string | undefined;
  description?: string | null | undefined;
  dockerImage?: string | undefined;
  env?: string | null | undefined;
  environmentId?: string | undefined;
  externalPort?: number | null | undefined;
  healthCheckSwarm?: MongoUpdateHealthCheckSwarm | null | undefined;
  labelsSwarm?: { [k: string]: string } | null | undefined;
  memoryLimit?: string | null | undefined;
  memoryReservation?: string | null | undefined;
  modeSwarm?: MongoUpdateModeSwarm | null | undefined;
  mongoId: string;
  name?: string | undefined;
  networkSwarm?: Array<MongoUpdateNetworkSwarm> | null | undefined;
  placementSwarm?: MongoUpdatePlacementSwarm | null | undefined;
  replicaSets?: boolean | null | undefined;
  replicas?: number | undefined;
  restartPolicySwarm?: MongoUpdateRestartPolicySwarm | null | undefined;
  rollbackConfigSwarm?: MongoUpdateRollbackConfigSwarm | null | undefined;
  updateConfigSwarm?: MongoUpdateUpdateConfigSwarm | null | undefined;
};

export type MongoUpdateResponse = models.ErrorT | boolean;

/** @internal */
export const MongoUpdateApplicationStatus$outboundSchema: z.ZodNativeEnum<
  typeof MongoUpdateApplicationStatus
> = z.nativeEnum(MongoUpdateApplicationStatus);

/** @internal */
export type MongoUpdateHealthCheckSwarm$Outbound = {
  Interval?: number | undefined;
  Retries?: number | undefined;
  StartPeriod?: number | undefined;
  Test?: Array<string> | undefined;
  Timeout?: number | undefined;
};

/** @internal */
export const MongoUpdateHealthCheckSwarm$outboundSchema: z.ZodType<
  MongoUpdateHealthCheckSwarm$Outbound,
  z.ZodTypeDef,
  MongoUpdateHealthCheckSwarm
> = z.object({
  interval: z.number().optional(),
  retries: z.number().optional(),
  startPeriod: z.number().optional(),
  test: z.array(z.string()).optional(),
  timeout: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    interval: "Interval",
    retries: "Retries",
    startPeriod: "StartPeriod",
    test: "Test",
    timeout: "Timeout",
  });
});

export function mongoUpdateHealthCheckSwarmToJSON(
  mongoUpdateHealthCheckSwarm: MongoUpdateHealthCheckSwarm,
): string {
  return JSON.stringify(
    MongoUpdateHealthCheckSwarm$outboundSchema.parse(
      mongoUpdateHealthCheckSwarm,
    ),
  );
}

/** @internal */
export type MongoUpdateGlobal$Outbound = {};

/** @internal */
export const MongoUpdateGlobal$outboundSchema: z.ZodType<
  MongoUpdateGlobal$Outbound,
  z.ZodTypeDef,
  MongoUpdateGlobal
> = z.object({});

export function mongoUpdateGlobalToJSON(
  mongoUpdateGlobal: MongoUpdateGlobal,
): string {
  return JSON.stringify(
    MongoUpdateGlobal$outboundSchema.parse(mongoUpdateGlobal),
  );
}

/** @internal */
export type MongoUpdateGlobalJob$Outbound = {};

/** @internal */
export const MongoUpdateGlobalJob$outboundSchema: z.ZodType<
  MongoUpdateGlobalJob$Outbound,
  z.ZodTypeDef,
  MongoUpdateGlobalJob
> = z.object({});

export function mongoUpdateGlobalJobToJSON(
  mongoUpdateGlobalJob: MongoUpdateGlobalJob,
): string {
  return JSON.stringify(
    MongoUpdateGlobalJob$outboundSchema.parse(mongoUpdateGlobalJob),
  );
}

/** @internal */
export type MongoUpdateReplicated$Outbound = {
  Replicas?: number | undefined;
};

/** @internal */
export const MongoUpdateReplicated$outboundSchema: z.ZodType<
  MongoUpdateReplicated$Outbound,
  z.ZodTypeDef,
  MongoUpdateReplicated
> = z.object({
  replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    replicas: "Replicas",
  });
});

export function mongoUpdateReplicatedToJSON(
  mongoUpdateReplicated: MongoUpdateReplicated,
): string {
  return JSON.stringify(
    MongoUpdateReplicated$outboundSchema.parse(mongoUpdateReplicated),
  );
}

/** @internal */
export type MongoUpdateReplicatedJob$Outbound = {
  MaxConcurrent?: number | undefined;
  TotalCompletions?: number | undefined;
};

/** @internal */
export const MongoUpdateReplicatedJob$outboundSchema: z.ZodType<
  MongoUpdateReplicatedJob$Outbound,
  z.ZodTypeDef,
  MongoUpdateReplicatedJob
> = z.object({
  maxConcurrent: z.number().optional(),
  totalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    maxConcurrent: "MaxConcurrent",
    totalCompletions: "TotalCompletions",
  });
});

export function mongoUpdateReplicatedJobToJSON(
  mongoUpdateReplicatedJob: MongoUpdateReplicatedJob,
): string {
  return JSON.stringify(
    MongoUpdateReplicatedJob$outboundSchema.parse(mongoUpdateReplicatedJob),
  );
}

/** @internal */
export type MongoUpdateModeSwarm$Outbound = {
  Global?: MongoUpdateGlobal$Outbound | undefined;
  GlobalJob?: MongoUpdateGlobalJob$Outbound | undefined;
  Replicated?: MongoUpdateReplicated$Outbound | undefined;
  ReplicatedJob?: MongoUpdateReplicatedJob$Outbound | undefined;
};

/** @internal */
export const MongoUpdateModeSwarm$outboundSchema: z.ZodType<
  MongoUpdateModeSwarm$Outbound,
  z.ZodTypeDef,
  MongoUpdateModeSwarm
> = z.object({
  global: z.lazy(() => MongoUpdateGlobal$outboundSchema).optional(),
  globalJob: z.lazy(() => MongoUpdateGlobalJob$outboundSchema).optional(),
  replicated: z.lazy(() => MongoUpdateReplicated$outboundSchema).optional(),
  replicatedJob: z.lazy(() => MongoUpdateReplicatedJob$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    global: "Global",
    globalJob: "GlobalJob",
    replicated: "Replicated",
    replicatedJob: "ReplicatedJob",
  });
});

export function mongoUpdateModeSwarmToJSON(
  mongoUpdateModeSwarm: MongoUpdateModeSwarm,
): string {
  return JSON.stringify(
    MongoUpdateModeSwarm$outboundSchema.parse(mongoUpdateModeSwarm),
  );
}

/** @internal */
export type MongoUpdateDriverOpts$Outbound = {};

/** @internal */
export const MongoUpdateDriverOpts$outboundSchema: z.ZodType<
  MongoUpdateDriverOpts$Outbound,
  z.ZodTypeDef,
  MongoUpdateDriverOpts
> = z.object({});

export function mongoUpdateDriverOptsToJSON(
  mongoUpdateDriverOpts: MongoUpdateDriverOpts,
): string {
  return JSON.stringify(
    MongoUpdateDriverOpts$outboundSchema.parse(mongoUpdateDriverOpts),
  );
}

/** @internal */
export type MongoUpdateNetworkSwarm$Outbound = {
  Aliases?: Array<string> | undefined;
  DriverOpts?: MongoUpdateDriverOpts$Outbound | undefined;
  Target?: string | undefined;
};

/** @internal */
export const MongoUpdateNetworkSwarm$outboundSchema: z.ZodType<
  MongoUpdateNetworkSwarm$Outbound,
  z.ZodTypeDef,
  MongoUpdateNetworkSwarm
> = z.object({
  aliases: z.array(z.string()).optional(),
  driverOpts: z.lazy(() => MongoUpdateDriverOpts$outboundSchema).optional(),
  target: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    aliases: "Aliases",
    driverOpts: "DriverOpts",
    target: "Target",
  });
});

export function mongoUpdateNetworkSwarmToJSON(
  mongoUpdateNetworkSwarm: MongoUpdateNetworkSwarm,
): string {
  return JSON.stringify(
    MongoUpdateNetworkSwarm$outboundSchema.parse(mongoUpdateNetworkSwarm),
  );
}

/** @internal */
export type MongoUpdatePlatform$Outbound = {
  Architecture: string;
  OS: string;
};

/** @internal */
export const MongoUpdatePlatform$outboundSchema: z.ZodType<
  MongoUpdatePlatform$Outbound,
  z.ZodTypeDef,
  MongoUpdatePlatform
> = z.object({
  architecture: z.string(),
  os: z.string(),
}).transform((v) => {
  return remap$(v, {
    architecture: "Architecture",
    os: "OS",
  });
});

export function mongoUpdatePlatformToJSON(
  mongoUpdatePlatform: MongoUpdatePlatform,
): string {
  return JSON.stringify(
    MongoUpdatePlatform$outboundSchema.parse(mongoUpdatePlatform),
  );
}

/** @internal */
export type MongoUpdateSpread$Outbound = {
  SpreadDescriptor: string;
};

/** @internal */
export const MongoUpdateSpread$outboundSchema: z.ZodType<
  MongoUpdateSpread$Outbound,
  z.ZodTypeDef,
  MongoUpdateSpread
> = z.object({
  spreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    spreadDescriptor: "SpreadDescriptor",
  });
});

export function mongoUpdateSpreadToJSON(
  mongoUpdateSpread: MongoUpdateSpread,
): string {
  return JSON.stringify(
    MongoUpdateSpread$outboundSchema.parse(mongoUpdateSpread),
  );
}

/** @internal */
export type MongoUpdatePreference$Outbound = {
  Spread: MongoUpdateSpread$Outbound;
};

/** @internal */
export const MongoUpdatePreference$outboundSchema: z.ZodType<
  MongoUpdatePreference$Outbound,
  z.ZodTypeDef,
  MongoUpdatePreference
> = z.object({
  spread: z.lazy(() => MongoUpdateSpread$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    spread: "Spread",
  });
});

export function mongoUpdatePreferenceToJSON(
  mongoUpdatePreference: MongoUpdatePreference,
): string {
  return JSON.stringify(
    MongoUpdatePreference$outboundSchema.parse(mongoUpdatePreference),
  );
}

/** @internal */
export type MongoUpdatePlacementSwarm$Outbound = {
  Constraints?: Array<string> | undefined;
  MaxReplicas?: number | undefined;
  Platforms?: Array<MongoUpdatePlatform$Outbound> | undefined;
  Preferences?: Array<MongoUpdatePreference$Outbound> | undefined;
};

/** @internal */
export const MongoUpdatePlacementSwarm$outboundSchema: z.ZodType<
  MongoUpdatePlacementSwarm$Outbound,
  z.ZodTypeDef,
  MongoUpdatePlacementSwarm
> = z.object({
  constraints: z.array(z.string()).optional(),
  maxReplicas: z.number().optional(),
  platforms: z.array(z.lazy(() => MongoUpdatePlatform$outboundSchema))
    .optional(),
  preferences: z.array(z.lazy(() => MongoUpdatePreference$outboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    constraints: "Constraints",
    maxReplicas: "MaxReplicas",
    platforms: "Platforms",
    preferences: "Preferences",
  });
});

export function mongoUpdatePlacementSwarmToJSON(
  mongoUpdatePlacementSwarm: MongoUpdatePlacementSwarm,
): string {
  return JSON.stringify(
    MongoUpdatePlacementSwarm$outboundSchema.parse(mongoUpdatePlacementSwarm),
  );
}

/** @internal */
export type MongoUpdateRestartPolicySwarm$Outbound = {
  Condition?: string | undefined;
  Delay?: number | undefined;
  MaxAttempts?: number | undefined;
  Window?: number | undefined;
};

/** @internal */
export const MongoUpdateRestartPolicySwarm$outboundSchema: z.ZodType<
  MongoUpdateRestartPolicySwarm$Outbound,
  z.ZodTypeDef,
  MongoUpdateRestartPolicySwarm
> = z.object({
  condition: z.string().optional(),
  delay: z.number().optional(),
  maxAttempts: z.number().optional(),
  window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    condition: "Condition",
    delay: "Delay",
    maxAttempts: "MaxAttempts",
    window: "Window",
  });
});

export function mongoUpdateRestartPolicySwarmToJSON(
  mongoUpdateRestartPolicySwarm: MongoUpdateRestartPolicySwarm,
): string {
  return JSON.stringify(
    MongoUpdateRestartPolicySwarm$outboundSchema.parse(
      mongoUpdateRestartPolicySwarm,
    ),
  );
}

/** @internal */
export type MongoUpdateRollbackConfigSwarm$Outbound = {
  Delay?: number | undefined;
  FailureAction?: string | undefined;
  MaxFailureRatio?: number | undefined;
  Monitor?: number | undefined;
  Order: string;
  Parallelism: number;
};

/** @internal */
export const MongoUpdateRollbackConfigSwarm$outboundSchema: z.ZodType<
  MongoUpdateRollbackConfigSwarm$Outbound,
  z.ZodTypeDef,
  MongoUpdateRollbackConfigSwarm
> = z.object({
  delay: z.number().optional(),
  failureAction: z.string().optional(),
  maxFailureRatio: z.number().optional(),
  monitor: z.number().optional(),
  order: z.string(),
  parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    delay: "Delay",
    failureAction: "FailureAction",
    maxFailureRatio: "MaxFailureRatio",
    monitor: "Monitor",
    order: "Order",
    parallelism: "Parallelism",
  });
});

export function mongoUpdateRollbackConfigSwarmToJSON(
  mongoUpdateRollbackConfigSwarm: MongoUpdateRollbackConfigSwarm,
): string {
  return JSON.stringify(
    MongoUpdateRollbackConfigSwarm$outboundSchema.parse(
      mongoUpdateRollbackConfigSwarm,
    ),
  );
}

/** @internal */
export type MongoUpdateUpdateConfigSwarm$Outbound = {
  Delay?: number | undefined;
  FailureAction?: string | undefined;
  MaxFailureRatio?: number | undefined;
  Monitor?: number | undefined;
  Order: string;
  Parallelism: number;
};

/** @internal */
export const MongoUpdateUpdateConfigSwarm$outboundSchema: z.ZodType<
  MongoUpdateUpdateConfigSwarm$Outbound,
  z.ZodTypeDef,
  MongoUpdateUpdateConfigSwarm
> = z.object({
  delay: z.number().optional(),
  failureAction: z.string().optional(),
  maxFailureRatio: z.number().optional(),
  monitor: z.number().optional(),
  order: z.string(),
  parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    delay: "Delay",
    failureAction: "FailureAction",
    maxFailureRatio: "MaxFailureRatio",
    monitor: "Monitor",
    order: "Order",
    parallelism: "Parallelism",
  });
});

export function mongoUpdateUpdateConfigSwarmToJSON(
  mongoUpdateUpdateConfigSwarm: MongoUpdateUpdateConfigSwarm,
): string {
  return JSON.stringify(
    MongoUpdateUpdateConfigSwarm$outboundSchema.parse(
      mongoUpdateUpdateConfigSwarm,
    ),
  );
}

/** @internal */
export type MongoUpdateRequest$Outbound = {
  appName?: string | undefined;
  applicationStatus?: string | undefined;
  command?: string | null | undefined;
  cpuLimit?: string | null | undefined;
  cpuReservation?: string | null | undefined;
  createdAt?: string | undefined;
  databasePassword?: string | undefined;
  databaseUser?: string | undefined;
  description?: string | null | undefined;
  dockerImage: string;
  env?: string | null | undefined;
  environmentId?: string | undefined;
  externalPort?: number | null | undefined;
  healthCheckSwarm?: MongoUpdateHealthCheckSwarm$Outbound | null | undefined;
  labelsSwarm?: { [k: string]: string } | null | undefined;
  memoryLimit?: string | null | undefined;
  memoryReservation?: string | null | undefined;
  modeSwarm?: MongoUpdateModeSwarm$Outbound | null | undefined;
  mongoId: string;
  name?: string | undefined;
  networkSwarm?: Array<MongoUpdateNetworkSwarm$Outbound> | null | undefined;
  placementSwarm?: MongoUpdatePlacementSwarm$Outbound | null | undefined;
  replicaSets: boolean | null;
  replicas?: number | undefined;
  restartPolicySwarm?:
    | MongoUpdateRestartPolicySwarm$Outbound
    | null
    | undefined;
  rollbackConfigSwarm?:
    | MongoUpdateRollbackConfigSwarm$Outbound
    | null
    | undefined;
  updateConfigSwarm?: MongoUpdateUpdateConfigSwarm$Outbound | null | undefined;
};

/** @internal */
export const MongoUpdateRequest$outboundSchema: z.ZodType<
  MongoUpdateRequest$Outbound,
  z.ZodTypeDef,
  MongoUpdateRequest
> = z.object({
  appName: z.string().optional(),
  applicationStatus: MongoUpdateApplicationStatus$outboundSchema.optional(),
  command: z.nullable(z.string()).optional(),
  cpuLimit: z.nullable(z.string()).optional(),
  cpuReservation: z.nullable(z.string()).optional(),
  createdAt: z.string().optional(),
  databasePassword: z.string().optional(),
  databaseUser: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  dockerImage: z.string().default("mongo:15"),
  env: z.nullable(z.string()).optional(),
  environmentId: z.string().optional(),
  externalPort: z.nullable(z.number()).optional(),
  healthCheckSwarm: z.nullable(
    z.lazy(() => MongoUpdateHealthCheckSwarm$outboundSchema),
  ).optional(),
  labelsSwarm: z.nullable(z.record(z.string())).optional(),
  memoryLimit: z.nullable(z.string()).optional(),
  memoryReservation: z.nullable(z.string()).optional(),
  modeSwarm: z.nullable(z.lazy(() => MongoUpdateModeSwarm$outboundSchema))
    .optional(),
  mongoId: z.string(),
  name: z.string().optional(),
  networkSwarm: z.nullable(
    z.array(z.lazy(() => MongoUpdateNetworkSwarm$outboundSchema)),
  ).optional(),
  placementSwarm: z.nullable(
    z.lazy(() => MongoUpdatePlacementSwarm$outboundSchema),
  ).optional(),
  replicaSets: z.nullable(z.boolean().default(false)),
  replicas: z.number().optional(),
  restartPolicySwarm: z.nullable(
    z.lazy(() => MongoUpdateRestartPolicySwarm$outboundSchema),
  ).optional(),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => MongoUpdateRollbackConfigSwarm$outboundSchema),
  ).optional(),
  updateConfigSwarm: z.nullable(
    z.lazy(() => MongoUpdateUpdateConfigSwarm$outboundSchema),
  ).optional(),
});

export function mongoUpdateRequestToJSON(
  mongoUpdateRequest: MongoUpdateRequest,
): string {
  return JSON.stringify(
    MongoUpdateRequest$outboundSchema.parse(mongoUpdateRequest),
  );
}

/** @internal */
export const MongoUpdateResponse$inboundSchema: z.ZodType<
  MongoUpdateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([models.ErrorT$inboundSchema, z.boolean()]);

export function mongoUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<MongoUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoUpdateResponse' from JSON`,
  );
}
