/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const MongoChangeStatusApplicationStatusRequest = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type MongoChangeStatusApplicationStatusRequest = ClosedEnum<
  typeof MongoChangeStatusApplicationStatusRequest
>;

export type MongoChangeStatusRequest = {
  applicationStatus: MongoChangeStatusApplicationStatusRequest;
  mongoId: string;
};

export const MongoChangeStatusApplicationStatusResponse = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type MongoChangeStatusApplicationStatusResponse = ClosedEnum<
  typeof MongoChangeStatusApplicationStatusResponse
>;

export const MongoChangeStatusBackupType = {
  Database: "database",
  Compose: "compose",
} as const;
export type MongoChangeStatusBackupType = ClosedEnum<
  typeof MongoChangeStatusBackupType
>;

export const MongoChangeStatusDatabaseType = {
  Postgres: "postgres",
  Mariadb: "mariadb",
  Mysql: "mysql",
  Mongo: "mongo",
  WebServer: "web-server",
} as const;
export type MongoChangeStatusDatabaseType = ClosedEnum<
  typeof MongoChangeStatusDatabaseType
>;

export const MongoChangeStatusMetadataEnum = {
  Null: "null",
} as const;
export type MongoChangeStatusMetadataEnum = ClosedEnum<
  typeof MongoChangeStatusMetadataEnum
>;

export type MongoChangeStatusMariadb = {
  databasePassword: string;
  databaseUser: string;
};

export type MongoChangeStatusMongo = {
  databasePassword: string;
  databaseUser: string;
};

export type MongoChangeStatusMysql = {
  databaseRootPassword: string;
};

export type MongoChangeStatusPostgres = {
  databaseUser: string;
};

export type MongoChangeStatusMetadata = {
  mariadb?: MongoChangeStatusMariadb | undefined;
  mongo?: MongoChangeStatusMongo | undefined;
  mysql?: MongoChangeStatusMysql | undefined;
  postgres?: MongoChangeStatusPostgres | undefined;
};

export type MongoChangeStatusMetadataUnion =
  | MongoChangeStatusMetadata
  | MongoChangeStatusMetadataEnum;

export type MongoChangeStatusBackup = {
  appName: string;
  backupId: string;
  backupType: MongoChangeStatusBackupType;
  composeId: string | null;
  database: string;
  databaseType: MongoChangeStatusDatabaseType;
  destinationId: string;
  enabled: boolean | null;
  keepLatestCount: number | null;
  mariadbId: string | null;
  metadata?:
    | MongoChangeStatusMetadata
    | MongoChangeStatusMetadataEnum
    | null
    | undefined;
  mongoId: string | null;
  mysqlId: string | null;
  postgresId: string | null;
  prefix: string;
  schedule: string;
  serviceName: string | null;
  userId: string | null;
};

export type MongoChangeStatusProject = {
  createdAt: string;
  description: string | null;
  env: string;
  name: string;
  organizationId: string;
  projectId: string;
};

export type MongoChangeStatusEnvironment = {
  createdAt: string;
  description: string | null;
  env: string;
  environmentId: string;
  name: string;
  project: MongoChangeStatusProject;
  projectId: string;
};

export type MongoChangeStatusHealthCheckSwarm = {
  interval?: number | undefined;
  retries?: number | undefined;
  startPeriod?: number | undefined;
  test?: Array<string> | undefined;
  timeout?: number | undefined;
};

export type MongoChangeStatusGlobal = {};

export type MongoChangeStatusGlobalJob = {};

export type MongoChangeStatusReplicated = {
  replicas?: number | undefined;
};

export type MongoChangeStatusReplicatedJob = {
  maxConcurrent?: number | undefined;
  totalCompletions?: number | undefined;
};

export type MongoChangeStatusModeSwarm = {
  global?: MongoChangeStatusGlobal | undefined;
  globalJob?: MongoChangeStatusGlobalJob | undefined;
  replicated?: MongoChangeStatusReplicated | undefined;
  replicatedJob?: MongoChangeStatusReplicatedJob | undefined;
};

export const MongoChangeStatusServiceType = {
  Application: "application",
  Postgres: "postgres",
  Mysql: "mysql",
  Mariadb: "mariadb",
  Mongo: "mongo",
  Redis: "redis",
  Compose: "compose",
} as const;
export type MongoChangeStatusServiceType = ClosedEnum<
  typeof MongoChangeStatusServiceType
>;

export const MongoChangeStatusType = {
  Bind: "bind",
  Volume: "volume",
  File: "file",
} as const;
export type MongoChangeStatusType = ClosedEnum<typeof MongoChangeStatusType>;

export type MongoChangeStatusMount = {
  applicationId: string | null;
  composeId: string | null;
  content: string | null;
  filePath: string | null;
  hostPath: string | null;
  mariadbId: string | null;
  mongoId: string | null;
  mountId: string;
  mountPath: string;
  mysqlId: string | null;
  postgresId: string | null;
  redisId: string | null;
  serviceType: MongoChangeStatusServiceType;
  type: MongoChangeStatusType;
  volumeName: string | null;
};

export type MongoChangeStatusDriverOpts = {};

export type MongoChangeStatusNetworkSwarm = {
  aliases?: Array<string> | undefined;
  driverOpts?: MongoChangeStatusDriverOpts | undefined;
  target?: string | undefined;
};

export type MongoChangeStatusPlatform = {
  architecture: string;
  os: string;
};

export type MongoChangeStatusSpread = {
  spreadDescriptor: string;
};

export type MongoChangeStatusPreference = {
  spread: MongoChangeStatusSpread;
};

export type MongoChangeStatusPlacementSwarm = {
  constraints?: Array<string> | undefined;
  maxReplicas?: number | undefined;
  platforms?: Array<MongoChangeStatusPlatform> | undefined;
  preferences?: Array<MongoChangeStatusPreference> | undefined;
};

export type MongoChangeStatusRestartPolicySwarm = {
  condition?: string | undefined;
  delay?: number | undefined;
  maxAttempts?: number | undefined;
  window?: number | undefined;
};

export type MongoChangeStatusRollbackConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

export const MongoChangeStatusMetricsConfigEnum = {
  Null: "null",
} as const;
export type MongoChangeStatusMetricsConfigEnum = ClosedEnum<
  typeof MongoChangeStatusMetricsConfigEnum
>;

export type MongoChangeStatusMetricsConfigUnion1 =
  | string
  | number
  | boolean
  | MongoChangeStatusMetricsConfigEnum;

export type MongoChangeStatusMetricsConfigUnion2 =
  | string
  | number
  | boolean
  | MongoChangeStatusMetricsConfigEnum
  | Array<any>
  | { [k: string]: any };

export const MongoChangeStatusServerStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
export type MongoChangeStatusServerStatus = ClosedEnum<
  typeof MongoChangeStatusServerStatus
>;

export type MongoChangeStatusServer = {
  appName: string;
  command: string;
  createdAt: string;
  description: string | null;
  enableDockerCleanup: boolean;
  ipAddress: string;
  metricsConfig:
    | string
    | number
    | boolean
    | MongoChangeStatusMetricsConfigEnum
    | Array<any>
    | { [k: string]: any };
  name: string;
  organizationId: string;
  port: number;
  serverId: string;
  serverStatus: MongoChangeStatusServerStatus;
  sshKeyId: string | null;
  username: string;
};

export type MongoChangeStatusUpdateConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

/**
 * Successful response
 */
export type MongoChangeStatusResponseBody = {
  appName: string;
  applicationStatus: MongoChangeStatusApplicationStatusResponse;
  backups: Array<MongoChangeStatusBackup>;
  command: string | null;
  cpuLimit: string | null;
  cpuReservation: string | null;
  createdAt: string;
  databasePassword: string;
  databaseUser: string;
  description: string | null;
  dockerImage: string;
  env: string | null;
  environment: MongoChangeStatusEnvironment;
  environmentId: string;
  externalPort: number | null;
  healthCheckSwarm: MongoChangeStatusHealthCheckSwarm | null;
  labelsSwarm: { [k: string]: string } | null;
  memoryLimit: string | null;
  memoryReservation: string | null;
  modeSwarm: MongoChangeStatusModeSwarm | null;
  mongoId: string;
  mounts: Array<MongoChangeStatusMount>;
  name: string;
  networkSwarm: Array<MongoChangeStatusNetworkSwarm> | null;
  placementSwarm: MongoChangeStatusPlacementSwarm | null;
  replicaSets: boolean | null;
  replicas: number;
  restartPolicySwarm: MongoChangeStatusRestartPolicySwarm | null;
  rollbackConfigSwarm: MongoChangeStatusRollbackConfigSwarm | null;
  server: MongoChangeStatusServer | null;
  serverId: string | null;
  updateConfigSwarm: MongoChangeStatusUpdateConfigSwarm | null;
};

export type MongoChangeStatusResponse =
  | MongoChangeStatusResponseBody
  | models.ErrorT;

/** @internal */
export const MongoChangeStatusApplicationStatusRequest$outboundSchema:
  z.ZodNativeEnum<typeof MongoChangeStatusApplicationStatusRequest> = z
    .nativeEnum(MongoChangeStatusApplicationStatusRequest);

/** @internal */
export type MongoChangeStatusRequest$Outbound = {
  applicationStatus: string;
  mongoId: string;
};

/** @internal */
export const MongoChangeStatusRequest$outboundSchema: z.ZodType<
  MongoChangeStatusRequest$Outbound,
  z.ZodTypeDef,
  MongoChangeStatusRequest
> = z.object({
  applicationStatus: MongoChangeStatusApplicationStatusRequest$outboundSchema,
  mongoId: z.string(),
});

export function mongoChangeStatusRequestToJSON(
  mongoChangeStatusRequest: MongoChangeStatusRequest,
): string {
  return JSON.stringify(
    MongoChangeStatusRequest$outboundSchema.parse(mongoChangeStatusRequest),
  );
}

/** @internal */
export const MongoChangeStatusApplicationStatusResponse$inboundSchema:
  z.ZodNativeEnum<typeof MongoChangeStatusApplicationStatusResponse> = z
    .nativeEnum(MongoChangeStatusApplicationStatusResponse);

/** @internal */
export const MongoChangeStatusBackupType$inboundSchema: z.ZodNativeEnum<
  typeof MongoChangeStatusBackupType
> = z.nativeEnum(MongoChangeStatusBackupType);

/** @internal */
export const MongoChangeStatusDatabaseType$inboundSchema: z.ZodNativeEnum<
  typeof MongoChangeStatusDatabaseType
> = z.nativeEnum(MongoChangeStatusDatabaseType);

/** @internal */
export const MongoChangeStatusMetadataEnum$inboundSchema: z.ZodNativeEnum<
  typeof MongoChangeStatusMetadataEnum
> = z.nativeEnum(MongoChangeStatusMetadataEnum);

/** @internal */
export const MongoChangeStatusMariadb$inboundSchema: z.ZodType<
  MongoChangeStatusMariadb,
  z.ZodTypeDef,
  unknown
> = z.object({
  databasePassword: z.string(),
  databaseUser: z.string(),
});

export function mongoChangeStatusMariadbFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusMariadb, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusMariadb$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusMariadb' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusMongo$inboundSchema: z.ZodType<
  MongoChangeStatusMongo,
  z.ZodTypeDef,
  unknown
> = z.object({
  databasePassword: z.string(),
  databaseUser: z.string(),
});

export function mongoChangeStatusMongoFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusMongo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusMongo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusMongo' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusMysql$inboundSchema: z.ZodType<
  MongoChangeStatusMysql,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseRootPassword: z.string(),
});

export function mongoChangeStatusMysqlFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusMysql, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusMysql$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusMysql' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusPostgres$inboundSchema: z.ZodType<
  MongoChangeStatusPostgres,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseUser: z.string(),
});

export function mongoChangeStatusPostgresFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusPostgres, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusPostgres$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusPostgres' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusMetadata$inboundSchema: z.ZodType<
  MongoChangeStatusMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  mariadb: z.lazy(() => MongoChangeStatusMariadb$inboundSchema).optional(),
  mongo: z.lazy(() => MongoChangeStatusMongo$inboundSchema).optional(),
  mysql: z.lazy(() => MongoChangeStatusMysql$inboundSchema).optional(),
  postgres: z.lazy(() => MongoChangeStatusPostgres$inboundSchema).optional(),
});

export function mongoChangeStatusMetadataFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusMetadata' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusMetadataUnion$inboundSchema: z.ZodType<
  MongoChangeStatusMetadataUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => MongoChangeStatusMetadata$inboundSchema),
  MongoChangeStatusMetadataEnum$inboundSchema,
]);

export function mongoChangeStatusMetadataUnionFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusMetadataUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusMetadataUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusMetadataUnion' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusBackup$inboundSchema: z.ZodType<
  MongoChangeStatusBackup,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  backupId: z.string(),
  backupType: MongoChangeStatusBackupType$inboundSchema,
  composeId: z.nullable(z.string()),
  database: z.string(),
  databaseType: MongoChangeStatusDatabaseType$inboundSchema,
  destinationId: z.string(),
  enabled: z.nullable(z.boolean()),
  keepLatestCount: z.nullable(z.number()),
  mariadbId: z.nullable(z.string()),
  metadata: z.nullable(
    z.union([
      z.lazy(() => MongoChangeStatusMetadata$inboundSchema),
      MongoChangeStatusMetadataEnum$inboundSchema,
    ]),
  ).optional(),
  mongoId: z.nullable(z.string()),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  prefix: z.string(),
  schedule: z.string(),
  serviceName: z.nullable(z.string()),
  userId: z.nullable(z.string()),
});

export function mongoChangeStatusBackupFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusBackup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusBackup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusBackup' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusProject$inboundSchema: z.ZodType<
  MongoChangeStatusProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  name: z.string(),
  organizationId: z.string(),
  projectId: z.string(),
});

export function mongoChangeStatusProjectFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusProject' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusEnvironment$inboundSchema: z.ZodType<
  MongoChangeStatusEnvironment,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  environmentId: z.string(),
  name: z.string(),
  project: z.lazy(() => MongoChangeStatusProject$inboundSchema),
  projectId: z.string(),
});

export function mongoChangeStatusEnvironmentFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusEnvironment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusEnvironment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusEnvironment' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusHealthCheckSwarm$inboundSchema: z.ZodType<
  MongoChangeStatusHealthCheckSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Interval: z.number().optional(),
  Retries: z.number().optional(),
  StartPeriod: z.number().optional(),
  Test: z.array(z.string()).optional(),
  Timeout: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Interval": "interval",
    "Retries": "retries",
    "StartPeriod": "startPeriod",
    "Test": "test",
    "Timeout": "timeout",
  });
});

export function mongoChangeStatusHealthCheckSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusHealthCheckSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusHealthCheckSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusHealthCheckSwarm' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusGlobal$inboundSchema: z.ZodType<
  MongoChangeStatusGlobal,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function mongoChangeStatusGlobalFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusGlobal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusGlobal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusGlobal' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusGlobalJob$inboundSchema: z.ZodType<
  MongoChangeStatusGlobalJob,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function mongoChangeStatusGlobalJobFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusGlobalJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusGlobalJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusGlobalJob' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusReplicated$inboundSchema: z.ZodType<
  MongoChangeStatusReplicated,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicas": "replicas",
  });
});

export function mongoChangeStatusReplicatedFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusReplicated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusReplicated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusReplicated' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusReplicatedJob$inboundSchema: z.ZodType<
  MongoChangeStatusReplicatedJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  MaxConcurrent: z.number().optional(),
  TotalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "MaxConcurrent": "maxConcurrent",
    "TotalCompletions": "totalCompletions",
  });
});

export function mongoChangeStatusReplicatedJobFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusReplicatedJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusReplicatedJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusReplicatedJob' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusModeSwarm$inboundSchema: z.ZodType<
  MongoChangeStatusModeSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Global: z.lazy(() => MongoChangeStatusGlobal$inboundSchema).optional(),
  GlobalJob: z.lazy(() => MongoChangeStatusGlobalJob$inboundSchema).optional(),
  Replicated: z.lazy(() => MongoChangeStatusReplicated$inboundSchema)
    .optional(),
  ReplicatedJob: z.lazy(() => MongoChangeStatusReplicatedJob$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Global": "global",
    "GlobalJob": "globalJob",
    "Replicated": "replicated",
    "ReplicatedJob": "replicatedJob",
  });
});

export function mongoChangeStatusModeSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusModeSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusModeSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusModeSwarm' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusServiceType$inboundSchema: z.ZodNativeEnum<
  typeof MongoChangeStatusServiceType
> = z.nativeEnum(MongoChangeStatusServiceType);

/** @internal */
export const MongoChangeStatusType$inboundSchema: z.ZodNativeEnum<
  typeof MongoChangeStatusType
> = z.nativeEnum(MongoChangeStatusType);

/** @internal */
export const MongoChangeStatusMount$inboundSchema: z.ZodType<
  MongoChangeStatusMount,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.nullable(z.string()),
  composeId: z.nullable(z.string()),
  content: z.nullable(z.string()),
  filePath: z.nullable(z.string()),
  hostPath: z.nullable(z.string()),
  mariadbId: z.nullable(z.string()),
  mongoId: z.nullable(z.string()),
  mountId: z.string(),
  mountPath: z.string(),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  redisId: z.nullable(z.string()),
  serviceType: MongoChangeStatusServiceType$inboundSchema,
  type: MongoChangeStatusType$inboundSchema,
  volumeName: z.nullable(z.string()),
});

export function mongoChangeStatusMountFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusMount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusMount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusMount' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusDriverOpts$inboundSchema: z.ZodType<
  MongoChangeStatusDriverOpts,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function mongoChangeStatusDriverOptsFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusDriverOpts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusDriverOpts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusDriverOpts' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusNetworkSwarm$inboundSchema: z.ZodType<
  MongoChangeStatusNetworkSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Aliases: z.array(z.string()).optional(),
  DriverOpts: z.lazy(() => MongoChangeStatusDriverOpts$inboundSchema)
    .optional(),
  Target: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Aliases": "aliases",
    "DriverOpts": "driverOpts",
    "Target": "target",
  });
});

export function mongoChangeStatusNetworkSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusNetworkSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusNetworkSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusNetworkSwarm' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusPlatform$inboundSchema: z.ZodType<
  MongoChangeStatusPlatform,
  z.ZodTypeDef,
  unknown
> = z.object({
  Architecture: z.string(),
  OS: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Architecture": "architecture",
    "OS": "os",
  });
});

export function mongoChangeStatusPlatformFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusPlatform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusPlatform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusPlatform' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusSpread$inboundSchema: z.ZodType<
  MongoChangeStatusSpread,
  z.ZodTypeDef,
  unknown
> = z.object({
  SpreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    "SpreadDescriptor": "spreadDescriptor",
  });
});

export function mongoChangeStatusSpreadFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusSpread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusSpread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusSpread' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusPreference$inboundSchema: z.ZodType<
  MongoChangeStatusPreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  Spread: z.lazy(() => MongoChangeStatusSpread$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Spread": "spread",
  });
});

export function mongoChangeStatusPreferenceFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusPreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusPreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusPreference' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusPlacementSwarm$inboundSchema: z.ZodType<
  MongoChangeStatusPlacementSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Constraints: z.array(z.string()).optional(),
  MaxReplicas: z.number().optional(),
  Platforms: z.array(z.lazy(() => MongoChangeStatusPlatform$inboundSchema))
    .optional(),
  Preferences: z.array(z.lazy(() => MongoChangeStatusPreference$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Constraints": "constraints",
    "MaxReplicas": "maxReplicas",
    "Platforms": "platforms",
    "Preferences": "preferences",
  });
});

export function mongoChangeStatusPlacementSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusPlacementSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusPlacementSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusPlacementSwarm' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusRestartPolicySwarm$inboundSchema: z.ZodType<
  MongoChangeStatusRestartPolicySwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Condition: z.string().optional(),
  Delay: z.number().optional(),
  MaxAttempts: z.number().optional(),
  Window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Condition": "condition",
    "Delay": "delay",
    "MaxAttempts": "maxAttempts",
    "Window": "window",
  });
});

export function mongoChangeStatusRestartPolicySwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusRestartPolicySwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MongoChangeStatusRestartPolicySwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusRestartPolicySwarm' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusRollbackConfigSwarm$inboundSchema: z.ZodType<
  MongoChangeStatusRollbackConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function mongoChangeStatusRollbackConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusRollbackConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MongoChangeStatusRollbackConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusRollbackConfigSwarm' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusMetricsConfigEnum$inboundSchema: z.ZodNativeEnum<
  typeof MongoChangeStatusMetricsConfigEnum
> = z.nativeEnum(MongoChangeStatusMetricsConfigEnum);

/** @internal */
export const MongoChangeStatusMetricsConfigUnion1$inboundSchema: z.ZodType<
  MongoChangeStatusMetricsConfigUnion1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  MongoChangeStatusMetricsConfigEnum$inboundSchema,
]);

export function mongoChangeStatusMetricsConfigUnion1FromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusMetricsConfigUnion1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MongoChangeStatusMetricsConfigUnion1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusMetricsConfigUnion1' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusMetricsConfigUnion2$inboundSchema: z.ZodType<
  MongoChangeStatusMetricsConfigUnion2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    MongoChangeStatusMetricsConfigEnum$inboundSchema,
  ]),
  z.array(z.any()),
  z.record(z.any()),
]);

export function mongoChangeStatusMetricsConfigUnion2FromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusMetricsConfigUnion2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MongoChangeStatusMetricsConfigUnion2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusMetricsConfigUnion2' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusServerStatus$inboundSchema: z.ZodNativeEnum<
  typeof MongoChangeStatusServerStatus
> = z.nativeEnum(MongoChangeStatusServerStatus);

/** @internal */
export const MongoChangeStatusServer$inboundSchema: z.ZodType<
  MongoChangeStatusServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  command: z.string(),
  createdAt: z.string(),
  description: z.nullable(z.string()),
  enableDockerCleanup: z.boolean(),
  ipAddress: z.string(),
  metricsConfig: z.union([
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      MongoChangeStatusMetricsConfigEnum$inboundSchema,
    ]),
    z.array(z.any()),
    z.record(z.any()),
  ]),
  name: z.string(),
  organizationId: z.string(),
  port: z.number(),
  serverId: z.string(),
  serverStatus: MongoChangeStatusServerStatus$inboundSchema,
  sshKeyId: z.nullable(z.string()),
  username: z.string(),
});

export function mongoChangeStatusServerFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusServer' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusUpdateConfigSwarm$inboundSchema: z.ZodType<
  MongoChangeStatusUpdateConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function mongoChangeStatusUpdateConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusUpdateConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MongoChangeStatusUpdateConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusUpdateConfigSwarm' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusResponseBody$inboundSchema: z.ZodType<
  MongoChangeStatusResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  applicationStatus: MongoChangeStatusApplicationStatusResponse$inboundSchema,
  backups: z.array(z.lazy(() => MongoChangeStatusBackup$inboundSchema)),
  command: z.nullable(z.string()),
  cpuLimit: z.nullable(z.string()),
  cpuReservation: z.nullable(z.string()),
  createdAt: z.string(),
  databasePassword: z.string(),
  databaseUser: z.string(),
  description: z.nullable(z.string()),
  dockerImage: z.string(),
  env: z.nullable(z.string()),
  environment: z.lazy(() => MongoChangeStatusEnvironment$inboundSchema),
  environmentId: z.string(),
  externalPort: z.nullable(z.number()),
  healthCheckSwarm: z.nullable(
    z.lazy(() => MongoChangeStatusHealthCheckSwarm$inboundSchema),
  ),
  labelsSwarm: z.nullable(z.record(z.string())),
  memoryLimit: z.nullable(z.string()),
  memoryReservation: z.nullable(z.string()),
  modeSwarm: z.nullable(z.lazy(() => MongoChangeStatusModeSwarm$inboundSchema)),
  mongoId: z.string(),
  mounts: z.array(z.lazy(() => MongoChangeStatusMount$inboundSchema)),
  name: z.string(),
  networkSwarm: z.nullable(
    z.array(z.lazy(() => MongoChangeStatusNetworkSwarm$inboundSchema)),
  ),
  placementSwarm: z.nullable(
    z.lazy(() => MongoChangeStatusPlacementSwarm$inboundSchema),
  ),
  replicaSets: z.nullable(z.boolean()),
  replicas: z.number(),
  restartPolicySwarm: z.nullable(
    z.lazy(() => MongoChangeStatusRestartPolicySwarm$inboundSchema),
  ),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => MongoChangeStatusRollbackConfigSwarm$inboundSchema),
  ),
  server: z.nullable(z.lazy(() => MongoChangeStatusServer$inboundSchema)),
  serverId: z.nullable(z.string()),
  updateConfigSwarm: z.nullable(
    z.lazy(() => MongoChangeStatusUpdateConfigSwarm$inboundSchema),
  ),
});

export function mongoChangeStatusResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusResponseBody' from JSON`,
  );
}

/** @internal */
export const MongoChangeStatusResponse$inboundSchema: z.ZodType<
  MongoChangeStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => MongoChangeStatusResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function mongoChangeStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<MongoChangeStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoChangeStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoChangeStatusResponse' from JSON`,
  );
}
