/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type MongoMoveRequest = {
  mongoId: string;
  targetEnvironmentId: string;
};

export const MongoMoveApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type MongoMoveApplicationStatus = ClosedEnum<
  typeof MongoMoveApplicationStatus
>;

export type MongoMoveHealthCheckSwarm = {
  interval?: number | undefined;
  retries?: number | undefined;
  startPeriod?: number | undefined;
  test?: Array<string> | undefined;
  timeout?: number | undefined;
};

export type MongoMoveGlobal = {};

export type MongoMoveGlobalJob = {};

export type MongoMoveReplicated = {
  replicas?: number | undefined;
};

export type MongoMoveReplicatedJob = {
  maxConcurrent?: number | undefined;
  totalCompletions?: number | undefined;
};

export type MongoMoveModeSwarm = {
  global?: MongoMoveGlobal | undefined;
  globalJob?: MongoMoveGlobalJob | undefined;
  replicated?: MongoMoveReplicated | undefined;
  replicatedJob?: MongoMoveReplicatedJob | undefined;
};

export type MongoMoveDriverOpts = {};

export type MongoMoveNetworkSwarm = {
  aliases?: Array<string> | undefined;
  driverOpts?: MongoMoveDriverOpts | undefined;
  target?: string | undefined;
};

export type MongoMovePlatform = {
  architecture: string;
  os: string;
};

export type MongoMoveSpread = {
  spreadDescriptor: string;
};

export type MongoMovePreference = {
  spread: MongoMoveSpread;
};

export type MongoMovePlacementSwarm = {
  constraints?: Array<string> | undefined;
  maxReplicas?: number | undefined;
  platforms?: Array<MongoMovePlatform> | undefined;
  preferences?: Array<MongoMovePreference> | undefined;
};

export type MongoMoveRestartPolicySwarm = {
  condition?: string | undefined;
  delay?: number | undefined;
  maxAttempts?: number | undefined;
  window?: number | undefined;
};

export type MongoMoveRollbackConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

export type MongoMoveUpdateConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

/**
 * Successful response
 */
export type MongoMoveResponseBody = {
  appName: string;
  applicationStatus: MongoMoveApplicationStatus;
  command: string | null;
  cpuLimit: string | null;
  cpuReservation: string | null;
  createdAt: string;
  databasePassword: string;
  databaseUser: string;
  description: string | null;
  dockerImage: string;
  env: string | null;
  environmentId: string;
  externalPort: number | null;
  healthCheckSwarm: MongoMoveHealthCheckSwarm | null;
  labelsSwarm: { [k: string]: string } | null;
  memoryLimit: string | null;
  memoryReservation: string | null;
  modeSwarm: MongoMoveModeSwarm | null;
  mongoId: string;
  name: string;
  networkSwarm: Array<MongoMoveNetworkSwarm> | null;
  placementSwarm: MongoMovePlacementSwarm | null;
  replicaSets: boolean | null;
  replicas: number;
  restartPolicySwarm: MongoMoveRestartPolicySwarm | null;
  rollbackConfigSwarm: MongoMoveRollbackConfigSwarm | null;
  serverId: string | null;
  updateConfigSwarm: MongoMoveUpdateConfigSwarm | null;
};

export type MongoMoveResponse = MongoMoveResponseBody | models.ErrorT;

/** @internal */
export type MongoMoveRequest$Outbound = {
  mongoId: string;
  targetEnvironmentId: string;
};

/** @internal */
export const MongoMoveRequest$outboundSchema: z.ZodType<
  MongoMoveRequest$Outbound,
  z.ZodTypeDef,
  MongoMoveRequest
> = z.object({
  mongoId: z.string(),
  targetEnvironmentId: z.string(),
});

export function mongoMoveRequestToJSON(
  mongoMoveRequest: MongoMoveRequest,
): string {
  return JSON.stringify(
    MongoMoveRequest$outboundSchema.parse(mongoMoveRequest),
  );
}

/** @internal */
export const MongoMoveApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof MongoMoveApplicationStatus
> = z.nativeEnum(MongoMoveApplicationStatus);

/** @internal */
export const MongoMoveHealthCheckSwarm$inboundSchema: z.ZodType<
  MongoMoveHealthCheckSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Interval: z.number().optional(),
  Retries: z.number().optional(),
  StartPeriod: z.number().optional(),
  Test: z.array(z.string()).optional(),
  Timeout: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Interval": "interval",
    "Retries": "retries",
    "StartPeriod": "startPeriod",
    "Test": "test",
    "Timeout": "timeout",
  });
});

export function mongoMoveHealthCheckSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveHealthCheckSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveHealthCheckSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveHealthCheckSwarm' from JSON`,
  );
}

/** @internal */
export const MongoMoveGlobal$inboundSchema: z.ZodType<
  MongoMoveGlobal,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function mongoMoveGlobalFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveGlobal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveGlobal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveGlobal' from JSON`,
  );
}

/** @internal */
export const MongoMoveGlobalJob$inboundSchema: z.ZodType<
  MongoMoveGlobalJob,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function mongoMoveGlobalJobFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveGlobalJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveGlobalJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveGlobalJob' from JSON`,
  );
}

/** @internal */
export const MongoMoveReplicated$inboundSchema: z.ZodType<
  MongoMoveReplicated,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicas": "replicas",
  });
});

export function mongoMoveReplicatedFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveReplicated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveReplicated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveReplicated' from JSON`,
  );
}

/** @internal */
export const MongoMoveReplicatedJob$inboundSchema: z.ZodType<
  MongoMoveReplicatedJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  MaxConcurrent: z.number().optional(),
  TotalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "MaxConcurrent": "maxConcurrent",
    "TotalCompletions": "totalCompletions",
  });
});

export function mongoMoveReplicatedJobFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveReplicatedJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveReplicatedJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveReplicatedJob' from JSON`,
  );
}

/** @internal */
export const MongoMoveModeSwarm$inboundSchema: z.ZodType<
  MongoMoveModeSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Global: z.lazy(() => MongoMoveGlobal$inboundSchema).optional(),
  GlobalJob: z.lazy(() => MongoMoveGlobalJob$inboundSchema).optional(),
  Replicated: z.lazy(() => MongoMoveReplicated$inboundSchema).optional(),
  ReplicatedJob: z.lazy(() => MongoMoveReplicatedJob$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "Global": "global",
    "GlobalJob": "globalJob",
    "Replicated": "replicated",
    "ReplicatedJob": "replicatedJob",
  });
});

export function mongoMoveModeSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveModeSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveModeSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveModeSwarm' from JSON`,
  );
}

/** @internal */
export const MongoMoveDriverOpts$inboundSchema: z.ZodType<
  MongoMoveDriverOpts,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function mongoMoveDriverOptsFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveDriverOpts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveDriverOpts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveDriverOpts' from JSON`,
  );
}

/** @internal */
export const MongoMoveNetworkSwarm$inboundSchema: z.ZodType<
  MongoMoveNetworkSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Aliases: z.array(z.string()).optional(),
  DriverOpts: z.lazy(() => MongoMoveDriverOpts$inboundSchema).optional(),
  Target: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Aliases": "aliases",
    "DriverOpts": "driverOpts",
    "Target": "target",
  });
});

export function mongoMoveNetworkSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveNetworkSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveNetworkSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveNetworkSwarm' from JSON`,
  );
}

/** @internal */
export const MongoMovePlatform$inboundSchema: z.ZodType<
  MongoMovePlatform,
  z.ZodTypeDef,
  unknown
> = z.object({
  Architecture: z.string(),
  OS: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Architecture": "architecture",
    "OS": "os",
  });
});

export function mongoMovePlatformFromJSON(
  jsonString: string,
): SafeParseResult<MongoMovePlatform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMovePlatform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMovePlatform' from JSON`,
  );
}

/** @internal */
export const MongoMoveSpread$inboundSchema: z.ZodType<
  MongoMoveSpread,
  z.ZodTypeDef,
  unknown
> = z.object({
  SpreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    "SpreadDescriptor": "spreadDescriptor",
  });
});

export function mongoMoveSpreadFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveSpread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveSpread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveSpread' from JSON`,
  );
}

/** @internal */
export const MongoMovePreference$inboundSchema: z.ZodType<
  MongoMovePreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  Spread: z.lazy(() => MongoMoveSpread$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Spread": "spread",
  });
});

export function mongoMovePreferenceFromJSON(
  jsonString: string,
): SafeParseResult<MongoMovePreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMovePreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMovePreference' from JSON`,
  );
}

/** @internal */
export const MongoMovePlacementSwarm$inboundSchema: z.ZodType<
  MongoMovePlacementSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Constraints: z.array(z.string()).optional(),
  MaxReplicas: z.number().optional(),
  Platforms: z.array(z.lazy(() => MongoMovePlatform$inboundSchema)).optional(),
  Preferences: z.array(z.lazy(() => MongoMovePreference$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Constraints": "constraints",
    "MaxReplicas": "maxReplicas",
    "Platforms": "platforms",
    "Preferences": "preferences",
  });
});

export function mongoMovePlacementSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoMovePlacementSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMovePlacementSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMovePlacementSwarm' from JSON`,
  );
}

/** @internal */
export const MongoMoveRestartPolicySwarm$inboundSchema: z.ZodType<
  MongoMoveRestartPolicySwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Condition: z.string().optional(),
  Delay: z.number().optional(),
  MaxAttempts: z.number().optional(),
  Window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Condition": "condition",
    "Delay": "delay",
    "MaxAttempts": "maxAttempts",
    "Window": "window",
  });
});

export function mongoMoveRestartPolicySwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveRestartPolicySwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveRestartPolicySwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveRestartPolicySwarm' from JSON`,
  );
}

/** @internal */
export const MongoMoveRollbackConfigSwarm$inboundSchema: z.ZodType<
  MongoMoveRollbackConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function mongoMoveRollbackConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveRollbackConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveRollbackConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveRollbackConfigSwarm' from JSON`,
  );
}

/** @internal */
export const MongoMoveUpdateConfigSwarm$inboundSchema: z.ZodType<
  MongoMoveUpdateConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function mongoMoveUpdateConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveUpdateConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveUpdateConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveUpdateConfigSwarm' from JSON`,
  );
}

/** @internal */
export const MongoMoveResponseBody$inboundSchema: z.ZodType<
  MongoMoveResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  applicationStatus: MongoMoveApplicationStatus$inboundSchema,
  command: z.nullable(z.string()),
  cpuLimit: z.nullable(z.string()),
  cpuReservation: z.nullable(z.string()),
  createdAt: z.string(),
  databasePassword: z.string(),
  databaseUser: z.string(),
  description: z.nullable(z.string()),
  dockerImage: z.string(),
  env: z.nullable(z.string()),
  environmentId: z.string(),
  externalPort: z.nullable(z.number()),
  healthCheckSwarm: z.nullable(
    z.lazy(() => MongoMoveHealthCheckSwarm$inboundSchema),
  ),
  labelsSwarm: z.nullable(z.record(z.string())),
  memoryLimit: z.nullable(z.string()),
  memoryReservation: z.nullable(z.string()),
  modeSwarm: z.nullable(z.lazy(() => MongoMoveModeSwarm$inboundSchema)),
  mongoId: z.string(),
  name: z.string(),
  networkSwarm: z.nullable(
    z.array(z.lazy(() => MongoMoveNetworkSwarm$inboundSchema)),
  ),
  placementSwarm: z.nullable(
    z.lazy(() => MongoMovePlacementSwarm$inboundSchema),
  ),
  replicaSets: z.nullable(z.boolean()),
  replicas: z.number(),
  restartPolicySwarm: z.nullable(
    z.lazy(() => MongoMoveRestartPolicySwarm$inboundSchema),
  ),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => MongoMoveRollbackConfigSwarm$inboundSchema),
  ),
  serverId: z.nullable(z.string()),
  updateConfigSwarm: z.nullable(
    z.lazy(() => MongoMoveUpdateConfigSwarm$inboundSchema),
  ),
});

export function mongoMoveResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveResponseBody' from JSON`,
  );
}

/** @internal */
export const MongoMoveResponse$inboundSchema: z.ZodType<
  MongoMoveResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => MongoMoveResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function mongoMoveResponseFromJSON(
  jsonString: string,
): SafeParseResult<MongoMoveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoMoveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoMoveResponse' from JSON`,
  );
}
