/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type MongoRemoveRequest = {
  mongoId: string;
};

export const MongoRemoveApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type MongoRemoveApplicationStatus = ClosedEnum<
  typeof MongoRemoveApplicationStatus
>;

export const MongoRemoveBackupType = {
  Database: "database",
  Compose: "compose",
} as const;
export type MongoRemoveBackupType = ClosedEnum<typeof MongoRemoveBackupType>;

export const MongoRemoveDatabaseType = {
  Postgres: "postgres",
  Mariadb: "mariadb",
  Mysql: "mysql",
  Mongo: "mongo",
  WebServer: "web-server",
} as const;
export type MongoRemoveDatabaseType = ClosedEnum<
  typeof MongoRemoveDatabaseType
>;

export const MongoRemoveMetadataEnum = {
  Null: "null",
} as const;
export type MongoRemoveMetadataEnum = ClosedEnum<
  typeof MongoRemoveMetadataEnum
>;

export type MongoRemoveMariadb = {
  databasePassword: string;
  databaseUser: string;
};

export type MongoRemoveMongo = {
  databasePassword: string;
  databaseUser: string;
};

export type MongoRemoveMysql = {
  databaseRootPassword: string;
};

export type MongoRemovePostgres = {
  databaseUser: string;
};

export type MongoRemoveMetadata = {
  mariadb?: MongoRemoveMariadb | undefined;
  mongo?: MongoRemoveMongo | undefined;
  mysql?: MongoRemoveMysql | undefined;
  postgres?: MongoRemovePostgres | undefined;
};

export type MongoRemoveMetadataUnion =
  | MongoRemoveMetadata
  | MongoRemoveMetadataEnum;

export type MongoRemoveBackup = {
  appName: string;
  backupId: string;
  backupType: MongoRemoveBackupType;
  composeId: string | null;
  database: string;
  databaseType: MongoRemoveDatabaseType;
  destinationId: string;
  enabled: boolean | null;
  keepLatestCount: number | null;
  mariadbId: string | null;
  metadata?: MongoRemoveMetadata | MongoRemoveMetadataEnum | null | undefined;
  mongoId: string | null;
  mysqlId: string | null;
  postgresId: string | null;
  prefix: string;
  schedule: string;
  serviceName: string | null;
  userId: string | null;
};

export type MongoRemoveProject = {
  createdAt: string;
  description: string | null;
  env: string;
  name: string;
  organizationId: string;
  projectId: string;
};

export type MongoRemoveEnvironment = {
  createdAt: string;
  description: string | null;
  env: string;
  environmentId: string;
  name: string;
  project: MongoRemoveProject;
  projectId: string;
};

export type MongoRemoveHealthCheckSwarm = {
  interval?: number | undefined;
  retries?: number | undefined;
  startPeriod?: number | undefined;
  test?: Array<string> | undefined;
  timeout?: number | undefined;
};

export type MongoRemoveGlobal = {};

export type MongoRemoveGlobalJob = {};

export type MongoRemoveReplicated = {
  replicas?: number | undefined;
};

export type MongoRemoveReplicatedJob = {
  maxConcurrent?: number | undefined;
  totalCompletions?: number | undefined;
};

export type MongoRemoveModeSwarm = {
  global?: MongoRemoveGlobal | undefined;
  globalJob?: MongoRemoveGlobalJob | undefined;
  replicated?: MongoRemoveReplicated | undefined;
  replicatedJob?: MongoRemoveReplicatedJob | undefined;
};

export const MongoRemoveServiceType = {
  Application: "application",
  Postgres: "postgres",
  Mysql: "mysql",
  Mariadb: "mariadb",
  Mongo: "mongo",
  Redis: "redis",
  Compose: "compose",
} as const;
export type MongoRemoveServiceType = ClosedEnum<typeof MongoRemoveServiceType>;

export const MongoRemoveType = {
  Bind: "bind",
  Volume: "volume",
  File: "file",
} as const;
export type MongoRemoveType = ClosedEnum<typeof MongoRemoveType>;

export type MongoRemoveMount = {
  applicationId: string | null;
  composeId: string | null;
  content: string | null;
  filePath: string | null;
  hostPath: string | null;
  mariadbId: string | null;
  mongoId: string | null;
  mountId: string;
  mountPath: string;
  mysqlId: string | null;
  postgresId: string | null;
  redisId: string | null;
  serviceType: MongoRemoveServiceType;
  type: MongoRemoveType;
  volumeName: string | null;
};

export type MongoRemoveDriverOpts = {};

export type MongoRemoveNetworkSwarm = {
  aliases?: Array<string> | undefined;
  driverOpts?: MongoRemoveDriverOpts | undefined;
  target?: string | undefined;
};

export type MongoRemovePlatform = {
  architecture: string;
  os: string;
};

export type MongoRemoveSpread = {
  spreadDescriptor: string;
};

export type MongoRemovePreference = {
  spread: MongoRemoveSpread;
};

export type MongoRemovePlacementSwarm = {
  constraints?: Array<string> | undefined;
  maxReplicas?: number | undefined;
  platforms?: Array<MongoRemovePlatform> | undefined;
  preferences?: Array<MongoRemovePreference> | undefined;
};

export type MongoRemoveRestartPolicySwarm = {
  condition?: string | undefined;
  delay?: number | undefined;
  maxAttempts?: number | undefined;
  window?: number | undefined;
};

export type MongoRemoveRollbackConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

export const MongoRemoveMetricsConfigEnum = {
  Null: "null",
} as const;
export type MongoRemoveMetricsConfigEnum = ClosedEnum<
  typeof MongoRemoveMetricsConfigEnum
>;

export type MongoRemoveMetricsConfigUnion1 =
  | string
  | number
  | boolean
  | MongoRemoveMetricsConfigEnum;

export type MongoRemoveMetricsConfigUnion2 =
  | string
  | number
  | boolean
  | MongoRemoveMetricsConfigEnum
  | Array<any>
  | { [k: string]: any };

export const MongoRemoveServerStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
export type MongoRemoveServerStatus = ClosedEnum<
  typeof MongoRemoveServerStatus
>;

export type MongoRemoveServer = {
  appName: string;
  command: string;
  createdAt: string;
  description: string | null;
  enableDockerCleanup: boolean;
  ipAddress: string;
  metricsConfig:
    | string
    | number
    | boolean
    | MongoRemoveMetricsConfigEnum
    | Array<any>
    | { [k: string]: any };
  name: string;
  organizationId: string;
  port: number;
  serverId: string;
  serverStatus: MongoRemoveServerStatus;
  sshKeyId: string | null;
  username: string;
};

export type MongoRemoveUpdateConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

/**
 * Successful response
 */
export type MongoRemoveResponseBody = {
  appName: string;
  applicationStatus: MongoRemoveApplicationStatus;
  backups: Array<MongoRemoveBackup>;
  command: string | null;
  cpuLimit: string | null;
  cpuReservation: string | null;
  createdAt: string;
  databasePassword: string;
  databaseUser: string;
  description: string | null;
  dockerImage: string;
  env: string | null;
  environment: MongoRemoveEnvironment;
  environmentId: string;
  externalPort: number | null;
  healthCheckSwarm: MongoRemoveHealthCheckSwarm | null;
  labelsSwarm: { [k: string]: string } | null;
  memoryLimit: string | null;
  memoryReservation: string | null;
  modeSwarm: MongoRemoveModeSwarm | null;
  mongoId: string;
  mounts: Array<MongoRemoveMount>;
  name: string;
  networkSwarm: Array<MongoRemoveNetworkSwarm> | null;
  placementSwarm: MongoRemovePlacementSwarm | null;
  replicaSets: boolean | null;
  replicas: number;
  restartPolicySwarm: MongoRemoveRestartPolicySwarm | null;
  rollbackConfigSwarm: MongoRemoveRollbackConfigSwarm | null;
  server: MongoRemoveServer | null;
  serverId: string | null;
  updateConfigSwarm: MongoRemoveUpdateConfigSwarm | null;
};

export type MongoRemoveResponse = MongoRemoveResponseBody | models.ErrorT;

/** @internal */
export type MongoRemoveRequest$Outbound = {
  mongoId: string;
};

/** @internal */
export const MongoRemoveRequest$outboundSchema: z.ZodType<
  MongoRemoveRequest$Outbound,
  z.ZodTypeDef,
  MongoRemoveRequest
> = z.object({
  mongoId: z.string(),
});

export function mongoRemoveRequestToJSON(
  mongoRemoveRequest: MongoRemoveRequest,
): string {
  return JSON.stringify(
    MongoRemoveRequest$outboundSchema.parse(mongoRemoveRequest),
  );
}

/** @internal */
export const MongoRemoveApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveApplicationStatus
> = z.nativeEnum(MongoRemoveApplicationStatus);

/** @internal */
export const MongoRemoveBackupType$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveBackupType
> = z.nativeEnum(MongoRemoveBackupType);

/** @internal */
export const MongoRemoveDatabaseType$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveDatabaseType
> = z.nativeEnum(MongoRemoveDatabaseType);

/** @internal */
export const MongoRemoveMetadataEnum$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveMetadataEnum
> = z.nativeEnum(MongoRemoveMetadataEnum);

/** @internal */
export const MongoRemoveMariadb$inboundSchema: z.ZodType<
  MongoRemoveMariadb,
  z.ZodTypeDef,
  unknown
> = z.object({
  databasePassword: z.string(),
  databaseUser: z.string(),
});

export function mongoRemoveMariadbFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMariadb, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMariadb$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMariadb' from JSON`,
  );
}

/** @internal */
export const MongoRemoveMongo$inboundSchema: z.ZodType<
  MongoRemoveMongo,
  z.ZodTypeDef,
  unknown
> = z.object({
  databasePassword: z.string(),
  databaseUser: z.string(),
});

export function mongoRemoveMongoFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMongo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMongo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMongo' from JSON`,
  );
}

/** @internal */
export const MongoRemoveMysql$inboundSchema: z.ZodType<
  MongoRemoveMysql,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseRootPassword: z.string(),
});

export function mongoRemoveMysqlFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMysql, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMysql$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMysql' from JSON`,
  );
}

/** @internal */
export const MongoRemovePostgres$inboundSchema: z.ZodType<
  MongoRemovePostgres,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseUser: z.string(),
});

export function mongoRemovePostgresFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemovePostgres, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemovePostgres$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemovePostgres' from JSON`,
  );
}

/** @internal */
export const MongoRemoveMetadata$inboundSchema: z.ZodType<
  MongoRemoveMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  mariadb: z.lazy(() => MongoRemoveMariadb$inboundSchema).optional(),
  mongo: z.lazy(() => MongoRemoveMongo$inboundSchema).optional(),
  mysql: z.lazy(() => MongoRemoveMysql$inboundSchema).optional(),
  postgres: z.lazy(() => MongoRemovePostgres$inboundSchema).optional(),
});

export function mongoRemoveMetadataFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMetadata' from JSON`,
  );
}

/** @internal */
export const MongoRemoveMetadataUnion$inboundSchema: z.ZodType<
  MongoRemoveMetadataUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => MongoRemoveMetadata$inboundSchema),
  MongoRemoveMetadataEnum$inboundSchema,
]);

export function mongoRemoveMetadataUnionFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMetadataUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMetadataUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMetadataUnion' from JSON`,
  );
}

/** @internal */
export const MongoRemoveBackup$inboundSchema: z.ZodType<
  MongoRemoveBackup,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  backupId: z.string(),
  backupType: MongoRemoveBackupType$inboundSchema,
  composeId: z.nullable(z.string()),
  database: z.string(),
  databaseType: MongoRemoveDatabaseType$inboundSchema,
  destinationId: z.string(),
  enabled: z.nullable(z.boolean()),
  keepLatestCount: z.nullable(z.number()),
  mariadbId: z.nullable(z.string()),
  metadata: z.nullable(
    z.union([
      z.lazy(() => MongoRemoveMetadata$inboundSchema),
      MongoRemoveMetadataEnum$inboundSchema,
    ]),
  ).optional(),
  mongoId: z.nullable(z.string()),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  prefix: z.string(),
  schedule: z.string(),
  serviceName: z.nullable(z.string()),
  userId: z.nullable(z.string()),
});

export function mongoRemoveBackupFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveBackup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveBackup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveBackup' from JSON`,
  );
}

/** @internal */
export const MongoRemoveProject$inboundSchema: z.ZodType<
  MongoRemoveProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  name: z.string(),
  organizationId: z.string(),
  projectId: z.string(),
});

export function mongoRemoveProjectFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveProject' from JSON`,
  );
}

/** @internal */
export const MongoRemoveEnvironment$inboundSchema: z.ZodType<
  MongoRemoveEnvironment,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  environmentId: z.string(),
  name: z.string(),
  project: z.lazy(() => MongoRemoveProject$inboundSchema),
  projectId: z.string(),
});

export function mongoRemoveEnvironmentFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveEnvironment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveEnvironment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveEnvironment' from JSON`,
  );
}

/** @internal */
export const MongoRemoveHealthCheckSwarm$inboundSchema: z.ZodType<
  MongoRemoveHealthCheckSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Interval: z.number().optional(),
  Retries: z.number().optional(),
  StartPeriod: z.number().optional(),
  Test: z.array(z.string()).optional(),
  Timeout: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Interval": "interval",
    "Retries": "retries",
    "StartPeriod": "startPeriod",
    "Test": "test",
    "Timeout": "timeout",
  });
});

export function mongoRemoveHealthCheckSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveHealthCheckSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveHealthCheckSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveHealthCheckSwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemoveGlobal$inboundSchema: z.ZodType<
  MongoRemoveGlobal,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function mongoRemoveGlobalFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveGlobal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveGlobal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveGlobal' from JSON`,
  );
}

/** @internal */
export const MongoRemoveGlobalJob$inboundSchema: z.ZodType<
  MongoRemoveGlobalJob,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function mongoRemoveGlobalJobFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveGlobalJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveGlobalJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveGlobalJob' from JSON`,
  );
}

/** @internal */
export const MongoRemoveReplicated$inboundSchema: z.ZodType<
  MongoRemoveReplicated,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicas": "replicas",
  });
});

export function mongoRemoveReplicatedFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveReplicated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveReplicated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveReplicated' from JSON`,
  );
}

/** @internal */
export const MongoRemoveReplicatedJob$inboundSchema: z.ZodType<
  MongoRemoveReplicatedJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  MaxConcurrent: z.number().optional(),
  TotalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "MaxConcurrent": "maxConcurrent",
    "TotalCompletions": "totalCompletions",
  });
});

export function mongoRemoveReplicatedJobFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveReplicatedJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveReplicatedJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveReplicatedJob' from JSON`,
  );
}

/** @internal */
export const MongoRemoveModeSwarm$inboundSchema: z.ZodType<
  MongoRemoveModeSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Global: z.lazy(() => MongoRemoveGlobal$inboundSchema).optional(),
  GlobalJob: z.lazy(() => MongoRemoveGlobalJob$inboundSchema).optional(),
  Replicated: z.lazy(() => MongoRemoveReplicated$inboundSchema).optional(),
  ReplicatedJob: z.lazy(() => MongoRemoveReplicatedJob$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Global": "global",
    "GlobalJob": "globalJob",
    "Replicated": "replicated",
    "ReplicatedJob": "replicatedJob",
  });
});

export function mongoRemoveModeSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveModeSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveModeSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveModeSwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemoveServiceType$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveServiceType
> = z.nativeEnum(MongoRemoveServiceType);

/** @internal */
export const MongoRemoveType$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveType
> = z.nativeEnum(MongoRemoveType);

/** @internal */
export const MongoRemoveMount$inboundSchema: z.ZodType<
  MongoRemoveMount,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.nullable(z.string()),
  composeId: z.nullable(z.string()),
  content: z.nullable(z.string()),
  filePath: z.nullable(z.string()),
  hostPath: z.nullable(z.string()),
  mariadbId: z.nullable(z.string()),
  mongoId: z.nullable(z.string()),
  mountId: z.string(),
  mountPath: z.string(),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  redisId: z.nullable(z.string()),
  serviceType: MongoRemoveServiceType$inboundSchema,
  type: MongoRemoveType$inboundSchema,
  volumeName: z.nullable(z.string()),
});

export function mongoRemoveMountFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMount' from JSON`,
  );
}

/** @internal */
export const MongoRemoveDriverOpts$inboundSchema: z.ZodType<
  MongoRemoveDriverOpts,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function mongoRemoveDriverOptsFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveDriverOpts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveDriverOpts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveDriverOpts' from JSON`,
  );
}

/** @internal */
export const MongoRemoveNetworkSwarm$inboundSchema: z.ZodType<
  MongoRemoveNetworkSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Aliases: z.array(z.string()).optional(),
  DriverOpts: z.lazy(() => MongoRemoveDriverOpts$inboundSchema).optional(),
  Target: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Aliases": "aliases",
    "DriverOpts": "driverOpts",
    "Target": "target",
  });
});

export function mongoRemoveNetworkSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveNetworkSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveNetworkSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveNetworkSwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemovePlatform$inboundSchema: z.ZodType<
  MongoRemovePlatform,
  z.ZodTypeDef,
  unknown
> = z.object({
  Architecture: z.string(),
  OS: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Architecture": "architecture",
    "OS": "os",
  });
});

export function mongoRemovePlatformFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemovePlatform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemovePlatform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemovePlatform' from JSON`,
  );
}

/** @internal */
export const MongoRemoveSpread$inboundSchema: z.ZodType<
  MongoRemoveSpread,
  z.ZodTypeDef,
  unknown
> = z.object({
  SpreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    "SpreadDescriptor": "spreadDescriptor",
  });
});

export function mongoRemoveSpreadFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveSpread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveSpread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveSpread' from JSON`,
  );
}

/** @internal */
export const MongoRemovePreference$inboundSchema: z.ZodType<
  MongoRemovePreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  Spread: z.lazy(() => MongoRemoveSpread$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Spread": "spread",
  });
});

export function mongoRemovePreferenceFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemovePreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemovePreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemovePreference' from JSON`,
  );
}

/** @internal */
export const MongoRemovePlacementSwarm$inboundSchema: z.ZodType<
  MongoRemovePlacementSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Constraints: z.array(z.string()).optional(),
  MaxReplicas: z.number().optional(),
  Platforms: z.array(z.lazy(() => MongoRemovePlatform$inboundSchema))
    .optional(),
  Preferences: z.array(z.lazy(() => MongoRemovePreference$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Constraints": "constraints",
    "MaxReplicas": "maxReplicas",
    "Platforms": "platforms",
    "Preferences": "preferences",
  });
});

export function mongoRemovePlacementSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemovePlacementSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemovePlacementSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemovePlacementSwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemoveRestartPolicySwarm$inboundSchema: z.ZodType<
  MongoRemoveRestartPolicySwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Condition: z.string().optional(),
  Delay: z.number().optional(),
  MaxAttempts: z.number().optional(),
  Window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Condition": "condition",
    "Delay": "delay",
    "MaxAttempts": "maxAttempts",
    "Window": "window",
  });
});

export function mongoRemoveRestartPolicySwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveRestartPolicySwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveRestartPolicySwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveRestartPolicySwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemoveRollbackConfigSwarm$inboundSchema: z.ZodType<
  MongoRemoveRollbackConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function mongoRemoveRollbackConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveRollbackConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveRollbackConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveRollbackConfigSwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemoveMetricsConfigEnum$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveMetricsConfigEnum
> = z.nativeEnum(MongoRemoveMetricsConfigEnum);

/** @internal */
export const MongoRemoveMetricsConfigUnion1$inboundSchema: z.ZodType<
  MongoRemoveMetricsConfigUnion1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  MongoRemoveMetricsConfigEnum$inboundSchema,
]);

export function mongoRemoveMetricsConfigUnion1FromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMetricsConfigUnion1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMetricsConfigUnion1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMetricsConfigUnion1' from JSON`,
  );
}

/** @internal */
export const MongoRemoveMetricsConfigUnion2$inboundSchema: z.ZodType<
  MongoRemoveMetricsConfigUnion2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    MongoRemoveMetricsConfigEnum$inboundSchema,
  ]),
  z.array(z.any()),
  z.record(z.any()),
]);

export function mongoRemoveMetricsConfigUnion2FromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveMetricsConfigUnion2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveMetricsConfigUnion2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveMetricsConfigUnion2' from JSON`,
  );
}

/** @internal */
export const MongoRemoveServerStatus$inboundSchema: z.ZodNativeEnum<
  typeof MongoRemoveServerStatus
> = z.nativeEnum(MongoRemoveServerStatus);

/** @internal */
export const MongoRemoveServer$inboundSchema: z.ZodType<
  MongoRemoveServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  command: z.string(),
  createdAt: z.string(),
  description: z.nullable(z.string()),
  enableDockerCleanup: z.boolean(),
  ipAddress: z.string(),
  metricsConfig: z.union([
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      MongoRemoveMetricsConfigEnum$inboundSchema,
    ]),
    z.array(z.any()),
    z.record(z.any()),
  ]),
  name: z.string(),
  organizationId: z.string(),
  port: z.number(),
  serverId: z.string(),
  serverStatus: MongoRemoveServerStatus$inboundSchema,
  sshKeyId: z.nullable(z.string()),
  username: z.string(),
});

export function mongoRemoveServerFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveServer' from JSON`,
  );
}

/** @internal */
export const MongoRemoveUpdateConfigSwarm$inboundSchema: z.ZodType<
  MongoRemoveUpdateConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function mongoRemoveUpdateConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveUpdateConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveUpdateConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveUpdateConfigSwarm' from JSON`,
  );
}

/** @internal */
export const MongoRemoveResponseBody$inboundSchema: z.ZodType<
  MongoRemoveResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  applicationStatus: MongoRemoveApplicationStatus$inboundSchema,
  backups: z.array(z.lazy(() => MongoRemoveBackup$inboundSchema)),
  command: z.nullable(z.string()),
  cpuLimit: z.nullable(z.string()),
  cpuReservation: z.nullable(z.string()),
  createdAt: z.string(),
  databasePassword: z.string(),
  databaseUser: z.string(),
  description: z.nullable(z.string()),
  dockerImage: z.string(),
  env: z.nullable(z.string()),
  environment: z.lazy(() => MongoRemoveEnvironment$inboundSchema),
  environmentId: z.string(),
  externalPort: z.nullable(z.number()),
  healthCheckSwarm: z.nullable(
    z.lazy(() => MongoRemoveHealthCheckSwarm$inboundSchema),
  ),
  labelsSwarm: z.nullable(z.record(z.string())),
  memoryLimit: z.nullable(z.string()),
  memoryReservation: z.nullable(z.string()),
  modeSwarm: z.nullable(z.lazy(() => MongoRemoveModeSwarm$inboundSchema)),
  mongoId: z.string(),
  mounts: z.array(z.lazy(() => MongoRemoveMount$inboundSchema)),
  name: z.string(),
  networkSwarm: z.nullable(
    z.array(z.lazy(() => MongoRemoveNetworkSwarm$inboundSchema)),
  ),
  placementSwarm: z.nullable(
    z.lazy(() => MongoRemovePlacementSwarm$inboundSchema),
  ),
  replicaSets: z.nullable(z.boolean()),
  replicas: z.number(),
  restartPolicySwarm: z.nullable(
    z.lazy(() => MongoRemoveRestartPolicySwarm$inboundSchema),
  ),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => MongoRemoveRollbackConfigSwarm$inboundSchema),
  ),
  server: z.nullable(z.lazy(() => MongoRemoveServer$inboundSchema)),
  serverId: z.nullable(z.string()),
  updateConfigSwarm: z.nullable(
    z.lazy(() => MongoRemoveUpdateConfigSwarm$inboundSchema),
  ),
});

export function mongoRemoveResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveResponseBody' from JSON`,
  );
}

/** @internal */
export const MongoRemoveResponse$inboundSchema: z.ZodType<
  MongoRemoveResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => MongoRemoveResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function mongoRemoveResponseFromJSON(
  jsonString: string,
): SafeParseResult<MongoRemoveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoRemoveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoRemoveResponse' from JSON`,
  );
}
