/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type MongoSaveExternalPortRequest = {
  externalPort: number | null;
  mongoId: string;
};

export const MongoSaveExternalPortApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type MongoSaveExternalPortApplicationStatus = ClosedEnum<
  typeof MongoSaveExternalPortApplicationStatus
>;

export const MongoSaveExternalPortBackupType = {
  Database: "database",
  Compose: "compose",
} as const;
export type MongoSaveExternalPortBackupType = ClosedEnum<
  typeof MongoSaveExternalPortBackupType
>;

export const MongoSaveExternalPortDatabaseType = {
  Postgres: "postgres",
  Mariadb: "mariadb",
  Mysql: "mysql",
  Mongo: "mongo",
  WebServer: "web-server",
} as const;
export type MongoSaveExternalPortDatabaseType = ClosedEnum<
  typeof MongoSaveExternalPortDatabaseType
>;

export const MongoSaveExternalPortMetadataEnum = {
  Null: "null",
} as const;
export type MongoSaveExternalPortMetadataEnum = ClosedEnum<
  typeof MongoSaveExternalPortMetadataEnum
>;

export type MongoSaveExternalPortMariadb = {
  databasePassword: string;
  databaseUser: string;
};

export type MongoSaveExternalPortMongo = {
  databasePassword: string;
  databaseUser: string;
};

export type MongoSaveExternalPortMysql = {
  databaseRootPassword: string;
};

export type MongoSaveExternalPortPostgres = {
  databaseUser: string;
};

export type MongoSaveExternalPortMetadata = {
  mariadb?: MongoSaveExternalPortMariadb | undefined;
  mongo?: MongoSaveExternalPortMongo | undefined;
  mysql?: MongoSaveExternalPortMysql | undefined;
  postgres?: MongoSaveExternalPortPostgres | undefined;
};

export type MongoSaveExternalPortMetadataUnion =
  | MongoSaveExternalPortMetadata
  | MongoSaveExternalPortMetadataEnum;

export type MongoSaveExternalPortBackup = {
  appName: string;
  backupId: string;
  backupType: MongoSaveExternalPortBackupType;
  composeId: string | null;
  database: string;
  databaseType: MongoSaveExternalPortDatabaseType;
  destinationId: string;
  enabled: boolean | null;
  keepLatestCount: number | null;
  mariadbId: string | null;
  metadata?:
    | MongoSaveExternalPortMetadata
    | MongoSaveExternalPortMetadataEnum
    | null
    | undefined;
  mongoId: string | null;
  mysqlId: string | null;
  postgresId: string | null;
  prefix: string;
  schedule: string;
  serviceName: string | null;
  userId: string | null;
};

export type MongoSaveExternalPortProject = {
  createdAt: string;
  description: string | null;
  env: string;
  name: string;
  organizationId: string;
  projectId: string;
};

export type MongoSaveExternalPortEnvironment = {
  createdAt: string;
  description: string | null;
  env: string;
  environmentId: string;
  name: string;
  project: MongoSaveExternalPortProject;
  projectId: string;
};

export type MongoSaveExternalPortHealthCheckSwarm = {
  interval?: number | undefined;
  retries?: number | undefined;
  startPeriod?: number | undefined;
  test?: Array<string> | undefined;
  timeout?: number | undefined;
};

export type MongoSaveExternalPortGlobal = {};

export type MongoSaveExternalPortGlobalJob = {};

export type MongoSaveExternalPortReplicated = {
  replicas?: number | undefined;
};

export type MongoSaveExternalPortReplicatedJob = {
  maxConcurrent?: number | undefined;
  totalCompletions?: number | undefined;
};

export type MongoSaveExternalPortModeSwarm = {
  global?: MongoSaveExternalPortGlobal | undefined;
  globalJob?: MongoSaveExternalPortGlobalJob | undefined;
  replicated?: MongoSaveExternalPortReplicated | undefined;
  replicatedJob?: MongoSaveExternalPortReplicatedJob | undefined;
};

export const MongoSaveExternalPortServiceType = {
  Application: "application",
  Postgres: "postgres",
  Mysql: "mysql",
  Mariadb: "mariadb",
  Mongo: "mongo",
  Redis: "redis",
  Compose: "compose",
} as const;
export type MongoSaveExternalPortServiceType = ClosedEnum<
  typeof MongoSaveExternalPortServiceType
>;

export const MongoSaveExternalPortType = {
  Bind: "bind",
  Volume: "volume",
  File: "file",
} as const;
export type MongoSaveExternalPortType = ClosedEnum<
  typeof MongoSaveExternalPortType
>;

export type MongoSaveExternalPortMount = {
  applicationId: string | null;
  composeId: string | null;
  content: string | null;
  filePath: string | null;
  hostPath: string | null;
  mariadbId: string | null;
  mongoId: string | null;
  mountId: string;
  mountPath: string;
  mysqlId: string | null;
  postgresId: string | null;
  redisId: string | null;
  serviceType: MongoSaveExternalPortServiceType;
  type: MongoSaveExternalPortType;
  volumeName: string | null;
};

export type MongoSaveExternalPortDriverOpts = {};

export type MongoSaveExternalPortNetworkSwarm = {
  aliases?: Array<string> | undefined;
  driverOpts?: MongoSaveExternalPortDriverOpts | undefined;
  target?: string | undefined;
};

export type MongoSaveExternalPortPlatform = {
  architecture: string;
  os: string;
};

export type MongoSaveExternalPortSpread = {
  spreadDescriptor: string;
};

export type MongoSaveExternalPortPreference = {
  spread: MongoSaveExternalPortSpread;
};

export type MongoSaveExternalPortPlacementSwarm = {
  constraints?: Array<string> | undefined;
  maxReplicas?: number | undefined;
  platforms?: Array<MongoSaveExternalPortPlatform> | undefined;
  preferences?: Array<MongoSaveExternalPortPreference> | undefined;
};

export type MongoSaveExternalPortRestartPolicySwarm = {
  condition?: string | undefined;
  delay?: number | undefined;
  maxAttempts?: number | undefined;
  window?: number | undefined;
};

export type MongoSaveExternalPortRollbackConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

export const MongoSaveExternalPortMetricsConfigEnum = {
  Null: "null",
} as const;
export type MongoSaveExternalPortMetricsConfigEnum = ClosedEnum<
  typeof MongoSaveExternalPortMetricsConfigEnum
>;

export type MongoSaveExternalPortMetricsConfigUnion1 =
  | string
  | number
  | boolean
  | MongoSaveExternalPortMetricsConfigEnum;

export type MongoSaveExternalPortMetricsConfigUnion2 =
  | string
  | number
  | boolean
  | MongoSaveExternalPortMetricsConfigEnum
  | Array<any>
  | { [k: string]: any };

export const MongoSaveExternalPortServerStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
export type MongoSaveExternalPortServerStatus = ClosedEnum<
  typeof MongoSaveExternalPortServerStatus
>;

export type MongoSaveExternalPortServer = {
  appName: string;
  command: string;
  createdAt: string;
  description: string | null;
  enableDockerCleanup: boolean;
  ipAddress: string;
  metricsConfig:
    | string
    | number
    | boolean
    | MongoSaveExternalPortMetricsConfigEnum
    | Array<any>
    | { [k: string]: any };
  name: string;
  organizationId: string;
  port: number;
  serverId: string;
  serverStatus: MongoSaveExternalPortServerStatus;
  sshKeyId: string | null;
  username: string;
};

export type MongoSaveExternalPortUpdateConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

/**
 * Successful response
 */
export type MongoSaveExternalPortResponseBody = {
  appName: string;
  applicationStatus: MongoSaveExternalPortApplicationStatus;
  backups: Array<MongoSaveExternalPortBackup>;
  command: string | null;
  cpuLimit: string | null;
  cpuReservation: string | null;
  createdAt: string;
  databasePassword: string;
  databaseUser: string;
  description: string | null;
  dockerImage: string;
  env: string | null;
  environment: MongoSaveExternalPortEnvironment;
  environmentId: string;
  externalPort: number | null;
  healthCheckSwarm: MongoSaveExternalPortHealthCheckSwarm | null;
  labelsSwarm: { [k: string]: string } | null;
  memoryLimit: string | null;
  memoryReservation: string | null;
  modeSwarm: MongoSaveExternalPortModeSwarm | null;
  mongoId: string;
  mounts: Array<MongoSaveExternalPortMount>;
  name: string;
  networkSwarm: Array<MongoSaveExternalPortNetworkSwarm> | null;
  placementSwarm: MongoSaveExternalPortPlacementSwarm | null;
  replicaSets: boolean | null;
  replicas: number;
  restartPolicySwarm: MongoSaveExternalPortRestartPolicySwarm | null;
  rollbackConfigSwarm: MongoSaveExternalPortRollbackConfigSwarm | null;
  server: MongoSaveExternalPortServer | null;
  serverId: string | null;
  updateConfigSwarm: MongoSaveExternalPortUpdateConfigSwarm | null;
};

export type MongoSaveExternalPortResponse =
  | MongoSaveExternalPortResponseBody
  | models.ErrorT;

/** @internal */
export type MongoSaveExternalPortRequest$Outbound = {
  externalPort: number | null;
  mongoId: string;
};

/** @internal */
export const MongoSaveExternalPortRequest$outboundSchema: z.ZodType<
  MongoSaveExternalPortRequest$Outbound,
  z.ZodTypeDef,
  MongoSaveExternalPortRequest
> = z.object({
  externalPort: z.nullable(z.number()),
  mongoId: z.string(),
});

export function mongoSaveExternalPortRequestToJSON(
  mongoSaveExternalPortRequest: MongoSaveExternalPortRequest,
): string {
  return JSON.stringify(
    MongoSaveExternalPortRequest$outboundSchema.parse(
      mongoSaveExternalPortRequest,
    ),
  );
}

/** @internal */
export const MongoSaveExternalPortApplicationStatus$inboundSchema:
  z.ZodNativeEnum<typeof MongoSaveExternalPortApplicationStatus> = z.nativeEnum(
    MongoSaveExternalPortApplicationStatus,
  );

/** @internal */
export const MongoSaveExternalPortBackupType$inboundSchema: z.ZodNativeEnum<
  typeof MongoSaveExternalPortBackupType
> = z.nativeEnum(MongoSaveExternalPortBackupType);

/** @internal */
export const MongoSaveExternalPortDatabaseType$inboundSchema: z.ZodNativeEnum<
  typeof MongoSaveExternalPortDatabaseType
> = z.nativeEnum(MongoSaveExternalPortDatabaseType);

/** @internal */
export const MongoSaveExternalPortMetadataEnum$inboundSchema: z.ZodNativeEnum<
  typeof MongoSaveExternalPortMetadataEnum
> = z.nativeEnum(MongoSaveExternalPortMetadataEnum);

/** @internal */
export const MongoSaveExternalPortMariadb$inboundSchema: z.ZodType<
  MongoSaveExternalPortMariadb,
  z.ZodTypeDef,
  unknown
> = z.object({
  databasePassword: z.string(),
  databaseUser: z.string(),
});

export function mongoSaveExternalPortMariadbFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortMariadb, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortMariadb$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortMariadb' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortMongo$inboundSchema: z.ZodType<
  MongoSaveExternalPortMongo,
  z.ZodTypeDef,
  unknown
> = z.object({
  databasePassword: z.string(),
  databaseUser: z.string(),
});

export function mongoSaveExternalPortMongoFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortMongo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortMongo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortMongo' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortMysql$inboundSchema: z.ZodType<
  MongoSaveExternalPortMysql,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseRootPassword: z.string(),
});

export function mongoSaveExternalPortMysqlFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortMysql, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortMysql$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortMysql' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortPostgres$inboundSchema: z.ZodType<
  MongoSaveExternalPortPostgres,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseUser: z.string(),
});

export function mongoSaveExternalPortPostgresFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortPostgres, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortPostgres$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortPostgres' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortMetadata$inboundSchema: z.ZodType<
  MongoSaveExternalPortMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  mariadb: z.lazy(() => MongoSaveExternalPortMariadb$inboundSchema).optional(),
  mongo: z.lazy(() => MongoSaveExternalPortMongo$inboundSchema).optional(),
  mysql: z.lazy(() => MongoSaveExternalPortMysql$inboundSchema).optional(),
  postgres: z.lazy(() => MongoSaveExternalPortPostgres$inboundSchema)
    .optional(),
});

export function mongoSaveExternalPortMetadataFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortMetadata' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortMetadataUnion$inboundSchema: z.ZodType<
  MongoSaveExternalPortMetadataUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => MongoSaveExternalPortMetadata$inboundSchema),
  MongoSaveExternalPortMetadataEnum$inboundSchema,
]);

export function mongoSaveExternalPortMetadataUnionFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortMetadataUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MongoSaveExternalPortMetadataUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortMetadataUnion' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortBackup$inboundSchema: z.ZodType<
  MongoSaveExternalPortBackup,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  backupId: z.string(),
  backupType: MongoSaveExternalPortBackupType$inboundSchema,
  composeId: z.nullable(z.string()),
  database: z.string(),
  databaseType: MongoSaveExternalPortDatabaseType$inboundSchema,
  destinationId: z.string(),
  enabled: z.nullable(z.boolean()),
  keepLatestCount: z.nullable(z.number()),
  mariadbId: z.nullable(z.string()),
  metadata: z.nullable(
    z.union([
      z.lazy(() => MongoSaveExternalPortMetadata$inboundSchema),
      MongoSaveExternalPortMetadataEnum$inboundSchema,
    ]),
  ).optional(),
  mongoId: z.nullable(z.string()),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  prefix: z.string(),
  schedule: z.string(),
  serviceName: z.nullable(z.string()),
  userId: z.nullable(z.string()),
});

export function mongoSaveExternalPortBackupFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortBackup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortBackup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortBackup' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortProject$inboundSchema: z.ZodType<
  MongoSaveExternalPortProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  name: z.string(),
  organizationId: z.string(),
  projectId: z.string(),
});

export function mongoSaveExternalPortProjectFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortProject' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortEnvironment$inboundSchema: z.ZodType<
  MongoSaveExternalPortEnvironment,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  environmentId: z.string(),
  name: z.string(),
  project: z.lazy(() => MongoSaveExternalPortProject$inboundSchema),
  projectId: z.string(),
});

export function mongoSaveExternalPortEnvironmentFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortEnvironment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortEnvironment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortEnvironment' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortHealthCheckSwarm$inboundSchema: z.ZodType<
  MongoSaveExternalPortHealthCheckSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Interval: z.number().optional(),
  Retries: z.number().optional(),
  StartPeriod: z.number().optional(),
  Test: z.array(z.string()).optional(),
  Timeout: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Interval": "interval",
    "Retries": "retries",
    "StartPeriod": "startPeriod",
    "Test": "test",
    "Timeout": "timeout",
  });
});

export function mongoSaveExternalPortHealthCheckSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortHealthCheckSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MongoSaveExternalPortHealthCheckSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortHealthCheckSwarm' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortGlobal$inboundSchema: z.ZodType<
  MongoSaveExternalPortGlobal,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function mongoSaveExternalPortGlobalFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortGlobal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortGlobal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortGlobal' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortGlobalJob$inboundSchema: z.ZodType<
  MongoSaveExternalPortGlobalJob,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function mongoSaveExternalPortGlobalJobFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortGlobalJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortGlobalJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortGlobalJob' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortReplicated$inboundSchema: z.ZodType<
  MongoSaveExternalPortReplicated,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicas": "replicas",
  });
});

export function mongoSaveExternalPortReplicatedFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortReplicated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortReplicated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortReplicated' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortReplicatedJob$inboundSchema: z.ZodType<
  MongoSaveExternalPortReplicatedJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  MaxConcurrent: z.number().optional(),
  TotalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "MaxConcurrent": "maxConcurrent",
    "TotalCompletions": "totalCompletions",
  });
});

export function mongoSaveExternalPortReplicatedJobFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortReplicatedJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MongoSaveExternalPortReplicatedJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortReplicatedJob' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortModeSwarm$inboundSchema: z.ZodType<
  MongoSaveExternalPortModeSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Global: z.lazy(() => MongoSaveExternalPortGlobal$inboundSchema).optional(),
  GlobalJob: z.lazy(() => MongoSaveExternalPortGlobalJob$inboundSchema)
    .optional(),
  Replicated: z.lazy(() => MongoSaveExternalPortReplicated$inboundSchema)
    .optional(),
  ReplicatedJob: z.lazy(() => MongoSaveExternalPortReplicatedJob$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Global": "global",
    "GlobalJob": "globalJob",
    "Replicated": "replicated",
    "ReplicatedJob": "replicatedJob",
  });
});

export function mongoSaveExternalPortModeSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortModeSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortModeSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortModeSwarm' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortServiceType$inboundSchema: z.ZodNativeEnum<
  typeof MongoSaveExternalPortServiceType
> = z.nativeEnum(MongoSaveExternalPortServiceType);

/** @internal */
export const MongoSaveExternalPortType$inboundSchema: z.ZodNativeEnum<
  typeof MongoSaveExternalPortType
> = z.nativeEnum(MongoSaveExternalPortType);

/** @internal */
export const MongoSaveExternalPortMount$inboundSchema: z.ZodType<
  MongoSaveExternalPortMount,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.nullable(z.string()),
  composeId: z.nullable(z.string()),
  content: z.nullable(z.string()),
  filePath: z.nullable(z.string()),
  hostPath: z.nullable(z.string()),
  mariadbId: z.nullable(z.string()),
  mongoId: z.nullable(z.string()),
  mountId: z.string(),
  mountPath: z.string(),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  redisId: z.nullable(z.string()),
  serviceType: MongoSaveExternalPortServiceType$inboundSchema,
  type: MongoSaveExternalPortType$inboundSchema,
  volumeName: z.nullable(z.string()),
});

export function mongoSaveExternalPortMountFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortMount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortMount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortMount' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortDriverOpts$inboundSchema: z.ZodType<
  MongoSaveExternalPortDriverOpts,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function mongoSaveExternalPortDriverOptsFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortDriverOpts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortDriverOpts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortDriverOpts' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortNetworkSwarm$inboundSchema: z.ZodType<
  MongoSaveExternalPortNetworkSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Aliases: z.array(z.string()).optional(),
  DriverOpts: z.lazy(() => MongoSaveExternalPortDriverOpts$inboundSchema)
    .optional(),
  Target: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Aliases": "aliases",
    "DriverOpts": "driverOpts",
    "Target": "target",
  });
});

export function mongoSaveExternalPortNetworkSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortNetworkSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortNetworkSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortNetworkSwarm' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortPlatform$inboundSchema: z.ZodType<
  MongoSaveExternalPortPlatform,
  z.ZodTypeDef,
  unknown
> = z.object({
  Architecture: z.string(),
  OS: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Architecture": "architecture",
    "OS": "os",
  });
});

export function mongoSaveExternalPortPlatformFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortPlatform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortPlatform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortPlatform' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortSpread$inboundSchema: z.ZodType<
  MongoSaveExternalPortSpread,
  z.ZodTypeDef,
  unknown
> = z.object({
  SpreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    "SpreadDescriptor": "spreadDescriptor",
  });
});

export function mongoSaveExternalPortSpreadFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortSpread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortSpread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortSpread' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortPreference$inboundSchema: z.ZodType<
  MongoSaveExternalPortPreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  Spread: z.lazy(() => MongoSaveExternalPortSpread$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Spread": "spread",
  });
});

export function mongoSaveExternalPortPreferenceFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortPreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortPreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortPreference' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortPlacementSwarm$inboundSchema: z.ZodType<
  MongoSaveExternalPortPlacementSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Constraints: z.array(z.string()).optional(),
  MaxReplicas: z.number().optional(),
  Platforms: z.array(z.lazy(() => MongoSaveExternalPortPlatform$inboundSchema))
    .optional(),
  Preferences: z.array(
    z.lazy(() => MongoSaveExternalPortPreference$inboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "Constraints": "constraints",
    "MaxReplicas": "maxReplicas",
    "Platforms": "platforms",
    "Preferences": "preferences",
  });
});

export function mongoSaveExternalPortPlacementSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortPlacementSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MongoSaveExternalPortPlacementSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortPlacementSwarm' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortRestartPolicySwarm$inboundSchema: z.ZodType<
  MongoSaveExternalPortRestartPolicySwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Condition: z.string().optional(),
  Delay: z.number().optional(),
  MaxAttempts: z.number().optional(),
  Window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Condition": "condition",
    "Delay": "delay",
    "MaxAttempts": "maxAttempts",
    "Window": "window",
  });
});

export function mongoSaveExternalPortRestartPolicySwarmFromJSON(
  jsonString: string,
): SafeParseResult<
  MongoSaveExternalPortRestartPolicySwarm,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MongoSaveExternalPortRestartPolicySwarm$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'MongoSaveExternalPortRestartPolicySwarm' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortRollbackConfigSwarm$inboundSchema: z.ZodType<
  MongoSaveExternalPortRollbackConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function mongoSaveExternalPortRollbackConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<
  MongoSaveExternalPortRollbackConfigSwarm,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MongoSaveExternalPortRollbackConfigSwarm$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'MongoSaveExternalPortRollbackConfigSwarm' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortMetricsConfigEnum$inboundSchema:
  z.ZodNativeEnum<typeof MongoSaveExternalPortMetricsConfigEnum> = z.nativeEnum(
    MongoSaveExternalPortMetricsConfigEnum,
  );

/** @internal */
export const MongoSaveExternalPortMetricsConfigUnion1$inboundSchema: z.ZodType<
  MongoSaveExternalPortMetricsConfigUnion1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  MongoSaveExternalPortMetricsConfigEnum$inboundSchema,
]);

export function mongoSaveExternalPortMetricsConfigUnion1FromJSON(
  jsonString: string,
): SafeParseResult<
  MongoSaveExternalPortMetricsConfigUnion1,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MongoSaveExternalPortMetricsConfigUnion1$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'MongoSaveExternalPortMetricsConfigUnion1' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortMetricsConfigUnion2$inboundSchema: z.ZodType<
  MongoSaveExternalPortMetricsConfigUnion2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    MongoSaveExternalPortMetricsConfigEnum$inboundSchema,
  ]),
  z.array(z.any()),
  z.record(z.any()),
]);

export function mongoSaveExternalPortMetricsConfigUnion2FromJSON(
  jsonString: string,
): SafeParseResult<
  MongoSaveExternalPortMetricsConfigUnion2,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MongoSaveExternalPortMetricsConfigUnion2$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'MongoSaveExternalPortMetricsConfigUnion2' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortServerStatus$inboundSchema: z.ZodNativeEnum<
  typeof MongoSaveExternalPortServerStatus
> = z.nativeEnum(MongoSaveExternalPortServerStatus);

/** @internal */
export const MongoSaveExternalPortServer$inboundSchema: z.ZodType<
  MongoSaveExternalPortServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  command: z.string(),
  createdAt: z.string(),
  description: z.nullable(z.string()),
  enableDockerCleanup: z.boolean(),
  ipAddress: z.string(),
  metricsConfig: z.union([
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      MongoSaveExternalPortMetricsConfigEnum$inboundSchema,
    ]),
    z.array(z.any()),
    z.record(z.any()),
  ]),
  name: z.string(),
  organizationId: z.string(),
  port: z.number(),
  serverId: z.string(),
  serverStatus: MongoSaveExternalPortServerStatus$inboundSchema,
  sshKeyId: z.nullable(z.string()),
  username: z.string(),
});

export function mongoSaveExternalPortServerFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortServer' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortUpdateConfigSwarm$inboundSchema: z.ZodType<
  MongoSaveExternalPortUpdateConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function mongoSaveExternalPortUpdateConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortUpdateConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      MongoSaveExternalPortUpdateConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortUpdateConfigSwarm' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortResponseBody$inboundSchema: z.ZodType<
  MongoSaveExternalPortResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  applicationStatus: MongoSaveExternalPortApplicationStatus$inboundSchema,
  backups: z.array(z.lazy(() => MongoSaveExternalPortBackup$inboundSchema)),
  command: z.nullable(z.string()),
  cpuLimit: z.nullable(z.string()),
  cpuReservation: z.nullable(z.string()),
  createdAt: z.string(),
  databasePassword: z.string(),
  databaseUser: z.string(),
  description: z.nullable(z.string()),
  dockerImage: z.string(),
  env: z.nullable(z.string()),
  environment: z.lazy(() => MongoSaveExternalPortEnvironment$inboundSchema),
  environmentId: z.string(),
  externalPort: z.nullable(z.number()),
  healthCheckSwarm: z.nullable(
    z.lazy(() => MongoSaveExternalPortHealthCheckSwarm$inboundSchema),
  ),
  labelsSwarm: z.nullable(z.record(z.string())),
  memoryLimit: z.nullable(z.string()),
  memoryReservation: z.nullable(z.string()),
  modeSwarm: z.nullable(
    z.lazy(() => MongoSaveExternalPortModeSwarm$inboundSchema),
  ),
  mongoId: z.string(),
  mounts: z.array(z.lazy(() => MongoSaveExternalPortMount$inboundSchema)),
  name: z.string(),
  networkSwarm: z.nullable(
    z.array(z.lazy(() => MongoSaveExternalPortNetworkSwarm$inboundSchema)),
  ),
  placementSwarm: z.nullable(
    z.lazy(() => MongoSaveExternalPortPlacementSwarm$inboundSchema),
  ),
  replicaSets: z.nullable(z.boolean()),
  replicas: z.number(),
  restartPolicySwarm: z.nullable(
    z.lazy(() => MongoSaveExternalPortRestartPolicySwarm$inboundSchema),
  ),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => MongoSaveExternalPortRollbackConfigSwarm$inboundSchema),
  ),
  server: z.nullable(z.lazy(() => MongoSaveExternalPortServer$inboundSchema)),
  serverId: z.nullable(z.string()),
  updateConfigSwarm: z.nullable(
    z.lazy(() => MongoSaveExternalPortUpdateConfigSwarm$inboundSchema),
  ),
});

export function mongoSaveExternalPortResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortResponseBody' from JSON`,
  );
}

/** @internal */
export const MongoSaveExternalPortResponse$inboundSchema: z.ZodType<
  MongoSaveExternalPortResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => MongoSaveExternalPortResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function mongoSaveExternalPortResponseFromJSON(
  jsonString: string,
): SafeParseResult<MongoSaveExternalPortResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoSaveExternalPortResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoSaveExternalPortResponse' from JSON`,
  );
}
