/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type MongoReloadRequest = {
  appName: string;
  mongoId: string;
};

export type MongoReloadResponse = models.ErrorT | boolean;

/** @internal */
export type MongoReloadRequest$Outbound = {
  appName: string;
  mongoId: string;
};

/** @internal */
export const MongoReloadRequest$outboundSchema: z.ZodType<
  MongoReloadRequest$Outbound,
  z.ZodTypeDef,
  MongoReloadRequest
> = z.object({
  appName: z.string(),
  mongoId: z.string(),
});

export function mongoReloadRequestToJSON(
  mongoReloadRequest: MongoReloadRequest,
): string {
  return JSON.stringify(
    MongoReloadRequest$outboundSchema.parse(mongoReloadRequest),
  );
}

/** @internal */
export const MongoReloadResponse$inboundSchema: z.ZodType<
  MongoReloadResponse,
  z.ZodTypeDef,
  unknown
> = z.union([models.ErrorT$inboundSchema, z.boolean()]);

export function mongoReloadResponseFromJSON(
  jsonString: string,
): SafeParseResult<MongoReloadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoReloadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoReloadResponse' from JSON`,
  );
}
