/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type MongoCreateRequest = {
  appName: string;
  databasePassword: string;
  databaseUser: string;
  description?: string | null | undefined;
  dockerImage?: string | undefined;
  environmentId: string;
  name: string;
  replicaSets?: boolean | null | undefined;
  serverId?: string | null | undefined;
};

export type MongoCreateResponse = models.ErrorT | boolean;

/** @internal */
export type MongoCreateRequest$Outbound = {
  appName: string;
  databasePassword: string;
  databaseUser: string;
  description?: string | null | undefined;
  dockerImage: string;
  environmentId: string;
  name: string;
  replicaSets: boolean | null;
  serverId?: string | null | undefined;
};

/** @internal */
export const MongoCreateRequest$outboundSchema: z.ZodType<
  MongoCreateRequest$Outbound,
  z.ZodTypeDef,
  MongoCreateRequest
> = z.object({
  appName: z.string(),
  databasePassword: z.string(),
  databaseUser: z.string(),
  description: z.nullable(z.string()).optional(),
  dockerImage: z.string().default("mongo:15"),
  environmentId: z.string(),
  name: z.string(),
  replicaSets: z.nullable(z.boolean().default(false)),
  serverId: z.nullable(z.string()).optional(),
});

export function mongoCreateRequestToJSON(
  mongoCreateRequest: MongoCreateRequest,
): string {
  return JSON.stringify(
    MongoCreateRequest$outboundSchema.parse(mongoCreateRequest),
  );
}

/** @internal */
export const MongoCreateResponse$inboundSchema: z.ZodType<
  MongoCreateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([models.ErrorT$inboundSchema, z.boolean()]);

export function mongoCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<MongoCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MongoCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MongoCreateResponse' from JSON`,
  );
}
