/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type MysqlCreateRequest = {
  appName: string;
  databaseName: string;
  databasePassword: string;
  databaseRootPassword: string;
  databaseUser: string;
  description?: string | null | undefined;
  dockerImage?: string | undefined;
  environmentId: string;
  name: string;
  serverId?: string | null | undefined;
};

export type MysqlCreateResponse = models.ErrorT | boolean;

/** @internal */
export type MysqlCreateRequest$Outbound = {
  appName: string;
  databaseName: string;
  databasePassword: string;
  databaseRootPassword: string;
  databaseUser: string;
  description?: string | null | undefined;
  dockerImage: string;
  environmentId: string;
  name: string;
  serverId?: string | null | undefined;
};

/** @internal */
export const MysqlCreateRequest$outboundSchema: z.ZodType<
  MysqlCreateRequest$Outbound,
  z.ZodTypeDef,
  MysqlCreateRequest
> = z.object({
  appName: z.string(),
  databaseName: z.string(),
  databasePassword: z.string(),
  databaseRootPassword: z.string(),
  databaseUser: z.string(),
  description: z.nullable(z.string()).optional(),
  dockerImage: z.string().default("mysql:8"),
  environmentId: z.string(),
  name: z.string(),
  serverId: z.nullable(z.string()).optional(),
});

export function mysqlCreateRequestToJSON(
  mysqlCreateRequest: MysqlCreateRequest,
): string {
  return JSON.stringify(
    MysqlCreateRequest$outboundSchema.parse(mysqlCreateRequest),
  );
}

/** @internal */
export const MysqlCreateResponse$inboundSchema: z.ZodType<
  MysqlCreateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([models.ErrorT$inboundSchema, z.boolean()]);

export function mysqlCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<MysqlCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MysqlCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MysqlCreateResponse' from JSON`,
  );
}
