/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type NotificationRemoveRequest = {
  notificationId: string;
};

/** @internal */
export type NotificationRemoveRequest$Outbound = {
  notificationId: string;
};

/** @internal */
export const NotificationRemoveRequest$outboundSchema: z.ZodType<
  NotificationRemoveRequest$Outbound,
  z.ZodTypeDef,
  NotificationRemoveRequest
> = z.object({
  notificationId: z.string(),
});

export function notificationRemoveRequestToJSON(
  notificationRemoveRequest: NotificationRemoveRequest,
): string {
  return JSON.stringify(
    NotificationRemoveRequest$outboundSchema.parse(notificationRemoveRequest),
  );
}
