/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const ServerType = {
  Dokploy: "Dokploy",
  Remote: "Remote",
} as const;
export type ServerType = ClosedEnum<typeof ServerType>;

export const NotificationReceiveNotificationType = {
  Memory: "Memory",
  Cpu: "CPU",
} as const;
export type NotificationReceiveNotificationType = ClosedEnum<
  typeof NotificationReceiveNotificationType
>;

export type NotificationReceiveNotificationRequest = {
  message: string;
  serverType?: ServerType | undefined;
  threshold: number;
  timestamp: string;
  token: string;
  type: NotificationReceiveNotificationType;
  value: number;
};

/** @internal */
export const ServerType$outboundSchema: z.ZodNativeEnum<typeof ServerType> = z
  .nativeEnum(ServerType);

/** @internal */
export const NotificationReceiveNotificationType$outboundSchema:
  z.ZodNativeEnum<typeof NotificationReceiveNotificationType> = z.nativeEnum(
    NotificationReceiveNotificationType,
  );

/** @internal */
export type NotificationReceiveNotificationRequest$Outbound = {
  Message: string;
  ServerType: string;
  Threshold: number;
  Timestamp: string;
  Token: string;
  Type: string;
  Value: number;
};

/** @internal */
export const NotificationReceiveNotificationRequest$outboundSchema: z.ZodType<
  NotificationReceiveNotificationRequest$Outbound,
  z.ZodTypeDef,
  NotificationReceiveNotificationRequest
> = z.object({
  message: z.string(),
  serverType: ServerType$outboundSchema.default("Dokploy"),
  threshold: z.number(),
  timestamp: z.string(),
  token: z.string(),
  type: NotificationReceiveNotificationType$outboundSchema,
  value: z.number(),
}).transform((v) => {
  return remap$(v, {
    message: "Message",
    serverType: "ServerType",
    threshold: "Threshold",
    timestamp: "Timestamp",
    token: "Token",
    type: "Type",
    value: "Value",
  });
});

export function notificationReceiveNotificationRequestToJSON(
  notificationReceiveNotificationRequest:
    NotificationReceiveNotificationRequest,
): string {
  return JSON.stringify(
    NotificationReceiveNotificationRequest$outboundSchema.parse(
      notificationReceiveNotificationRequest,
    ),
  );
}
