/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type OrganizationAllResponseBody = {
  createdAt: Date;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  ownerId: string;
  slug: string | null;
};

export type OrganizationAllResponse =
  | models.ErrorT
  | Array<OrganizationAllResponseBody>;

/** @internal */
export const OrganizationAllResponseBody$inboundSchema: z.ZodType<
  OrganizationAllResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  id: z.string(),
  logo: z.nullable(z.string()),
  metadata: z.nullable(z.string()),
  name: z.string(),
  ownerId: z.string(),
  slug: z.nullable(z.string()),
});

export function organizationAllResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationAllResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationAllResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationAllResponseBody' from JSON`,
  );
}

/** @internal */
export const OrganizationAllResponse$inboundSchema: z.ZodType<
  OrganizationAllResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.ErrorT$inboundSchema,
  z.array(z.lazy(() => OrganizationAllResponseBody$inboundSchema)),
]);

export function organizationAllResponseFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationAllResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationAllResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationAllResponse' from JSON`,
  );
}
