/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type OrganizationRemoveInvitationRequest = {
  invitationId: string;
};

/** @internal */
export type OrganizationRemoveInvitationRequest$Outbound = {
  invitationId: string;
};

/** @internal */
export const OrganizationRemoveInvitationRequest$outboundSchema: z.ZodType<
  OrganizationRemoveInvitationRequest$Outbound,
  z.ZodTypeDef,
  OrganizationRemoveInvitationRequest
> = z.object({
  invitationId: z.string(),
});

export function organizationRemoveInvitationRequestToJSON(
  organizationRemoveInvitationRequest: OrganizationRemoveInvitationRequest,
): string {
  return JSON.stringify(
    OrganizationRemoveInvitationRequest$outboundSchema.parse(
      organizationRemoveInvitationRequest,
    ),
  );
}
