/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type OrganizationDeleteRequest = {
  organizationId: string;
};

/**
 * Successful response
 */
export type OrganizationDeleteResponseBody = {
  createdAt: Date;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  ownerId: string;
  slug: string | null;
};

export type OrganizationDeleteResponse =
  | OrganizationDeleteResponseBody
  | models.ErrorT;

/** @internal */
export type OrganizationDeleteRequest$Outbound = {
  organizationId: string;
};

/** @internal */
export const OrganizationDeleteRequest$outboundSchema: z.ZodType<
  OrganizationDeleteRequest$Outbound,
  z.ZodTypeDef,
  OrganizationDeleteRequest
> = z.object({
  organizationId: z.string(),
});

export function organizationDeleteRequestToJSON(
  organizationDeleteRequest: OrganizationDeleteRequest,
): string {
  return JSON.stringify(
    OrganizationDeleteRequest$outboundSchema.parse(organizationDeleteRequest),
  );
}

/** @internal */
export const OrganizationDeleteResponseBody$inboundSchema: z.ZodType<
  OrganizationDeleteResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  id: z.string(),
  logo: z.nullable(z.string()),
  metadata: z.nullable(z.string()),
  name: z.string(),
  ownerId: z.string(),
  slug: z.nullable(z.string()),
});

export function organizationDeleteResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationDeleteResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationDeleteResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationDeleteResponseBody' from JSON`,
  );
}

/** @internal */
export const OrganizationDeleteResponse$inboundSchema: z.ZodType<
  OrganizationDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => OrganizationDeleteResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function organizationDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationDeleteResponse' from JSON`,
  );
}
