/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const PortUpdateProtocolRequest = {
  Tcp: "tcp",
  Udp: "udp",
} as const;
export type PortUpdateProtocolRequest = ClosedEnum<
  typeof PortUpdateProtocolRequest
>;

export const PortUpdatePublishModeRequest = {
  Ingress: "ingress",
  Host: "host",
} as const;
export type PortUpdatePublishModeRequest = ClosedEnum<
  typeof PortUpdatePublishModeRequest
>;

export type PortUpdateRequest = {
  portId: string;
  protocol?: PortUpdateProtocolRequest | undefined;
  publishMode?: PortUpdatePublishModeRequest | undefined;
  publishedPort: number;
  targetPort: number;
};

export const PortUpdateProtocolResponse = {
  Tcp: "tcp",
  Udp: "udp",
} as const;
export type PortUpdateProtocolResponse = ClosedEnum<
  typeof PortUpdateProtocolResponse
>;

export const PortUpdatePublishModeResponse = {
  Ingress: "ingress",
  Host: "host",
} as const;
export type PortUpdatePublishModeResponse = ClosedEnum<
  typeof PortUpdatePublishModeResponse
>;

/**
 * Successful response
 */
export type PortUpdateResponseBody = {
  applicationId: string;
  portId: string;
  protocol: PortUpdateProtocolResponse;
  publishMode: PortUpdatePublishModeResponse;
  publishedPort: number;
  targetPort: number;
};

export type PortUpdateResponse = PortUpdateResponseBody | models.ErrorT;

/** @internal */
export const PortUpdateProtocolRequest$outboundSchema: z.ZodNativeEnum<
  typeof PortUpdateProtocolRequest
> = z.nativeEnum(PortUpdateProtocolRequest);

/** @internal */
export const PortUpdatePublishModeRequest$outboundSchema: z.ZodNativeEnum<
  typeof PortUpdatePublishModeRequest
> = z.nativeEnum(PortUpdatePublishModeRequest);

/** @internal */
export type PortUpdateRequest$Outbound = {
  portId: string;
  protocol: string;
  publishMode: string;
  publishedPort: number;
  targetPort: number;
};

/** @internal */
export const PortUpdateRequest$outboundSchema: z.ZodType<
  PortUpdateRequest$Outbound,
  z.ZodTypeDef,
  PortUpdateRequest
> = z.object({
  portId: z.string(),
  protocol: PortUpdateProtocolRequest$outboundSchema.default("tcp"),
  publishMode: PortUpdatePublishModeRequest$outboundSchema.default("ingress"),
  publishedPort: z.number(),
  targetPort: z.number(),
});

export function portUpdateRequestToJSON(
  portUpdateRequest: PortUpdateRequest,
): string {
  return JSON.stringify(
    PortUpdateRequest$outboundSchema.parse(portUpdateRequest),
  );
}

/** @internal */
export const PortUpdateProtocolResponse$inboundSchema: z.ZodNativeEnum<
  typeof PortUpdateProtocolResponse
> = z.nativeEnum(PortUpdateProtocolResponse);

/** @internal */
export const PortUpdatePublishModeResponse$inboundSchema: z.ZodNativeEnum<
  typeof PortUpdatePublishModeResponse
> = z.nativeEnum(PortUpdatePublishModeResponse);

/** @internal */
export const PortUpdateResponseBody$inboundSchema: z.ZodType<
  PortUpdateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
  portId: z.string(),
  protocol: PortUpdateProtocolResponse$inboundSchema,
  publishMode: PortUpdatePublishModeResponse$inboundSchema,
  publishedPort: z.number(),
  targetPort: z.number(),
});

export function portUpdateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PortUpdateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PortUpdateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PortUpdateResponseBody' from JSON`,
  );
}

/** @internal */
export const PortUpdateResponse$inboundSchema: z.ZodType<
  PortUpdateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PortUpdateResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function portUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<PortUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PortUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PortUpdateResponse' from JSON`,
  );
}
