/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PostgresDeployRequest = {
  postgresId: string;
};

export const PostgresDeployApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type PostgresDeployApplicationStatus = ClosedEnum<
  typeof PostgresDeployApplicationStatus
>;

export const PostgresDeployBackupType = {
  Database: "database",
  Compose: "compose",
} as const;
export type PostgresDeployBackupType = ClosedEnum<
  typeof PostgresDeployBackupType
>;

export const PostgresDeployDatabaseType = {
  Postgres: "postgres",
  Mariadb: "mariadb",
  Mysql: "mysql",
  Mongo: "mongo",
  WebServer: "web-server",
} as const;
export type PostgresDeployDatabaseType = ClosedEnum<
  typeof PostgresDeployDatabaseType
>;

export const PostgresDeployMetadataEnum = {
  Null: "null",
} as const;
export type PostgresDeployMetadataEnum = ClosedEnum<
  typeof PostgresDeployMetadataEnum
>;

export type PostgresDeployMariadb = {
  databasePassword: string;
  databaseUser: string;
};

export type PostgresDeployMongo = {
  databasePassword: string;
  databaseUser: string;
};

export type PostgresDeployMysql = {
  databaseRootPassword: string;
};

export type PostgresDeployPostgres = {
  databaseUser: string;
};

export type PostgresDeployMetadata = {
  mariadb?: PostgresDeployMariadb | undefined;
  mongo?: PostgresDeployMongo | undefined;
  mysql?: PostgresDeployMysql | undefined;
  postgres?: PostgresDeployPostgres | undefined;
};

export type PostgresDeployMetadataUnion =
  | PostgresDeployMetadata
  | PostgresDeployMetadataEnum;

export type PostgresDeployBackup = {
  appName: string;
  backupId: string;
  backupType: PostgresDeployBackupType;
  composeId: string | null;
  database: string;
  databaseType: PostgresDeployDatabaseType;
  destinationId: string;
  enabled: boolean | null;
  keepLatestCount: number | null;
  mariadbId: string | null;
  metadata?:
    | PostgresDeployMetadata
    | PostgresDeployMetadataEnum
    | null
    | undefined;
  mongoId: string | null;
  mysqlId: string | null;
  postgresId: string | null;
  prefix: string;
  schedule: string;
  serviceName: string | null;
  userId: string | null;
};

export type PostgresDeployProject = {
  createdAt: string;
  description: string | null;
  env: string;
  name: string;
  organizationId: string;
  projectId: string;
};

export type PostgresDeployEnvironment = {
  createdAt: string;
  description: string | null;
  env: string;
  environmentId: string;
  name: string;
  project: PostgresDeployProject;
  projectId: string;
};

export type PostgresDeployHealthCheckSwarm = {
  interval?: number | undefined;
  retries?: number | undefined;
  startPeriod?: number | undefined;
  test?: Array<string> | undefined;
  timeout?: number | undefined;
};

export type PostgresDeployGlobal = {};

export type PostgresDeployGlobalJob = {};

export type PostgresDeployReplicated = {
  replicas?: number | undefined;
};

export type PostgresDeployReplicatedJob = {
  maxConcurrent?: number | undefined;
  totalCompletions?: number | undefined;
};

export type PostgresDeployModeSwarm = {
  global?: PostgresDeployGlobal | undefined;
  globalJob?: PostgresDeployGlobalJob | undefined;
  replicated?: PostgresDeployReplicated | undefined;
  replicatedJob?: PostgresDeployReplicatedJob | undefined;
};

export const PostgresDeployServiceType = {
  Application: "application",
  Postgres: "postgres",
  Mysql: "mysql",
  Mariadb: "mariadb",
  Mongo: "mongo",
  Redis: "redis",
  Compose: "compose",
} as const;
export type PostgresDeployServiceType = ClosedEnum<
  typeof PostgresDeployServiceType
>;

export const PostgresDeployType = {
  Bind: "bind",
  Volume: "volume",
  File: "file",
} as const;
export type PostgresDeployType = ClosedEnum<typeof PostgresDeployType>;

export type PostgresDeployMount = {
  applicationId: string | null;
  composeId: string | null;
  content: string | null;
  filePath: string | null;
  hostPath: string | null;
  mariadbId: string | null;
  mongoId: string | null;
  mountId: string;
  mountPath: string;
  mysqlId: string | null;
  postgresId: string | null;
  redisId: string | null;
  serviceType: PostgresDeployServiceType;
  type: PostgresDeployType;
  volumeName: string | null;
};

export type PostgresDeployDriverOpts = {};

export type PostgresDeployNetworkSwarm = {
  aliases?: Array<string> | undefined;
  driverOpts?: PostgresDeployDriverOpts | undefined;
  target?: string | undefined;
};

export type PostgresDeployPlatform = {
  architecture: string;
  os: string;
};

export type PostgresDeploySpread = {
  spreadDescriptor: string;
};

export type PostgresDeployPreference = {
  spread: PostgresDeploySpread;
};

export type PostgresDeployPlacementSwarm = {
  constraints?: Array<string> | undefined;
  maxReplicas?: number | undefined;
  platforms?: Array<PostgresDeployPlatform> | undefined;
  preferences?: Array<PostgresDeployPreference> | undefined;
};

export type PostgresDeployRestartPolicySwarm = {
  condition?: string | undefined;
  delay?: number | undefined;
  maxAttempts?: number | undefined;
  window?: number | undefined;
};

export type PostgresDeployRollbackConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

export const PostgresDeployMetricsConfigEnum = {
  Null: "null",
} as const;
export type PostgresDeployMetricsConfigEnum = ClosedEnum<
  typeof PostgresDeployMetricsConfigEnum
>;

export type PostgresDeployMetricsConfigUnion1 =
  | string
  | number
  | boolean
  | PostgresDeployMetricsConfigEnum;

export type PostgresDeployMetricsConfigUnion2 =
  | string
  | number
  | boolean
  | PostgresDeployMetricsConfigEnum
  | Array<any>
  | { [k: string]: any };

export const PostgresDeployServerStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
export type PostgresDeployServerStatus = ClosedEnum<
  typeof PostgresDeployServerStatus
>;

export type PostgresDeployServer = {
  appName: string;
  command: string;
  createdAt: string;
  description: string | null;
  enableDockerCleanup: boolean;
  ipAddress: string;
  metricsConfig:
    | string
    | number
    | boolean
    | PostgresDeployMetricsConfigEnum
    | Array<any>
    | { [k: string]: any };
  name: string;
  organizationId: string;
  port: number;
  serverId: string;
  serverStatus: PostgresDeployServerStatus;
  sshKeyId: string | null;
  username: string;
};

export type PostgresDeployUpdateConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

/**
 * Successful response
 */
export type PostgresDeployResponseBody = {
  appName: string;
  applicationStatus: PostgresDeployApplicationStatus;
  backups: Array<PostgresDeployBackup>;
  command: string | null;
  cpuLimit: string | null;
  cpuReservation: string | null;
  createdAt: string;
  databaseName: string;
  databasePassword: string;
  databaseUser: string;
  description: string | null;
  dockerImage: string;
  env: string | null;
  environment: PostgresDeployEnvironment;
  environmentId: string;
  externalPort: number | null;
  healthCheckSwarm: PostgresDeployHealthCheckSwarm | null;
  labelsSwarm: { [k: string]: string } | null;
  memoryLimit: string | null;
  memoryReservation: string | null;
  modeSwarm: PostgresDeployModeSwarm | null;
  mounts: Array<PostgresDeployMount>;
  name: string;
  networkSwarm: Array<PostgresDeployNetworkSwarm> | null;
  placementSwarm: PostgresDeployPlacementSwarm | null;
  postgresId: string;
  replicas: number;
  restartPolicySwarm: PostgresDeployRestartPolicySwarm | null;
  rollbackConfigSwarm: PostgresDeployRollbackConfigSwarm | null;
  server: PostgresDeployServer | null;
  serverId: string | null;
  updateConfigSwarm: PostgresDeployUpdateConfigSwarm | null;
};

export type PostgresDeployResponse = PostgresDeployResponseBody | models.ErrorT;

/** @internal */
export type PostgresDeployRequest$Outbound = {
  postgresId: string;
};

/** @internal */
export const PostgresDeployRequest$outboundSchema: z.ZodType<
  PostgresDeployRequest$Outbound,
  z.ZodTypeDef,
  PostgresDeployRequest
> = z.object({
  postgresId: z.string(),
});

export function postgresDeployRequestToJSON(
  postgresDeployRequest: PostgresDeployRequest,
): string {
  return JSON.stringify(
    PostgresDeployRequest$outboundSchema.parse(postgresDeployRequest),
  );
}

/** @internal */
export const PostgresDeployApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof PostgresDeployApplicationStatus
> = z.nativeEnum(PostgresDeployApplicationStatus);

/** @internal */
export const PostgresDeployBackupType$inboundSchema: z.ZodNativeEnum<
  typeof PostgresDeployBackupType
> = z.nativeEnum(PostgresDeployBackupType);

/** @internal */
export const PostgresDeployDatabaseType$inboundSchema: z.ZodNativeEnum<
  typeof PostgresDeployDatabaseType
> = z.nativeEnum(PostgresDeployDatabaseType);

/** @internal */
export const PostgresDeployMetadataEnum$inboundSchema: z.ZodNativeEnum<
  typeof PostgresDeployMetadataEnum
> = z.nativeEnum(PostgresDeployMetadataEnum);

/** @internal */
export const PostgresDeployMariadb$inboundSchema: z.ZodType<
  PostgresDeployMariadb,
  z.ZodTypeDef,
  unknown
> = z.object({
  databasePassword: z.string(),
  databaseUser: z.string(),
});

export function postgresDeployMariadbFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployMariadb, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployMariadb$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployMariadb' from JSON`,
  );
}

/** @internal */
export const PostgresDeployMongo$inboundSchema: z.ZodType<
  PostgresDeployMongo,
  z.ZodTypeDef,
  unknown
> = z.object({
  databasePassword: z.string(),
  databaseUser: z.string(),
});

export function postgresDeployMongoFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployMongo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployMongo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployMongo' from JSON`,
  );
}

/** @internal */
export const PostgresDeployMysql$inboundSchema: z.ZodType<
  PostgresDeployMysql,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseRootPassword: z.string(),
});

export function postgresDeployMysqlFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployMysql, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployMysql$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployMysql' from JSON`,
  );
}

/** @internal */
export const PostgresDeployPostgres$inboundSchema: z.ZodType<
  PostgresDeployPostgres,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseUser: z.string(),
});

export function postgresDeployPostgresFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployPostgres, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployPostgres$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployPostgres' from JSON`,
  );
}

/** @internal */
export const PostgresDeployMetadata$inboundSchema: z.ZodType<
  PostgresDeployMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  mariadb: z.lazy(() => PostgresDeployMariadb$inboundSchema).optional(),
  mongo: z.lazy(() => PostgresDeployMongo$inboundSchema).optional(),
  mysql: z.lazy(() => PostgresDeployMysql$inboundSchema).optional(),
  postgres: z.lazy(() => PostgresDeployPostgres$inboundSchema).optional(),
});

export function postgresDeployMetadataFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployMetadata' from JSON`,
  );
}

/** @internal */
export const PostgresDeployMetadataUnion$inboundSchema: z.ZodType<
  PostgresDeployMetadataUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostgresDeployMetadata$inboundSchema),
  PostgresDeployMetadataEnum$inboundSchema,
]);

export function postgresDeployMetadataUnionFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployMetadataUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployMetadataUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployMetadataUnion' from JSON`,
  );
}

/** @internal */
export const PostgresDeployBackup$inboundSchema: z.ZodType<
  PostgresDeployBackup,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  backupId: z.string(),
  backupType: PostgresDeployBackupType$inboundSchema,
  composeId: z.nullable(z.string()),
  database: z.string(),
  databaseType: PostgresDeployDatabaseType$inboundSchema,
  destinationId: z.string(),
  enabled: z.nullable(z.boolean()),
  keepLatestCount: z.nullable(z.number()),
  mariadbId: z.nullable(z.string()),
  metadata: z.nullable(
    z.union([
      z.lazy(() => PostgresDeployMetadata$inboundSchema),
      PostgresDeployMetadataEnum$inboundSchema,
    ]),
  ).optional(),
  mongoId: z.nullable(z.string()),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  prefix: z.string(),
  schedule: z.string(),
  serviceName: z.nullable(z.string()),
  userId: z.nullable(z.string()),
});

export function postgresDeployBackupFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployBackup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployBackup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployBackup' from JSON`,
  );
}

/** @internal */
export const PostgresDeployProject$inboundSchema: z.ZodType<
  PostgresDeployProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  name: z.string(),
  organizationId: z.string(),
  projectId: z.string(),
});

export function postgresDeployProjectFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployProject' from JSON`,
  );
}

/** @internal */
export const PostgresDeployEnvironment$inboundSchema: z.ZodType<
  PostgresDeployEnvironment,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  environmentId: z.string(),
  name: z.string(),
  project: z.lazy(() => PostgresDeployProject$inboundSchema),
  projectId: z.string(),
});

export function postgresDeployEnvironmentFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployEnvironment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployEnvironment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployEnvironment' from JSON`,
  );
}

/** @internal */
export const PostgresDeployHealthCheckSwarm$inboundSchema: z.ZodType<
  PostgresDeployHealthCheckSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Interval: z.number().optional(),
  Retries: z.number().optional(),
  StartPeriod: z.number().optional(),
  Test: z.array(z.string()).optional(),
  Timeout: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Interval": "interval",
    "Retries": "retries",
    "StartPeriod": "startPeriod",
    "Test": "test",
    "Timeout": "timeout",
  });
});

export function postgresDeployHealthCheckSwarmFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployHealthCheckSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployHealthCheckSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployHealthCheckSwarm' from JSON`,
  );
}

/** @internal */
export const PostgresDeployGlobal$inboundSchema: z.ZodType<
  PostgresDeployGlobal,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function postgresDeployGlobalFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployGlobal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployGlobal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployGlobal' from JSON`,
  );
}

/** @internal */
export const PostgresDeployGlobalJob$inboundSchema: z.ZodType<
  PostgresDeployGlobalJob,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function postgresDeployGlobalJobFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployGlobalJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployGlobalJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployGlobalJob' from JSON`,
  );
}

/** @internal */
export const PostgresDeployReplicated$inboundSchema: z.ZodType<
  PostgresDeployReplicated,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicas": "replicas",
  });
});

export function postgresDeployReplicatedFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployReplicated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployReplicated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployReplicated' from JSON`,
  );
}

/** @internal */
export const PostgresDeployReplicatedJob$inboundSchema: z.ZodType<
  PostgresDeployReplicatedJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  MaxConcurrent: z.number().optional(),
  TotalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "MaxConcurrent": "maxConcurrent",
    "TotalCompletions": "totalCompletions",
  });
});

export function postgresDeployReplicatedJobFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployReplicatedJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployReplicatedJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployReplicatedJob' from JSON`,
  );
}

/** @internal */
export const PostgresDeployModeSwarm$inboundSchema: z.ZodType<
  PostgresDeployModeSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Global: z.lazy(() => PostgresDeployGlobal$inboundSchema).optional(),
  GlobalJob: z.lazy(() => PostgresDeployGlobalJob$inboundSchema).optional(),
  Replicated: z.lazy(() => PostgresDeployReplicated$inboundSchema).optional(),
  ReplicatedJob: z.lazy(() => PostgresDeployReplicatedJob$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Global": "global",
    "GlobalJob": "globalJob",
    "Replicated": "replicated",
    "ReplicatedJob": "replicatedJob",
  });
});

export function postgresDeployModeSwarmFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployModeSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployModeSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployModeSwarm' from JSON`,
  );
}

/** @internal */
export const PostgresDeployServiceType$inboundSchema: z.ZodNativeEnum<
  typeof PostgresDeployServiceType
> = z.nativeEnum(PostgresDeployServiceType);

/** @internal */
export const PostgresDeployType$inboundSchema: z.ZodNativeEnum<
  typeof PostgresDeployType
> = z.nativeEnum(PostgresDeployType);

/** @internal */
export const PostgresDeployMount$inboundSchema: z.ZodType<
  PostgresDeployMount,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.nullable(z.string()),
  composeId: z.nullable(z.string()),
  content: z.nullable(z.string()),
  filePath: z.nullable(z.string()),
  hostPath: z.nullable(z.string()),
  mariadbId: z.nullable(z.string()),
  mongoId: z.nullable(z.string()),
  mountId: z.string(),
  mountPath: z.string(),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  redisId: z.nullable(z.string()),
  serviceType: PostgresDeployServiceType$inboundSchema,
  type: PostgresDeployType$inboundSchema,
  volumeName: z.nullable(z.string()),
});

export function postgresDeployMountFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployMount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployMount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployMount' from JSON`,
  );
}

/** @internal */
export const PostgresDeployDriverOpts$inboundSchema: z.ZodType<
  PostgresDeployDriverOpts,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function postgresDeployDriverOptsFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployDriverOpts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployDriverOpts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployDriverOpts' from JSON`,
  );
}

/** @internal */
export const PostgresDeployNetworkSwarm$inboundSchema: z.ZodType<
  PostgresDeployNetworkSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Aliases: z.array(z.string()).optional(),
  DriverOpts: z.lazy(() => PostgresDeployDriverOpts$inboundSchema).optional(),
  Target: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Aliases": "aliases",
    "DriverOpts": "driverOpts",
    "Target": "target",
  });
});

export function postgresDeployNetworkSwarmFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployNetworkSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployNetworkSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployNetworkSwarm' from JSON`,
  );
}

/** @internal */
export const PostgresDeployPlatform$inboundSchema: z.ZodType<
  PostgresDeployPlatform,
  z.ZodTypeDef,
  unknown
> = z.object({
  Architecture: z.string(),
  OS: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Architecture": "architecture",
    "OS": "os",
  });
});

export function postgresDeployPlatformFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployPlatform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployPlatform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployPlatform' from JSON`,
  );
}

/** @internal */
export const PostgresDeploySpread$inboundSchema: z.ZodType<
  PostgresDeploySpread,
  z.ZodTypeDef,
  unknown
> = z.object({
  SpreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    "SpreadDescriptor": "spreadDescriptor",
  });
});

export function postgresDeploySpreadFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeploySpread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeploySpread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeploySpread' from JSON`,
  );
}

/** @internal */
export const PostgresDeployPreference$inboundSchema: z.ZodType<
  PostgresDeployPreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  Spread: z.lazy(() => PostgresDeploySpread$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Spread": "spread",
  });
});

export function postgresDeployPreferenceFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployPreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployPreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployPreference' from JSON`,
  );
}

/** @internal */
export const PostgresDeployPlacementSwarm$inboundSchema: z.ZodType<
  PostgresDeployPlacementSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Constraints: z.array(z.string()).optional(),
  MaxReplicas: z.number().optional(),
  Platforms: z.array(z.lazy(() => PostgresDeployPlatform$inboundSchema))
    .optional(),
  Preferences: z.array(z.lazy(() => PostgresDeployPreference$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Constraints": "constraints",
    "MaxReplicas": "maxReplicas",
    "Platforms": "platforms",
    "Preferences": "preferences",
  });
});

export function postgresDeployPlacementSwarmFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployPlacementSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployPlacementSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployPlacementSwarm' from JSON`,
  );
}

/** @internal */
export const PostgresDeployRestartPolicySwarm$inboundSchema: z.ZodType<
  PostgresDeployRestartPolicySwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Condition: z.string().optional(),
  Delay: z.number().optional(),
  MaxAttempts: z.number().optional(),
  Window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Condition": "condition",
    "Delay": "delay",
    "MaxAttempts": "maxAttempts",
    "Window": "window",
  });
});

export function postgresDeployRestartPolicySwarmFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployRestartPolicySwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployRestartPolicySwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployRestartPolicySwarm' from JSON`,
  );
}

/** @internal */
export const PostgresDeployRollbackConfigSwarm$inboundSchema: z.ZodType<
  PostgresDeployRollbackConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function postgresDeployRollbackConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployRollbackConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployRollbackConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployRollbackConfigSwarm' from JSON`,
  );
}

/** @internal */
export const PostgresDeployMetricsConfigEnum$inboundSchema: z.ZodNativeEnum<
  typeof PostgresDeployMetricsConfigEnum
> = z.nativeEnum(PostgresDeployMetricsConfigEnum);

/** @internal */
export const PostgresDeployMetricsConfigUnion1$inboundSchema: z.ZodType<
  PostgresDeployMetricsConfigUnion1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  PostgresDeployMetricsConfigEnum$inboundSchema,
]);

export function postgresDeployMetricsConfigUnion1FromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployMetricsConfigUnion1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployMetricsConfigUnion1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployMetricsConfigUnion1' from JSON`,
  );
}

/** @internal */
export const PostgresDeployMetricsConfigUnion2$inboundSchema: z.ZodType<
  PostgresDeployMetricsConfigUnion2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    PostgresDeployMetricsConfigEnum$inboundSchema,
  ]),
  z.array(z.any()),
  z.record(z.any()),
]);

export function postgresDeployMetricsConfigUnion2FromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployMetricsConfigUnion2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployMetricsConfigUnion2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployMetricsConfigUnion2' from JSON`,
  );
}

/** @internal */
export const PostgresDeployServerStatus$inboundSchema: z.ZodNativeEnum<
  typeof PostgresDeployServerStatus
> = z.nativeEnum(PostgresDeployServerStatus);

/** @internal */
export const PostgresDeployServer$inboundSchema: z.ZodType<
  PostgresDeployServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  command: z.string(),
  createdAt: z.string(),
  description: z.nullable(z.string()),
  enableDockerCleanup: z.boolean(),
  ipAddress: z.string(),
  metricsConfig: z.union([
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      PostgresDeployMetricsConfigEnum$inboundSchema,
    ]),
    z.array(z.any()),
    z.record(z.any()),
  ]),
  name: z.string(),
  organizationId: z.string(),
  port: z.number(),
  serverId: z.string(),
  serverStatus: PostgresDeployServerStatus$inboundSchema,
  sshKeyId: z.nullable(z.string()),
  username: z.string(),
});

export function postgresDeployServerFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployServer' from JSON`,
  );
}

/** @internal */
export const PostgresDeployUpdateConfigSwarm$inboundSchema: z.ZodType<
  PostgresDeployUpdateConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function postgresDeployUpdateConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployUpdateConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployUpdateConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployUpdateConfigSwarm' from JSON`,
  );
}

/** @internal */
export const PostgresDeployResponseBody$inboundSchema: z.ZodType<
  PostgresDeployResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  applicationStatus: PostgresDeployApplicationStatus$inboundSchema,
  backups: z.array(z.lazy(() => PostgresDeployBackup$inboundSchema)),
  command: z.nullable(z.string()),
  cpuLimit: z.nullable(z.string()),
  cpuReservation: z.nullable(z.string()),
  createdAt: z.string(),
  databaseName: z.string(),
  databasePassword: z.string(),
  databaseUser: z.string(),
  description: z.nullable(z.string()),
  dockerImage: z.string(),
  env: z.nullable(z.string()),
  environment: z.lazy(() => PostgresDeployEnvironment$inboundSchema),
  environmentId: z.string(),
  externalPort: z.nullable(z.number()),
  healthCheckSwarm: z.nullable(
    z.lazy(() => PostgresDeployHealthCheckSwarm$inboundSchema),
  ),
  labelsSwarm: z.nullable(z.record(z.string())),
  memoryLimit: z.nullable(z.string()),
  memoryReservation: z.nullable(z.string()),
  modeSwarm: z.nullable(z.lazy(() => PostgresDeployModeSwarm$inboundSchema)),
  mounts: z.array(z.lazy(() => PostgresDeployMount$inboundSchema)),
  name: z.string(),
  networkSwarm: z.nullable(
    z.array(z.lazy(() => PostgresDeployNetworkSwarm$inboundSchema)),
  ),
  placementSwarm: z.nullable(
    z.lazy(() => PostgresDeployPlacementSwarm$inboundSchema),
  ),
  postgresId: z.string(),
  replicas: z.number(),
  restartPolicySwarm: z.nullable(
    z.lazy(() => PostgresDeployRestartPolicySwarm$inboundSchema),
  ),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => PostgresDeployRollbackConfigSwarm$inboundSchema),
  ),
  server: z.nullable(z.lazy(() => PostgresDeployServer$inboundSchema)),
  serverId: z.nullable(z.string()),
  updateConfigSwarm: z.nullable(
    z.lazy(() => PostgresDeployUpdateConfigSwarm$inboundSchema),
  ),
});

export function postgresDeployResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployResponseBody' from JSON`,
  );
}

/** @internal */
export const PostgresDeployResponse$inboundSchema: z.ZodType<
  PostgresDeployResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostgresDeployResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function postgresDeployResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostgresDeployResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresDeployResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresDeployResponse' from JSON`,
  );
}
