/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const PostgresChangeStatusApplicationStatusRequest = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type PostgresChangeStatusApplicationStatusRequest = ClosedEnum<
  typeof PostgresChangeStatusApplicationStatusRequest
>;

export type PostgresChangeStatusRequest = {
  applicationStatus: PostgresChangeStatusApplicationStatusRequest;
  postgresId: string;
};

export const PostgresChangeStatusApplicationStatusResponse = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type PostgresChangeStatusApplicationStatusResponse = ClosedEnum<
  typeof PostgresChangeStatusApplicationStatusResponse
>;

export const PostgresChangeStatusBackupType = {
  Database: "database",
  Compose: "compose",
} as const;
export type PostgresChangeStatusBackupType = ClosedEnum<
  typeof PostgresChangeStatusBackupType
>;

export const PostgresChangeStatusDatabaseType = {
  Postgres: "postgres",
  Mariadb: "mariadb",
  Mysql: "mysql",
  Mongo: "mongo",
  WebServer: "web-server",
} as const;
export type PostgresChangeStatusDatabaseType = ClosedEnum<
  typeof PostgresChangeStatusDatabaseType
>;

export const PostgresChangeStatusMetadataEnum = {
  Null: "null",
} as const;
export type PostgresChangeStatusMetadataEnum = ClosedEnum<
  typeof PostgresChangeStatusMetadataEnum
>;

export type PostgresChangeStatusMariadb = {
  databasePassword: string;
  databaseUser: string;
};

export type PostgresChangeStatusMongo = {
  databasePassword: string;
  databaseUser: string;
};

export type PostgresChangeStatusMysql = {
  databaseRootPassword: string;
};

export type PostgresChangeStatusPostgres = {
  databaseUser: string;
};

export type PostgresChangeStatusMetadata = {
  mariadb?: PostgresChangeStatusMariadb | undefined;
  mongo?: PostgresChangeStatusMongo | undefined;
  mysql?: PostgresChangeStatusMysql | undefined;
  postgres?: PostgresChangeStatusPostgres | undefined;
};

export type PostgresChangeStatusMetadataUnion =
  | PostgresChangeStatusMetadata
  | PostgresChangeStatusMetadataEnum;

export type PostgresChangeStatusBackup = {
  appName: string;
  backupId: string;
  backupType: PostgresChangeStatusBackupType;
  composeId: string | null;
  database: string;
  databaseType: PostgresChangeStatusDatabaseType;
  destinationId: string;
  enabled: boolean | null;
  keepLatestCount: number | null;
  mariadbId: string | null;
  metadata?:
    | PostgresChangeStatusMetadata
    | PostgresChangeStatusMetadataEnum
    | null
    | undefined;
  mongoId: string | null;
  mysqlId: string | null;
  postgresId: string | null;
  prefix: string;
  schedule: string;
  serviceName: string | null;
  userId: string | null;
};

export type PostgresChangeStatusProject = {
  createdAt: string;
  description: string | null;
  env: string;
  name: string;
  organizationId: string;
  projectId: string;
};

export type PostgresChangeStatusEnvironment = {
  createdAt: string;
  description: string | null;
  env: string;
  environmentId: string;
  name: string;
  project: PostgresChangeStatusProject;
  projectId: string;
};

export type PostgresChangeStatusHealthCheckSwarm = {
  interval?: number | undefined;
  retries?: number | undefined;
  startPeriod?: number | undefined;
  test?: Array<string> | undefined;
  timeout?: number | undefined;
};

export type PostgresChangeStatusGlobal = {};

export type PostgresChangeStatusGlobalJob = {};

export type PostgresChangeStatusReplicated = {
  replicas?: number | undefined;
};

export type PostgresChangeStatusReplicatedJob = {
  maxConcurrent?: number | undefined;
  totalCompletions?: number | undefined;
};

export type PostgresChangeStatusModeSwarm = {
  global?: PostgresChangeStatusGlobal | undefined;
  globalJob?: PostgresChangeStatusGlobalJob | undefined;
  replicated?: PostgresChangeStatusReplicated | undefined;
  replicatedJob?: PostgresChangeStatusReplicatedJob | undefined;
};

export const PostgresChangeStatusServiceType = {
  Application: "application",
  Postgres: "postgres",
  Mysql: "mysql",
  Mariadb: "mariadb",
  Mongo: "mongo",
  Redis: "redis",
  Compose: "compose",
} as const;
export type PostgresChangeStatusServiceType = ClosedEnum<
  typeof PostgresChangeStatusServiceType
>;

export const PostgresChangeStatusType = {
  Bind: "bind",
  Volume: "volume",
  File: "file",
} as const;
export type PostgresChangeStatusType = ClosedEnum<
  typeof PostgresChangeStatusType
>;

export type PostgresChangeStatusMount = {
  applicationId: string | null;
  composeId: string | null;
  content: string | null;
  filePath: string | null;
  hostPath: string | null;
  mariadbId: string | null;
  mongoId: string | null;
  mountId: string;
  mountPath: string;
  mysqlId: string | null;
  postgresId: string | null;
  redisId: string | null;
  serviceType: PostgresChangeStatusServiceType;
  type: PostgresChangeStatusType;
  volumeName: string | null;
};

export type PostgresChangeStatusDriverOpts = {};

export type PostgresChangeStatusNetworkSwarm = {
  aliases?: Array<string> | undefined;
  driverOpts?: PostgresChangeStatusDriverOpts | undefined;
  target?: string | undefined;
};

export type PostgresChangeStatusPlatform = {
  architecture: string;
  os: string;
};

export type PostgresChangeStatusSpread = {
  spreadDescriptor: string;
};

export type PostgresChangeStatusPreference = {
  spread: PostgresChangeStatusSpread;
};

export type PostgresChangeStatusPlacementSwarm = {
  constraints?: Array<string> | undefined;
  maxReplicas?: number | undefined;
  platforms?: Array<PostgresChangeStatusPlatform> | undefined;
  preferences?: Array<PostgresChangeStatusPreference> | undefined;
};

export type PostgresChangeStatusRestartPolicySwarm = {
  condition?: string | undefined;
  delay?: number | undefined;
  maxAttempts?: number | undefined;
  window?: number | undefined;
};

export type PostgresChangeStatusRollbackConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

export const PostgresChangeStatusMetricsConfigEnum = {
  Null: "null",
} as const;
export type PostgresChangeStatusMetricsConfigEnum = ClosedEnum<
  typeof PostgresChangeStatusMetricsConfigEnum
>;

export type PostgresChangeStatusMetricsConfigUnion1 =
  | string
  | number
  | boolean
  | PostgresChangeStatusMetricsConfigEnum;

export type PostgresChangeStatusMetricsConfigUnion2 =
  | string
  | number
  | boolean
  | PostgresChangeStatusMetricsConfigEnum
  | Array<any>
  | { [k: string]: any };

export const PostgresChangeStatusServerStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
export type PostgresChangeStatusServerStatus = ClosedEnum<
  typeof PostgresChangeStatusServerStatus
>;

export type PostgresChangeStatusServer = {
  appName: string;
  command: string;
  createdAt: string;
  description: string | null;
  enableDockerCleanup: boolean;
  ipAddress: string;
  metricsConfig:
    | string
    | number
    | boolean
    | PostgresChangeStatusMetricsConfigEnum
    | Array<any>
    | { [k: string]: any };
  name: string;
  organizationId: string;
  port: number;
  serverId: string;
  serverStatus: PostgresChangeStatusServerStatus;
  sshKeyId: string | null;
  username: string;
};

export type PostgresChangeStatusUpdateConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

/**
 * Successful response
 */
export type PostgresChangeStatusResponseBody = {
  appName: string;
  applicationStatus: PostgresChangeStatusApplicationStatusResponse;
  backups: Array<PostgresChangeStatusBackup>;
  command: string | null;
  cpuLimit: string | null;
  cpuReservation: string | null;
  createdAt: string;
  databaseName: string;
  databasePassword: string;
  databaseUser: string;
  description: string | null;
  dockerImage: string;
  env: string | null;
  environment: PostgresChangeStatusEnvironment;
  environmentId: string;
  externalPort: number | null;
  healthCheckSwarm: PostgresChangeStatusHealthCheckSwarm | null;
  labelsSwarm: { [k: string]: string } | null;
  memoryLimit: string | null;
  memoryReservation: string | null;
  modeSwarm: PostgresChangeStatusModeSwarm | null;
  mounts: Array<PostgresChangeStatusMount>;
  name: string;
  networkSwarm: Array<PostgresChangeStatusNetworkSwarm> | null;
  placementSwarm: PostgresChangeStatusPlacementSwarm | null;
  postgresId: string;
  replicas: number;
  restartPolicySwarm: PostgresChangeStatusRestartPolicySwarm | null;
  rollbackConfigSwarm: PostgresChangeStatusRollbackConfigSwarm | null;
  server: PostgresChangeStatusServer | null;
  serverId: string | null;
  updateConfigSwarm: PostgresChangeStatusUpdateConfigSwarm | null;
};

export type PostgresChangeStatusResponse =
  | PostgresChangeStatusResponseBody
  | models.ErrorT;

/** @internal */
export const PostgresChangeStatusApplicationStatusRequest$outboundSchema:
  z.ZodNativeEnum<typeof PostgresChangeStatusApplicationStatusRequest> = z
    .nativeEnum(PostgresChangeStatusApplicationStatusRequest);

/** @internal */
export type PostgresChangeStatusRequest$Outbound = {
  applicationStatus: string;
  postgresId: string;
};

/** @internal */
export const PostgresChangeStatusRequest$outboundSchema: z.ZodType<
  PostgresChangeStatusRequest$Outbound,
  z.ZodTypeDef,
  PostgresChangeStatusRequest
> = z.object({
  applicationStatus:
    PostgresChangeStatusApplicationStatusRequest$outboundSchema,
  postgresId: z.string(),
});

export function postgresChangeStatusRequestToJSON(
  postgresChangeStatusRequest: PostgresChangeStatusRequest,
): string {
  return JSON.stringify(
    PostgresChangeStatusRequest$outboundSchema.parse(
      postgresChangeStatusRequest,
    ),
  );
}

/** @internal */
export const PostgresChangeStatusApplicationStatusResponse$inboundSchema:
  z.ZodNativeEnum<typeof PostgresChangeStatusApplicationStatusResponse> = z
    .nativeEnum(PostgresChangeStatusApplicationStatusResponse);

/** @internal */
export const PostgresChangeStatusBackupType$inboundSchema: z.ZodNativeEnum<
  typeof PostgresChangeStatusBackupType
> = z.nativeEnum(PostgresChangeStatusBackupType);

/** @internal */
export const PostgresChangeStatusDatabaseType$inboundSchema: z.ZodNativeEnum<
  typeof PostgresChangeStatusDatabaseType
> = z.nativeEnum(PostgresChangeStatusDatabaseType);

/** @internal */
export const PostgresChangeStatusMetadataEnum$inboundSchema: z.ZodNativeEnum<
  typeof PostgresChangeStatusMetadataEnum
> = z.nativeEnum(PostgresChangeStatusMetadataEnum);

/** @internal */
export const PostgresChangeStatusMariadb$inboundSchema: z.ZodType<
  PostgresChangeStatusMariadb,
  z.ZodTypeDef,
  unknown
> = z.object({
  databasePassword: z.string(),
  databaseUser: z.string(),
});

export function postgresChangeStatusMariadbFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusMariadb, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusMariadb$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusMariadb' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusMongo$inboundSchema: z.ZodType<
  PostgresChangeStatusMongo,
  z.ZodTypeDef,
  unknown
> = z.object({
  databasePassword: z.string(),
  databaseUser: z.string(),
});

export function postgresChangeStatusMongoFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusMongo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusMongo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusMongo' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusMysql$inboundSchema: z.ZodType<
  PostgresChangeStatusMysql,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseRootPassword: z.string(),
});

export function postgresChangeStatusMysqlFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusMysql, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusMysql$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusMysql' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusPostgres$inboundSchema: z.ZodType<
  PostgresChangeStatusPostgres,
  z.ZodTypeDef,
  unknown
> = z.object({
  databaseUser: z.string(),
});

export function postgresChangeStatusPostgresFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusPostgres, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusPostgres$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusPostgres' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusMetadata$inboundSchema: z.ZodType<
  PostgresChangeStatusMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  mariadb: z.lazy(() => PostgresChangeStatusMariadb$inboundSchema).optional(),
  mongo: z.lazy(() => PostgresChangeStatusMongo$inboundSchema).optional(),
  mysql: z.lazy(() => PostgresChangeStatusMysql$inboundSchema).optional(),
  postgres: z.lazy(() => PostgresChangeStatusPostgres$inboundSchema).optional(),
});

export function postgresChangeStatusMetadataFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusMetadata' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusMetadataUnion$inboundSchema: z.ZodType<
  PostgresChangeStatusMetadataUnion,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostgresChangeStatusMetadata$inboundSchema),
  PostgresChangeStatusMetadataEnum$inboundSchema,
]);

export function postgresChangeStatusMetadataUnionFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusMetadataUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusMetadataUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusMetadataUnion' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusBackup$inboundSchema: z.ZodType<
  PostgresChangeStatusBackup,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  backupId: z.string(),
  backupType: PostgresChangeStatusBackupType$inboundSchema,
  composeId: z.nullable(z.string()),
  database: z.string(),
  databaseType: PostgresChangeStatusDatabaseType$inboundSchema,
  destinationId: z.string(),
  enabled: z.nullable(z.boolean()),
  keepLatestCount: z.nullable(z.number()),
  mariadbId: z.nullable(z.string()),
  metadata: z.nullable(
    z.union([
      z.lazy(() => PostgresChangeStatusMetadata$inboundSchema),
      PostgresChangeStatusMetadataEnum$inboundSchema,
    ]),
  ).optional(),
  mongoId: z.nullable(z.string()),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  prefix: z.string(),
  schedule: z.string(),
  serviceName: z.nullable(z.string()),
  userId: z.nullable(z.string()),
});

export function postgresChangeStatusBackupFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusBackup, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusBackup$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusBackup' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusProject$inboundSchema: z.ZodType<
  PostgresChangeStatusProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  name: z.string(),
  organizationId: z.string(),
  projectId: z.string(),
});

export function postgresChangeStatusProjectFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusProject' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusEnvironment$inboundSchema: z.ZodType<
  PostgresChangeStatusEnvironment,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  environmentId: z.string(),
  name: z.string(),
  project: z.lazy(() => PostgresChangeStatusProject$inboundSchema),
  projectId: z.string(),
});

export function postgresChangeStatusEnvironmentFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusEnvironment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusEnvironment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusEnvironment' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusHealthCheckSwarm$inboundSchema: z.ZodType<
  PostgresChangeStatusHealthCheckSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Interval: z.number().optional(),
  Retries: z.number().optional(),
  StartPeriod: z.number().optional(),
  Test: z.array(z.string()).optional(),
  Timeout: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Interval": "interval",
    "Retries": "retries",
    "StartPeriod": "startPeriod",
    "Test": "test",
    "Timeout": "timeout",
  });
});

export function postgresChangeStatusHealthCheckSwarmFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusHealthCheckSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostgresChangeStatusHealthCheckSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusHealthCheckSwarm' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusGlobal$inboundSchema: z.ZodType<
  PostgresChangeStatusGlobal,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function postgresChangeStatusGlobalFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusGlobal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusGlobal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusGlobal' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusGlobalJob$inboundSchema: z.ZodType<
  PostgresChangeStatusGlobalJob,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function postgresChangeStatusGlobalJobFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusGlobalJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusGlobalJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusGlobalJob' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusReplicated$inboundSchema: z.ZodType<
  PostgresChangeStatusReplicated,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicas": "replicas",
  });
});

export function postgresChangeStatusReplicatedFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusReplicated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusReplicated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusReplicated' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusReplicatedJob$inboundSchema: z.ZodType<
  PostgresChangeStatusReplicatedJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  MaxConcurrent: z.number().optional(),
  TotalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "MaxConcurrent": "maxConcurrent",
    "TotalCompletions": "totalCompletions",
  });
});

export function postgresChangeStatusReplicatedJobFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusReplicatedJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusReplicatedJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusReplicatedJob' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusModeSwarm$inboundSchema: z.ZodType<
  PostgresChangeStatusModeSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Global: z.lazy(() => PostgresChangeStatusGlobal$inboundSchema).optional(),
  GlobalJob: z.lazy(() => PostgresChangeStatusGlobalJob$inboundSchema)
    .optional(),
  Replicated: z.lazy(() => PostgresChangeStatusReplicated$inboundSchema)
    .optional(),
  ReplicatedJob: z.lazy(() => PostgresChangeStatusReplicatedJob$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Global": "global",
    "GlobalJob": "globalJob",
    "Replicated": "replicated",
    "ReplicatedJob": "replicatedJob",
  });
});

export function postgresChangeStatusModeSwarmFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusModeSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusModeSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusModeSwarm' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusServiceType$inboundSchema: z.ZodNativeEnum<
  typeof PostgresChangeStatusServiceType
> = z.nativeEnum(PostgresChangeStatusServiceType);

/** @internal */
export const PostgresChangeStatusType$inboundSchema: z.ZodNativeEnum<
  typeof PostgresChangeStatusType
> = z.nativeEnum(PostgresChangeStatusType);

/** @internal */
export const PostgresChangeStatusMount$inboundSchema: z.ZodType<
  PostgresChangeStatusMount,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.nullable(z.string()),
  composeId: z.nullable(z.string()),
  content: z.nullable(z.string()),
  filePath: z.nullable(z.string()),
  hostPath: z.nullable(z.string()),
  mariadbId: z.nullable(z.string()),
  mongoId: z.nullable(z.string()),
  mountId: z.string(),
  mountPath: z.string(),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  redisId: z.nullable(z.string()),
  serviceType: PostgresChangeStatusServiceType$inboundSchema,
  type: PostgresChangeStatusType$inboundSchema,
  volumeName: z.nullable(z.string()),
});

export function postgresChangeStatusMountFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusMount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusMount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusMount' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusDriverOpts$inboundSchema: z.ZodType<
  PostgresChangeStatusDriverOpts,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function postgresChangeStatusDriverOptsFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusDriverOpts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusDriverOpts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusDriverOpts' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusNetworkSwarm$inboundSchema: z.ZodType<
  PostgresChangeStatusNetworkSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Aliases: z.array(z.string()).optional(),
  DriverOpts: z.lazy(() => PostgresChangeStatusDriverOpts$inboundSchema)
    .optional(),
  Target: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Aliases": "aliases",
    "DriverOpts": "driverOpts",
    "Target": "target",
  });
});

export function postgresChangeStatusNetworkSwarmFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusNetworkSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusNetworkSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusNetworkSwarm' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusPlatform$inboundSchema: z.ZodType<
  PostgresChangeStatusPlatform,
  z.ZodTypeDef,
  unknown
> = z.object({
  Architecture: z.string(),
  OS: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Architecture": "architecture",
    "OS": "os",
  });
});

export function postgresChangeStatusPlatformFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusPlatform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusPlatform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusPlatform' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusSpread$inboundSchema: z.ZodType<
  PostgresChangeStatusSpread,
  z.ZodTypeDef,
  unknown
> = z.object({
  SpreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    "SpreadDescriptor": "spreadDescriptor",
  });
});

export function postgresChangeStatusSpreadFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusSpread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusSpread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusSpread' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusPreference$inboundSchema: z.ZodType<
  PostgresChangeStatusPreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  Spread: z.lazy(() => PostgresChangeStatusSpread$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Spread": "spread",
  });
});

export function postgresChangeStatusPreferenceFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusPreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusPreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusPreference' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusPlacementSwarm$inboundSchema: z.ZodType<
  PostgresChangeStatusPlacementSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Constraints: z.array(z.string()).optional(),
  MaxReplicas: z.number().optional(),
  Platforms: z.array(z.lazy(() => PostgresChangeStatusPlatform$inboundSchema))
    .optional(),
  Preferences: z.array(
    z.lazy(() => PostgresChangeStatusPreference$inboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "Constraints": "constraints",
    "MaxReplicas": "maxReplicas",
    "Platforms": "platforms",
    "Preferences": "preferences",
  });
});

export function postgresChangeStatusPlacementSwarmFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusPlacementSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostgresChangeStatusPlacementSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusPlacementSwarm' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusRestartPolicySwarm$inboundSchema: z.ZodType<
  PostgresChangeStatusRestartPolicySwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Condition: z.string().optional(),
  Delay: z.number().optional(),
  MaxAttempts: z.number().optional(),
  Window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Condition": "condition",
    "Delay": "delay",
    "MaxAttempts": "maxAttempts",
    "Window": "window",
  });
});

export function postgresChangeStatusRestartPolicySwarmFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusRestartPolicySwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostgresChangeStatusRestartPolicySwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusRestartPolicySwarm' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusRollbackConfigSwarm$inboundSchema: z.ZodType<
  PostgresChangeStatusRollbackConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function postgresChangeStatusRollbackConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<
  PostgresChangeStatusRollbackConfigSwarm,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostgresChangeStatusRollbackConfigSwarm$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostgresChangeStatusRollbackConfigSwarm' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusMetricsConfigEnum$inboundSchema:
  z.ZodNativeEnum<typeof PostgresChangeStatusMetricsConfigEnum> = z.nativeEnum(
    PostgresChangeStatusMetricsConfigEnum,
  );

/** @internal */
export const PostgresChangeStatusMetricsConfigUnion1$inboundSchema: z.ZodType<
  PostgresChangeStatusMetricsConfigUnion1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  PostgresChangeStatusMetricsConfigEnum$inboundSchema,
]);

export function postgresChangeStatusMetricsConfigUnion1FromJSON(
  jsonString: string,
): SafeParseResult<
  PostgresChangeStatusMetricsConfigUnion1,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostgresChangeStatusMetricsConfigUnion1$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostgresChangeStatusMetricsConfigUnion1' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusMetricsConfigUnion2$inboundSchema: z.ZodType<
  PostgresChangeStatusMetricsConfigUnion2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    PostgresChangeStatusMetricsConfigEnum$inboundSchema,
  ]),
  z.array(z.any()),
  z.record(z.any()),
]);

export function postgresChangeStatusMetricsConfigUnion2FromJSON(
  jsonString: string,
): SafeParseResult<
  PostgresChangeStatusMetricsConfigUnion2,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostgresChangeStatusMetricsConfigUnion2$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostgresChangeStatusMetricsConfigUnion2' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusServerStatus$inboundSchema: z.ZodNativeEnum<
  typeof PostgresChangeStatusServerStatus
> = z.nativeEnum(PostgresChangeStatusServerStatus);

/** @internal */
export const PostgresChangeStatusServer$inboundSchema: z.ZodType<
  PostgresChangeStatusServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  command: z.string(),
  createdAt: z.string(),
  description: z.nullable(z.string()),
  enableDockerCleanup: z.boolean(),
  ipAddress: z.string(),
  metricsConfig: z.union([
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      PostgresChangeStatusMetricsConfigEnum$inboundSchema,
    ]),
    z.array(z.any()),
    z.record(z.any()),
  ]),
  name: z.string(),
  organizationId: z.string(),
  port: z.number(),
  serverId: z.string(),
  serverStatus: PostgresChangeStatusServerStatus$inboundSchema,
  sshKeyId: z.nullable(z.string()),
  username: z.string(),
});

export function postgresChangeStatusServerFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusServer' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusUpdateConfigSwarm$inboundSchema: z.ZodType<
  PostgresChangeStatusUpdateConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function postgresChangeStatusUpdateConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusUpdateConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostgresChangeStatusUpdateConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusUpdateConfigSwarm' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusResponseBody$inboundSchema: z.ZodType<
  PostgresChangeStatusResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  applicationStatus:
    PostgresChangeStatusApplicationStatusResponse$inboundSchema,
  backups: z.array(z.lazy(() => PostgresChangeStatusBackup$inboundSchema)),
  command: z.nullable(z.string()),
  cpuLimit: z.nullable(z.string()),
  cpuReservation: z.nullable(z.string()),
  createdAt: z.string(),
  databaseName: z.string(),
  databasePassword: z.string(),
  databaseUser: z.string(),
  description: z.nullable(z.string()),
  dockerImage: z.string(),
  env: z.nullable(z.string()),
  environment: z.lazy(() => PostgresChangeStatusEnvironment$inboundSchema),
  environmentId: z.string(),
  externalPort: z.nullable(z.number()),
  healthCheckSwarm: z.nullable(
    z.lazy(() => PostgresChangeStatusHealthCheckSwarm$inboundSchema),
  ),
  labelsSwarm: z.nullable(z.record(z.string())),
  memoryLimit: z.nullable(z.string()),
  memoryReservation: z.nullable(z.string()),
  modeSwarm: z.nullable(
    z.lazy(() => PostgresChangeStatusModeSwarm$inboundSchema),
  ),
  mounts: z.array(z.lazy(() => PostgresChangeStatusMount$inboundSchema)),
  name: z.string(),
  networkSwarm: z.nullable(
    z.array(z.lazy(() => PostgresChangeStatusNetworkSwarm$inboundSchema)),
  ),
  placementSwarm: z.nullable(
    z.lazy(() => PostgresChangeStatusPlacementSwarm$inboundSchema),
  ),
  postgresId: z.string(),
  replicas: z.number(),
  restartPolicySwarm: z.nullable(
    z.lazy(() => PostgresChangeStatusRestartPolicySwarm$inboundSchema),
  ),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => PostgresChangeStatusRollbackConfigSwarm$inboundSchema),
  ),
  server: z.nullable(z.lazy(() => PostgresChangeStatusServer$inboundSchema)),
  serverId: z.nullable(z.string()),
  updateConfigSwarm: z.nullable(
    z.lazy(() => PostgresChangeStatusUpdateConfigSwarm$inboundSchema),
  ),
});

export function postgresChangeStatusResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusResponseBody' from JSON`,
  );
}

/** @internal */
export const PostgresChangeStatusResponse$inboundSchema: z.ZodType<
  PostgresChangeStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PostgresChangeStatusResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function postgresChangeStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostgresChangeStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostgresChangeStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostgresChangeStatusResponse' from JSON`,
  );
}
