/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type PreviewDeploymentAllRequest = {
  applicationId: string;
};

export const PreviewDeploymentAllPreviewStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type PreviewDeploymentAllPreviewStatus = ClosedEnum<
  typeof PreviewDeploymentAllPreviewStatus
>;

export type PreviewDeploymentAllResponseBody = {
  appName: string;
  applicationId: string;
  branch: string;
  createdAt: string;
  domainId: string | null;
  expiresAt: string | null;
  previewDeploymentId: string;
  previewStatus: PreviewDeploymentAllPreviewStatus;
  pullRequestCommentId: string;
  pullRequestId: string;
  pullRequestNumber: string;
  pullRequestTitle: string;
  pullRequestURL: string;
};

export type PreviewDeploymentAllResponse =
  | models.ErrorT
  | Array<PreviewDeploymentAllResponseBody>;

/** @internal */
export type PreviewDeploymentAllRequest$Outbound = {
  applicationId: string;
};

/** @internal */
export const PreviewDeploymentAllRequest$outboundSchema: z.ZodType<
  PreviewDeploymentAllRequest$Outbound,
  z.ZodTypeDef,
  PreviewDeploymentAllRequest
> = z.object({
  applicationId: z.string(),
});

export function previewDeploymentAllRequestToJSON(
  previewDeploymentAllRequest: PreviewDeploymentAllRequest,
): string {
  return JSON.stringify(
    PreviewDeploymentAllRequest$outboundSchema.parse(
      previewDeploymentAllRequest,
    ),
  );
}

/** @internal */
export const PreviewDeploymentAllPreviewStatus$inboundSchema: z.ZodNativeEnum<
  typeof PreviewDeploymentAllPreviewStatus
> = z.nativeEnum(PreviewDeploymentAllPreviewStatus);

/** @internal */
export const PreviewDeploymentAllResponseBody$inboundSchema: z.ZodType<
  PreviewDeploymentAllResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  applicationId: z.string(),
  branch: z.string(),
  createdAt: z.string(),
  domainId: z.nullable(z.string()),
  expiresAt: z.nullable(z.string()),
  previewDeploymentId: z.string(),
  previewStatus: PreviewDeploymentAllPreviewStatus$inboundSchema,
  pullRequestCommentId: z.string(),
  pullRequestId: z.string(),
  pullRequestNumber: z.string(),
  pullRequestTitle: z.string(),
  pullRequestURL: z.string(),
});

export function previewDeploymentAllResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PreviewDeploymentAllResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewDeploymentAllResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewDeploymentAllResponseBody' from JSON`,
  );
}

/** @internal */
export const PreviewDeploymentAllResponse$inboundSchema: z.ZodType<
  PreviewDeploymentAllResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.ErrorT$inboundSchema,
  z.array(z.lazy(() => PreviewDeploymentAllResponseBody$inboundSchema)),
]);

export function previewDeploymentAllResponseFromJSON(
  jsonString: string,
): SafeParseResult<PreviewDeploymentAllResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewDeploymentAllResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewDeploymentAllResponse' from JSON`,
  );
}
