/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const ProjectDuplicateType = {
  Application: "application",
  Postgres: "postgres",
  Mariadb: "mariadb",
  Mongo: "mongo",
  Mysql: "mysql",
  Redis: "redis",
  Compose: "compose",
} as const;
export type ProjectDuplicateType = ClosedEnum<typeof ProjectDuplicateType>;

export type SelectedService = {
  id: string;
  type: ProjectDuplicateType;
};

export type ProjectDuplicateRequest = {
  description?: string | undefined;
  duplicateInSameProject?: boolean | undefined;
  includeServices?: boolean | undefined;
  name: string;
  selectedServices?: Array<SelectedService> | undefined;
  sourceEnvironmentId: string;
};

/** @internal */
export const ProjectDuplicateType$outboundSchema: z.ZodNativeEnum<
  typeof ProjectDuplicateType
> = z.nativeEnum(ProjectDuplicateType);

/** @internal */
export type SelectedService$Outbound = {
  id: string;
  type: string;
};

/** @internal */
export const SelectedService$outboundSchema: z.ZodType<
  SelectedService$Outbound,
  z.ZodTypeDef,
  SelectedService
> = z.object({
  id: z.string(),
  type: ProjectDuplicateType$outboundSchema,
});

export function selectedServiceToJSON(
  selectedService: SelectedService,
): string {
  return JSON.stringify(SelectedService$outboundSchema.parse(selectedService));
}

/** @internal */
export type ProjectDuplicateRequest$Outbound = {
  description?: string | undefined;
  duplicateInSameProject: boolean;
  includeServices: boolean;
  name: string;
  selectedServices?: Array<SelectedService$Outbound> | undefined;
  sourceEnvironmentId: string;
};

/** @internal */
export const ProjectDuplicateRequest$outboundSchema: z.ZodType<
  ProjectDuplicateRequest$Outbound,
  z.ZodTypeDef,
  ProjectDuplicateRequest
> = z.object({
  description: z.string().optional(),
  duplicateInSameProject: z.boolean().default(false),
  includeServices: z.boolean().default(true),
  name: z.string(),
  selectedServices: z.array(z.lazy(() => SelectedService$outboundSchema))
    .optional(),
  sourceEnvironmentId: z.string(),
});

export function projectDuplicateRequestToJSON(
  projectDuplicateRequest: ProjectDuplicateRequest,
): string {
  return JSON.stringify(
    ProjectDuplicateRequest$outboundSchema.parse(projectDuplicateRequest),
  );
}
