/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type RedisRemoveRequest = {
  redisId: string;
};

export const RedisRemoveApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type RedisRemoveApplicationStatus = ClosedEnum<
  typeof RedisRemoveApplicationStatus
>;

export type RedisRemoveProject = {
  createdAt: string;
  description: string | null;
  env: string;
  name: string;
  organizationId: string;
  projectId: string;
};

export type RedisRemoveEnvironment = {
  createdAt: string;
  description: string | null;
  env: string;
  environmentId: string;
  name: string;
  project: RedisRemoveProject;
  projectId: string;
};

export type RedisRemoveHealthCheckSwarm = {
  interval?: number | undefined;
  retries?: number | undefined;
  startPeriod?: number | undefined;
  test?: Array<string> | undefined;
  timeout?: number | undefined;
};

export type RedisRemoveGlobal = {};

export type RedisRemoveGlobalJob = {};

export type RedisRemoveReplicated = {
  replicas?: number | undefined;
};

export type RedisRemoveReplicatedJob = {
  maxConcurrent?: number | undefined;
  totalCompletions?: number | undefined;
};

export type RedisRemoveModeSwarm = {
  global?: RedisRemoveGlobal | undefined;
  globalJob?: RedisRemoveGlobalJob | undefined;
  replicated?: RedisRemoveReplicated | undefined;
  replicatedJob?: RedisRemoveReplicatedJob | undefined;
};

export const RedisRemoveServiceType = {
  Application: "application",
  Postgres: "postgres",
  Mysql: "mysql",
  Mariadb: "mariadb",
  Mongo: "mongo",
  Redis: "redis",
  Compose: "compose",
} as const;
export type RedisRemoveServiceType = ClosedEnum<typeof RedisRemoveServiceType>;

export const RedisRemoveType = {
  Bind: "bind",
  Volume: "volume",
  File: "file",
} as const;
export type RedisRemoveType = ClosedEnum<typeof RedisRemoveType>;

export type RedisRemoveMount = {
  applicationId: string | null;
  composeId: string | null;
  content: string | null;
  filePath: string | null;
  hostPath: string | null;
  mariadbId: string | null;
  mongoId: string | null;
  mountId: string;
  mountPath: string;
  mysqlId: string | null;
  postgresId: string | null;
  redisId: string | null;
  serviceType: RedisRemoveServiceType;
  type: RedisRemoveType;
  volumeName: string | null;
};

export type RedisRemoveDriverOpts = {};

export type RedisRemoveNetworkSwarm = {
  aliases?: Array<string> | undefined;
  driverOpts?: RedisRemoveDriverOpts | undefined;
  target?: string | undefined;
};

export type RedisRemovePlatform = {
  architecture: string;
  os: string;
};

export type RedisRemoveSpread = {
  spreadDescriptor: string;
};

export type RedisRemovePreference = {
  spread: RedisRemoveSpread;
};

export type RedisRemovePlacementSwarm = {
  constraints?: Array<string> | undefined;
  maxReplicas?: number | undefined;
  platforms?: Array<RedisRemovePlatform> | undefined;
  preferences?: Array<RedisRemovePreference> | undefined;
};

export type RedisRemoveRestartPolicySwarm = {
  condition?: string | undefined;
  delay?: number | undefined;
  maxAttempts?: number | undefined;
  window?: number | undefined;
};

export type RedisRemoveRollbackConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

export const RedisRemoveMetricsConfigEnum = {
  Null: "null",
} as const;
export type RedisRemoveMetricsConfigEnum = ClosedEnum<
  typeof RedisRemoveMetricsConfigEnum
>;

export type RedisRemoveMetricsConfigUnion1 =
  | string
  | number
  | boolean
  | RedisRemoveMetricsConfigEnum;

export type RedisRemoveMetricsConfigUnion2 =
  | string
  | number
  | boolean
  | RedisRemoveMetricsConfigEnum
  | Array<any>
  | { [k: string]: any };

export const RedisRemoveServerStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
export type RedisRemoveServerStatus = ClosedEnum<
  typeof RedisRemoveServerStatus
>;

export type RedisRemoveServer = {
  appName: string;
  command: string;
  createdAt: string;
  description: string | null;
  enableDockerCleanup: boolean;
  ipAddress: string;
  metricsConfig:
    | string
    | number
    | boolean
    | RedisRemoveMetricsConfigEnum
    | Array<any>
    | { [k: string]: any };
  name: string;
  organizationId: string;
  port: number;
  serverId: string;
  serverStatus: RedisRemoveServerStatus;
  sshKeyId: string | null;
  username: string;
};

export type RedisRemoveUpdateConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

/**
 * Successful response
 */
export type RedisRemoveResponseBody = {
  appName: string;
  applicationStatus: RedisRemoveApplicationStatus;
  command: string | null;
  cpuLimit: string | null;
  cpuReservation: string | null;
  createdAt: string;
  databasePassword: string;
  description: string | null;
  dockerImage: string;
  env: string | null;
  environment: RedisRemoveEnvironment;
  environmentId: string;
  externalPort: number | null;
  healthCheckSwarm: RedisRemoveHealthCheckSwarm | null;
  labelsSwarm: { [k: string]: string } | null;
  memoryLimit: string | null;
  memoryReservation: string | null;
  modeSwarm: RedisRemoveModeSwarm | null;
  mounts: Array<RedisRemoveMount>;
  name: string;
  networkSwarm: Array<RedisRemoveNetworkSwarm> | null;
  placementSwarm: RedisRemovePlacementSwarm | null;
  redisId: string;
  replicas: number;
  restartPolicySwarm: RedisRemoveRestartPolicySwarm | null;
  rollbackConfigSwarm: RedisRemoveRollbackConfigSwarm | null;
  server: RedisRemoveServer | null;
  serverId: string | null;
  updateConfigSwarm: RedisRemoveUpdateConfigSwarm | null;
};

export type RedisRemoveResponse = RedisRemoveResponseBody | models.ErrorT;

/** @internal */
export type RedisRemoveRequest$Outbound = {
  redisId: string;
};

/** @internal */
export const RedisRemoveRequest$outboundSchema: z.ZodType<
  RedisRemoveRequest$Outbound,
  z.ZodTypeDef,
  RedisRemoveRequest
> = z.object({
  redisId: z.string(),
});

export function redisRemoveRequestToJSON(
  redisRemoveRequest: RedisRemoveRequest,
): string {
  return JSON.stringify(
    RedisRemoveRequest$outboundSchema.parse(redisRemoveRequest),
  );
}

/** @internal */
export const RedisRemoveApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof RedisRemoveApplicationStatus
> = z.nativeEnum(RedisRemoveApplicationStatus);

/** @internal */
export const RedisRemoveProject$inboundSchema: z.ZodType<
  RedisRemoveProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  name: z.string(),
  organizationId: z.string(),
  projectId: z.string(),
});

export function redisRemoveProjectFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveProject' from JSON`,
  );
}

/** @internal */
export const RedisRemoveEnvironment$inboundSchema: z.ZodType<
  RedisRemoveEnvironment,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  environmentId: z.string(),
  name: z.string(),
  project: z.lazy(() => RedisRemoveProject$inboundSchema),
  projectId: z.string(),
});

export function redisRemoveEnvironmentFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveEnvironment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveEnvironment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveEnvironment' from JSON`,
  );
}

/** @internal */
export const RedisRemoveHealthCheckSwarm$inboundSchema: z.ZodType<
  RedisRemoveHealthCheckSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Interval: z.number().optional(),
  Retries: z.number().optional(),
  StartPeriod: z.number().optional(),
  Test: z.array(z.string()).optional(),
  Timeout: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Interval": "interval",
    "Retries": "retries",
    "StartPeriod": "startPeriod",
    "Test": "test",
    "Timeout": "timeout",
  });
});

export function redisRemoveHealthCheckSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveHealthCheckSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveHealthCheckSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveHealthCheckSwarm' from JSON`,
  );
}

/** @internal */
export const RedisRemoveGlobal$inboundSchema: z.ZodType<
  RedisRemoveGlobal,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function redisRemoveGlobalFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveGlobal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveGlobal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveGlobal' from JSON`,
  );
}

/** @internal */
export const RedisRemoveGlobalJob$inboundSchema: z.ZodType<
  RedisRemoveGlobalJob,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function redisRemoveGlobalJobFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveGlobalJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveGlobalJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveGlobalJob' from JSON`,
  );
}

/** @internal */
export const RedisRemoveReplicated$inboundSchema: z.ZodType<
  RedisRemoveReplicated,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicas": "replicas",
  });
});

export function redisRemoveReplicatedFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveReplicated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveReplicated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveReplicated' from JSON`,
  );
}

/** @internal */
export const RedisRemoveReplicatedJob$inboundSchema: z.ZodType<
  RedisRemoveReplicatedJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  MaxConcurrent: z.number().optional(),
  TotalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "MaxConcurrent": "maxConcurrent",
    "TotalCompletions": "totalCompletions",
  });
});

export function redisRemoveReplicatedJobFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveReplicatedJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveReplicatedJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveReplicatedJob' from JSON`,
  );
}

/** @internal */
export const RedisRemoveModeSwarm$inboundSchema: z.ZodType<
  RedisRemoveModeSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Global: z.lazy(() => RedisRemoveGlobal$inboundSchema).optional(),
  GlobalJob: z.lazy(() => RedisRemoveGlobalJob$inboundSchema).optional(),
  Replicated: z.lazy(() => RedisRemoveReplicated$inboundSchema).optional(),
  ReplicatedJob: z.lazy(() => RedisRemoveReplicatedJob$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Global": "global",
    "GlobalJob": "globalJob",
    "Replicated": "replicated",
    "ReplicatedJob": "replicatedJob",
  });
});

export function redisRemoveModeSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveModeSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveModeSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveModeSwarm' from JSON`,
  );
}

/** @internal */
export const RedisRemoveServiceType$inboundSchema: z.ZodNativeEnum<
  typeof RedisRemoveServiceType
> = z.nativeEnum(RedisRemoveServiceType);

/** @internal */
export const RedisRemoveType$inboundSchema: z.ZodNativeEnum<
  typeof RedisRemoveType
> = z.nativeEnum(RedisRemoveType);

/** @internal */
export const RedisRemoveMount$inboundSchema: z.ZodType<
  RedisRemoveMount,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.nullable(z.string()),
  composeId: z.nullable(z.string()),
  content: z.nullable(z.string()),
  filePath: z.nullable(z.string()),
  hostPath: z.nullable(z.string()),
  mariadbId: z.nullable(z.string()),
  mongoId: z.nullable(z.string()),
  mountId: z.string(),
  mountPath: z.string(),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  redisId: z.nullable(z.string()),
  serviceType: RedisRemoveServiceType$inboundSchema,
  type: RedisRemoveType$inboundSchema,
  volumeName: z.nullable(z.string()),
});

export function redisRemoveMountFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveMount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveMount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveMount' from JSON`,
  );
}

/** @internal */
export const RedisRemoveDriverOpts$inboundSchema: z.ZodType<
  RedisRemoveDriverOpts,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function redisRemoveDriverOptsFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveDriverOpts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveDriverOpts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveDriverOpts' from JSON`,
  );
}

/** @internal */
export const RedisRemoveNetworkSwarm$inboundSchema: z.ZodType<
  RedisRemoveNetworkSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Aliases: z.array(z.string()).optional(),
  DriverOpts: z.lazy(() => RedisRemoveDriverOpts$inboundSchema).optional(),
  Target: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Aliases": "aliases",
    "DriverOpts": "driverOpts",
    "Target": "target",
  });
});

export function redisRemoveNetworkSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveNetworkSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveNetworkSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveNetworkSwarm' from JSON`,
  );
}

/** @internal */
export const RedisRemovePlatform$inboundSchema: z.ZodType<
  RedisRemovePlatform,
  z.ZodTypeDef,
  unknown
> = z.object({
  Architecture: z.string(),
  OS: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Architecture": "architecture",
    "OS": "os",
  });
});

export function redisRemovePlatformFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemovePlatform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemovePlatform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemovePlatform' from JSON`,
  );
}

/** @internal */
export const RedisRemoveSpread$inboundSchema: z.ZodType<
  RedisRemoveSpread,
  z.ZodTypeDef,
  unknown
> = z.object({
  SpreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    "SpreadDescriptor": "spreadDescriptor",
  });
});

export function redisRemoveSpreadFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveSpread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveSpread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveSpread' from JSON`,
  );
}

/** @internal */
export const RedisRemovePreference$inboundSchema: z.ZodType<
  RedisRemovePreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  Spread: z.lazy(() => RedisRemoveSpread$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Spread": "spread",
  });
});

export function redisRemovePreferenceFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemovePreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemovePreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemovePreference' from JSON`,
  );
}

/** @internal */
export const RedisRemovePlacementSwarm$inboundSchema: z.ZodType<
  RedisRemovePlacementSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Constraints: z.array(z.string()).optional(),
  MaxReplicas: z.number().optional(),
  Platforms: z.array(z.lazy(() => RedisRemovePlatform$inboundSchema))
    .optional(),
  Preferences: z.array(z.lazy(() => RedisRemovePreference$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Constraints": "constraints",
    "MaxReplicas": "maxReplicas",
    "Platforms": "platforms",
    "Preferences": "preferences",
  });
});

export function redisRemovePlacementSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemovePlacementSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemovePlacementSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemovePlacementSwarm' from JSON`,
  );
}

/** @internal */
export const RedisRemoveRestartPolicySwarm$inboundSchema: z.ZodType<
  RedisRemoveRestartPolicySwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Condition: z.string().optional(),
  Delay: z.number().optional(),
  MaxAttempts: z.number().optional(),
  Window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Condition": "condition",
    "Delay": "delay",
    "MaxAttempts": "maxAttempts",
    "Window": "window",
  });
});

export function redisRemoveRestartPolicySwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveRestartPolicySwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveRestartPolicySwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveRestartPolicySwarm' from JSON`,
  );
}

/** @internal */
export const RedisRemoveRollbackConfigSwarm$inboundSchema: z.ZodType<
  RedisRemoveRollbackConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function redisRemoveRollbackConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveRollbackConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveRollbackConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveRollbackConfigSwarm' from JSON`,
  );
}

/** @internal */
export const RedisRemoveMetricsConfigEnum$inboundSchema: z.ZodNativeEnum<
  typeof RedisRemoveMetricsConfigEnum
> = z.nativeEnum(RedisRemoveMetricsConfigEnum);

/** @internal */
export const RedisRemoveMetricsConfigUnion1$inboundSchema: z.ZodType<
  RedisRemoveMetricsConfigUnion1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  RedisRemoveMetricsConfigEnum$inboundSchema,
]);

export function redisRemoveMetricsConfigUnion1FromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveMetricsConfigUnion1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveMetricsConfigUnion1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveMetricsConfigUnion1' from JSON`,
  );
}

/** @internal */
export const RedisRemoveMetricsConfigUnion2$inboundSchema: z.ZodType<
  RedisRemoveMetricsConfigUnion2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    RedisRemoveMetricsConfigEnum$inboundSchema,
  ]),
  z.array(z.any()),
  z.record(z.any()),
]);

export function redisRemoveMetricsConfigUnion2FromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveMetricsConfigUnion2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveMetricsConfigUnion2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveMetricsConfigUnion2' from JSON`,
  );
}

/** @internal */
export const RedisRemoveServerStatus$inboundSchema: z.ZodNativeEnum<
  typeof RedisRemoveServerStatus
> = z.nativeEnum(RedisRemoveServerStatus);

/** @internal */
export const RedisRemoveServer$inboundSchema: z.ZodType<
  RedisRemoveServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  command: z.string(),
  createdAt: z.string(),
  description: z.nullable(z.string()),
  enableDockerCleanup: z.boolean(),
  ipAddress: z.string(),
  metricsConfig: z.union([
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      RedisRemoveMetricsConfigEnum$inboundSchema,
    ]),
    z.array(z.any()),
    z.record(z.any()),
  ]),
  name: z.string(),
  organizationId: z.string(),
  port: z.number(),
  serverId: z.string(),
  serverStatus: RedisRemoveServerStatus$inboundSchema,
  sshKeyId: z.nullable(z.string()),
  username: z.string(),
});

export function redisRemoveServerFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveServer' from JSON`,
  );
}

/** @internal */
export const RedisRemoveUpdateConfigSwarm$inboundSchema: z.ZodType<
  RedisRemoveUpdateConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function redisRemoveUpdateConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveUpdateConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveUpdateConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveUpdateConfigSwarm' from JSON`,
  );
}

/** @internal */
export const RedisRemoveResponseBody$inboundSchema: z.ZodType<
  RedisRemoveResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  applicationStatus: RedisRemoveApplicationStatus$inboundSchema,
  command: z.nullable(z.string()),
  cpuLimit: z.nullable(z.string()),
  cpuReservation: z.nullable(z.string()),
  createdAt: z.string(),
  databasePassword: z.string(),
  description: z.nullable(z.string()),
  dockerImage: z.string(),
  env: z.nullable(z.string()),
  environment: z.lazy(() => RedisRemoveEnvironment$inboundSchema),
  environmentId: z.string(),
  externalPort: z.nullable(z.number()),
  healthCheckSwarm: z.nullable(
    z.lazy(() => RedisRemoveHealthCheckSwarm$inboundSchema),
  ),
  labelsSwarm: z.nullable(z.record(z.string())),
  memoryLimit: z.nullable(z.string()),
  memoryReservation: z.nullable(z.string()),
  modeSwarm: z.nullable(z.lazy(() => RedisRemoveModeSwarm$inboundSchema)),
  mounts: z.array(z.lazy(() => RedisRemoveMount$inboundSchema)),
  name: z.string(),
  networkSwarm: z.nullable(
    z.array(z.lazy(() => RedisRemoveNetworkSwarm$inboundSchema)),
  ),
  placementSwarm: z.nullable(
    z.lazy(() => RedisRemovePlacementSwarm$inboundSchema),
  ),
  redisId: z.string(),
  replicas: z.number(),
  restartPolicySwarm: z.nullable(
    z.lazy(() => RedisRemoveRestartPolicySwarm$inboundSchema),
  ),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => RedisRemoveRollbackConfigSwarm$inboundSchema),
  ),
  server: z.nullable(z.lazy(() => RedisRemoveServer$inboundSchema)),
  serverId: z.nullable(z.string()),
  updateConfigSwarm: z.nullable(
    z.lazy(() => RedisRemoveUpdateConfigSwarm$inboundSchema),
  ),
});

export function redisRemoveResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveResponseBody' from JSON`,
  );
}

/** @internal */
export const RedisRemoveResponse$inboundSchema: z.ZodType<
  RedisRemoveResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => RedisRemoveResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function redisRemoveResponseFromJSON(
  jsonString: string,
): SafeParseResult<RedisRemoveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisRemoveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisRemoveResponse' from JSON`,
  );
}
