/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type RedisDeployRequest = {
  redisId: string;
};

export const RedisDeployApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type RedisDeployApplicationStatus = ClosedEnum<
  typeof RedisDeployApplicationStatus
>;

export type RedisDeployProject = {
  createdAt: string;
  description: string | null;
  env: string;
  name: string;
  organizationId: string;
  projectId: string;
};

export type RedisDeployEnvironment = {
  createdAt: string;
  description: string | null;
  env: string;
  environmentId: string;
  name: string;
  project: RedisDeployProject;
  projectId: string;
};

export type RedisDeployHealthCheckSwarm = {
  interval?: number | undefined;
  retries?: number | undefined;
  startPeriod?: number | undefined;
  test?: Array<string> | undefined;
  timeout?: number | undefined;
};

export type RedisDeployGlobal = {};

export type RedisDeployGlobalJob = {};

export type RedisDeployReplicated = {
  replicas?: number | undefined;
};

export type RedisDeployReplicatedJob = {
  maxConcurrent?: number | undefined;
  totalCompletions?: number | undefined;
};

export type RedisDeployModeSwarm = {
  global?: RedisDeployGlobal | undefined;
  globalJob?: RedisDeployGlobalJob | undefined;
  replicated?: RedisDeployReplicated | undefined;
  replicatedJob?: RedisDeployReplicatedJob | undefined;
};

export const RedisDeployServiceType = {
  Application: "application",
  Postgres: "postgres",
  Mysql: "mysql",
  Mariadb: "mariadb",
  Mongo: "mongo",
  Redis: "redis",
  Compose: "compose",
} as const;
export type RedisDeployServiceType = ClosedEnum<typeof RedisDeployServiceType>;

export const RedisDeployType = {
  Bind: "bind",
  Volume: "volume",
  File: "file",
} as const;
export type RedisDeployType = ClosedEnum<typeof RedisDeployType>;

export type RedisDeployMount = {
  applicationId: string | null;
  composeId: string | null;
  content: string | null;
  filePath: string | null;
  hostPath: string | null;
  mariadbId: string | null;
  mongoId: string | null;
  mountId: string;
  mountPath: string;
  mysqlId: string | null;
  postgresId: string | null;
  redisId: string | null;
  serviceType: RedisDeployServiceType;
  type: RedisDeployType;
  volumeName: string | null;
};

export type RedisDeployDriverOpts = {};

export type RedisDeployNetworkSwarm = {
  aliases?: Array<string> | undefined;
  driverOpts?: RedisDeployDriverOpts | undefined;
  target?: string | undefined;
};

export type RedisDeployPlatform = {
  architecture: string;
  os: string;
};

export type RedisDeploySpread = {
  spreadDescriptor: string;
};

export type RedisDeployPreference = {
  spread: RedisDeploySpread;
};

export type RedisDeployPlacementSwarm = {
  constraints?: Array<string> | undefined;
  maxReplicas?: number | undefined;
  platforms?: Array<RedisDeployPlatform> | undefined;
  preferences?: Array<RedisDeployPreference> | undefined;
};

export type RedisDeployRestartPolicySwarm = {
  condition?: string | undefined;
  delay?: number | undefined;
  maxAttempts?: number | undefined;
  window?: number | undefined;
};

export type RedisDeployRollbackConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

export const RedisDeployMetricsConfigEnum = {
  Null: "null",
} as const;
export type RedisDeployMetricsConfigEnum = ClosedEnum<
  typeof RedisDeployMetricsConfigEnum
>;

export type RedisDeployMetricsConfigUnion1 =
  | string
  | number
  | boolean
  | RedisDeployMetricsConfigEnum;

export type RedisDeployMetricsConfigUnion2 =
  | string
  | number
  | boolean
  | RedisDeployMetricsConfigEnum
  | Array<any>
  | { [k: string]: any };

export const RedisDeployServerStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
export type RedisDeployServerStatus = ClosedEnum<
  typeof RedisDeployServerStatus
>;

export type RedisDeployServer = {
  appName: string;
  command: string;
  createdAt: string;
  description: string | null;
  enableDockerCleanup: boolean;
  ipAddress: string;
  metricsConfig:
    | string
    | number
    | boolean
    | RedisDeployMetricsConfigEnum
    | Array<any>
    | { [k: string]: any };
  name: string;
  organizationId: string;
  port: number;
  serverId: string;
  serverStatus: RedisDeployServerStatus;
  sshKeyId: string | null;
  username: string;
};

export type RedisDeployUpdateConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

/**
 * Successful response
 */
export type RedisDeployResponseBody = {
  appName: string;
  applicationStatus: RedisDeployApplicationStatus;
  command: string | null;
  cpuLimit: string | null;
  cpuReservation: string | null;
  createdAt: string;
  databasePassword: string;
  description: string | null;
  dockerImage: string;
  env: string | null;
  environment: RedisDeployEnvironment;
  environmentId: string;
  externalPort: number | null;
  healthCheckSwarm: RedisDeployHealthCheckSwarm | null;
  labelsSwarm: { [k: string]: string } | null;
  memoryLimit: string | null;
  memoryReservation: string | null;
  modeSwarm: RedisDeployModeSwarm | null;
  mounts: Array<RedisDeployMount>;
  name: string;
  networkSwarm: Array<RedisDeployNetworkSwarm> | null;
  placementSwarm: RedisDeployPlacementSwarm | null;
  redisId: string;
  replicas: number;
  restartPolicySwarm: RedisDeployRestartPolicySwarm | null;
  rollbackConfigSwarm: RedisDeployRollbackConfigSwarm | null;
  server: RedisDeployServer | null;
  serverId: string | null;
  updateConfigSwarm: RedisDeployUpdateConfigSwarm | null;
};

export type RedisDeployResponse = RedisDeployResponseBody | models.ErrorT;

/** @internal */
export type RedisDeployRequest$Outbound = {
  redisId: string;
};

/** @internal */
export const RedisDeployRequest$outboundSchema: z.ZodType<
  RedisDeployRequest$Outbound,
  z.ZodTypeDef,
  RedisDeployRequest
> = z.object({
  redisId: z.string(),
});

export function redisDeployRequestToJSON(
  redisDeployRequest: RedisDeployRequest,
): string {
  return JSON.stringify(
    RedisDeployRequest$outboundSchema.parse(redisDeployRequest),
  );
}

/** @internal */
export const RedisDeployApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof RedisDeployApplicationStatus
> = z.nativeEnum(RedisDeployApplicationStatus);

/** @internal */
export const RedisDeployProject$inboundSchema: z.ZodType<
  RedisDeployProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  name: z.string(),
  organizationId: z.string(),
  projectId: z.string(),
});

export function redisDeployProjectFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployProject' from JSON`,
  );
}

/** @internal */
export const RedisDeployEnvironment$inboundSchema: z.ZodType<
  RedisDeployEnvironment,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  environmentId: z.string(),
  name: z.string(),
  project: z.lazy(() => RedisDeployProject$inboundSchema),
  projectId: z.string(),
});

export function redisDeployEnvironmentFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployEnvironment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployEnvironment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployEnvironment' from JSON`,
  );
}

/** @internal */
export const RedisDeployHealthCheckSwarm$inboundSchema: z.ZodType<
  RedisDeployHealthCheckSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Interval: z.number().optional(),
  Retries: z.number().optional(),
  StartPeriod: z.number().optional(),
  Test: z.array(z.string()).optional(),
  Timeout: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Interval": "interval",
    "Retries": "retries",
    "StartPeriod": "startPeriod",
    "Test": "test",
    "Timeout": "timeout",
  });
});

export function redisDeployHealthCheckSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployHealthCheckSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployHealthCheckSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployHealthCheckSwarm' from JSON`,
  );
}

/** @internal */
export const RedisDeployGlobal$inboundSchema: z.ZodType<
  RedisDeployGlobal,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function redisDeployGlobalFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployGlobal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployGlobal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployGlobal' from JSON`,
  );
}

/** @internal */
export const RedisDeployGlobalJob$inboundSchema: z.ZodType<
  RedisDeployGlobalJob,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function redisDeployGlobalJobFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployGlobalJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployGlobalJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployGlobalJob' from JSON`,
  );
}

/** @internal */
export const RedisDeployReplicated$inboundSchema: z.ZodType<
  RedisDeployReplicated,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicas": "replicas",
  });
});

export function redisDeployReplicatedFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployReplicated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployReplicated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployReplicated' from JSON`,
  );
}

/** @internal */
export const RedisDeployReplicatedJob$inboundSchema: z.ZodType<
  RedisDeployReplicatedJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  MaxConcurrent: z.number().optional(),
  TotalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "MaxConcurrent": "maxConcurrent",
    "TotalCompletions": "totalCompletions",
  });
});

export function redisDeployReplicatedJobFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployReplicatedJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployReplicatedJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployReplicatedJob' from JSON`,
  );
}

/** @internal */
export const RedisDeployModeSwarm$inboundSchema: z.ZodType<
  RedisDeployModeSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Global: z.lazy(() => RedisDeployGlobal$inboundSchema).optional(),
  GlobalJob: z.lazy(() => RedisDeployGlobalJob$inboundSchema).optional(),
  Replicated: z.lazy(() => RedisDeployReplicated$inboundSchema).optional(),
  ReplicatedJob: z.lazy(() => RedisDeployReplicatedJob$inboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Global": "global",
    "GlobalJob": "globalJob",
    "Replicated": "replicated",
    "ReplicatedJob": "replicatedJob",
  });
});

export function redisDeployModeSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployModeSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployModeSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployModeSwarm' from JSON`,
  );
}

/** @internal */
export const RedisDeployServiceType$inboundSchema: z.ZodNativeEnum<
  typeof RedisDeployServiceType
> = z.nativeEnum(RedisDeployServiceType);

/** @internal */
export const RedisDeployType$inboundSchema: z.ZodNativeEnum<
  typeof RedisDeployType
> = z.nativeEnum(RedisDeployType);

/** @internal */
export const RedisDeployMount$inboundSchema: z.ZodType<
  RedisDeployMount,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.nullable(z.string()),
  composeId: z.nullable(z.string()),
  content: z.nullable(z.string()),
  filePath: z.nullable(z.string()),
  hostPath: z.nullable(z.string()),
  mariadbId: z.nullable(z.string()),
  mongoId: z.nullable(z.string()),
  mountId: z.string(),
  mountPath: z.string(),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  redisId: z.nullable(z.string()),
  serviceType: RedisDeployServiceType$inboundSchema,
  type: RedisDeployType$inboundSchema,
  volumeName: z.nullable(z.string()),
});

export function redisDeployMountFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployMount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployMount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployMount' from JSON`,
  );
}

/** @internal */
export const RedisDeployDriverOpts$inboundSchema: z.ZodType<
  RedisDeployDriverOpts,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function redisDeployDriverOptsFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployDriverOpts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployDriverOpts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployDriverOpts' from JSON`,
  );
}

/** @internal */
export const RedisDeployNetworkSwarm$inboundSchema: z.ZodType<
  RedisDeployNetworkSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Aliases: z.array(z.string()).optional(),
  DriverOpts: z.lazy(() => RedisDeployDriverOpts$inboundSchema).optional(),
  Target: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Aliases": "aliases",
    "DriverOpts": "driverOpts",
    "Target": "target",
  });
});

export function redisDeployNetworkSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployNetworkSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployNetworkSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployNetworkSwarm' from JSON`,
  );
}

/** @internal */
export const RedisDeployPlatform$inboundSchema: z.ZodType<
  RedisDeployPlatform,
  z.ZodTypeDef,
  unknown
> = z.object({
  Architecture: z.string(),
  OS: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Architecture": "architecture",
    "OS": "os",
  });
});

export function redisDeployPlatformFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployPlatform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployPlatform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployPlatform' from JSON`,
  );
}

/** @internal */
export const RedisDeploySpread$inboundSchema: z.ZodType<
  RedisDeploySpread,
  z.ZodTypeDef,
  unknown
> = z.object({
  SpreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    "SpreadDescriptor": "spreadDescriptor",
  });
});

export function redisDeploySpreadFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeploySpread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeploySpread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeploySpread' from JSON`,
  );
}

/** @internal */
export const RedisDeployPreference$inboundSchema: z.ZodType<
  RedisDeployPreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  Spread: z.lazy(() => RedisDeploySpread$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Spread": "spread",
  });
});

export function redisDeployPreferenceFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployPreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployPreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployPreference' from JSON`,
  );
}

/** @internal */
export const RedisDeployPlacementSwarm$inboundSchema: z.ZodType<
  RedisDeployPlacementSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Constraints: z.array(z.string()).optional(),
  MaxReplicas: z.number().optional(),
  Platforms: z.array(z.lazy(() => RedisDeployPlatform$inboundSchema))
    .optional(),
  Preferences: z.array(z.lazy(() => RedisDeployPreference$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Constraints": "constraints",
    "MaxReplicas": "maxReplicas",
    "Platforms": "platforms",
    "Preferences": "preferences",
  });
});

export function redisDeployPlacementSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployPlacementSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployPlacementSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployPlacementSwarm' from JSON`,
  );
}

/** @internal */
export const RedisDeployRestartPolicySwarm$inboundSchema: z.ZodType<
  RedisDeployRestartPolicySwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Condition: z.string().optional(),
  Delay: z.number().optional(),
  MaxAttempts: z.number().optional(),
  Window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Condition": "condition",
    "Delay": "delay",
    "MaxAttempts": "maxAttempts",
    "Window": "window",
  });
});

export function redisDeployRestartPolicySwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployRestartPolicySwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployRestartPolicySwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployRestartPolicySwarm' from JSON`,
  );
}

/** @internal */
export const RedisDeployRollbackConfigSwarm$inboundSchema: z.ZodType<
  RedisDeployRollbackConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function redisDeployRollbackConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployRollbackConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployRollbackConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployRollbackConfigSwarm' from JSON`,
  );
}

/** @internal */
export const RedisDeployMetricsConfigEnum$inboundSchema: z.ZodNativeEnum<
  typeof RedisDeployMetricsConfigEnum
> = z.nativeEnum(RedisDeployMetricsConfigEnum);

/** @internal */
export const RedisDeployMetricsConfigUnion1$inboundSchema: z.ZodType<
  RedisDeployMetricsConfigUnion1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  RedisDeployMetricsConfigEnum$inboundSchema,
]);

export function redisDeployMetricsConfigUnion1FromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployMetricsConfigUnion1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployMetricsConfigUnion1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployMetricsConfigUnion1' from JSON`,
  );
}

/** @internal */
export const RedisDeployMetricsConfigUnion2$inboundSchema: z.ZodType<
  RedisDeployMetricsConfigUnion2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    RedisDeployMetricsConfigEnum$inboundSchema,
  ]),
  z.array(z.any()),
  z.record(z.any()),
]);

export function redisDeployMetricsConfigUnion2FromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployMetricsConfigUnion2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployMetricsConfigUnion2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployMetricsConfigUnion2' from JSON`,
  );
}

/** @internal */
export const RedisDeployServerStatus$inboundSchema: z.ZodNativeEnum<
  typeof RedisDeployServerStatus
> = z.nativeEnum(RedisDeployServerStatus);

/** @internal */
export const RedisDeployServer$inboundSchema: z.ZodType<
  RedisDeployServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  command: z.string(),
  createdAt: z.string(),
  description: z.nullable(z.string()),
  enableDockerCleanup: z.boolean(),
  ipAddress: z.string(),
  metricsConfig: z.union([
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      RedisDeployMetricsConfigEnum$inboundSchema,
    ]),
    z.array(z.any()),
    z.record(z.any()),
  ]),
  name: z.string(),
  organizationId: z.string(),
  port: z.number(),
  serverId: z.string(),
  serverStatus: RedisDeployServerStatus$inboundSchema,
  sshKeyId: z.nullable(z.string()),
  username: z.string(),
});

export function redisDeployServerFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployServer' from JSON`,
  );
}

/** @internal */
export const RedisDeployUpdateConfigSwarm$inboundSchema: z.ZodType<
  RedisDeployUpdateConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function redisDeployUpdateConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployUpdateConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployUpdateConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployUpdateConfigSwarm' from JSON`,
  );
}

/** @internal */
export const RedisDeployResponseBody$inboundSchema: z.ZodType<
  RedisDeployResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  applicationStatus: RedisDeployApplicationStatus$inboundSchema,
  command: z.nullable(z.string()),
  cpuLimit: z.nullable(z.string()),
  cpuReservation: z.nullable(z.string()),
  createdAt: z.string(),
  databasePassword: z.string(),
  description: z.nullable(z.string()),
  dockerImage: z.string(),
  env: z.nullable(z.string()),
  environment: z.lazy(() => RedisDeployEnvironment$inboundSchema),
  environmentId: z.string(),
  externalPort: z.nullable(z.number()),
  healthCheckSwarm: z.nullable(
    z.lazy(() => RedisDeployHealthCheckSwarm$inboundSchema),
  ),
  labelsSwarm: z.nullable(z.record(z.string())),
  memoryLimit: z.nullable(z.string()),
  memoryReservation: z.nullable(z.string()),
  modeSwarm: z.nullable(z.lazy(() => RedisDeployModeSwarm$inboundSchema)),
  mounts: z.array(z.lazy(() => RedisDeployMount$inboundSchema)),
  name: z.string(),
  networkSwarm: z.nullable(
    z.array(z.lazy(() => RedisDeployNetworkSwarm$inboundSchema)),
  ),
  placementSwarm: z.nullable(
    z.lazy(() => RedisDeployPlacementSwarm$inboundSchema),
  ),
  redisId: z.string(),
  replicas: z.number(),
  restartPolicySwarm: z.nullable(
    z.lazy(() => RedisDeployRestartPolicySwarm$inboundSchema),
  ),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => RedisDeployRollbackConfigSwarm$inboundSchema),
  ),
  server: z.nullable(z.lazy(() => RedisDeployServer$inboundSchema)),
  serverId: z.nullable(z.string()),
  updateConfigSwarm: z.nullable(
    z.lazy(() => RedisDeployUpdateConfigSwarm$inboundSchema),
  ),
});

export function redisDeployResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployResponseBody' from JSON`,
  );
}

/** @internal */
export const RedisDeployResponse$inboundSchema: z.ZodType<
  RedisDeployResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => RedisDeployResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function redisDeployResponseFromJSON(
  jsonString: string,
): SafeParseResult<RedisDeployResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisDeployResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisDeployResponse' from JSON`,
  );
}
