/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type RedirectsOneRequest = {
  redirectId: string;
};

/**
 * Successful response
 */
export type RedirectsOneResponseBody = {
  applicationId: string;
  createdAt: string;
  permanent: boolean;
  redirectId: string;
  regex: string;
  replacement: string;
  uniqueConfigKey: number;
};

export type RedirectsOneResponse = RedirectsOneResponseBody | models.ErrorT;

/** @internal */
export type RedirectsOneRequest$Outbound = {
  redirectId: string;
};

/** @internal */
export const RedirectsOneRequest$outboundSchema: z.ZodType<
  RedirectsOneRequest$Outbound,
  z.ZodTypeDef,
  RedirectsOneRequest
> = z.object({
  redirectId: z.string(),
});

export function redirectsOneRequestToJSON(
  redirectsOneRequest: RedirectsOneRequest,
): string {
  return JSON.stringify(
    RedirectsOneRequest$outboundSchema.parse(redirectsOneRequest),
  );
}

/** @internal */
export const RedirectsOneResponseBody$inboundSchema: z.ZodType<
  RedirectsOneResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
  createdAt: z.string(),
  permanent: z.boolean(),
  redirectId: z.string(),
  regex: z.string(),
  replacement: z.string(),
  uniqueConfigKey: z.number(),
});

export function redirectsOneResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<RedirectsOneResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedirectsOneResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedirectsOneResponseBody' from JSON`,
  );
}

/** @internal */
export const RedirectsOneResponse$inboundSchema: z.ZodType<
  RedirectsOneResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => RedirectsOneResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function redirectsOneResponseFromJSON(
  jsonString: string,
): SafeParseResult<RedirectsOneResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedirectsOneResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedirectsOneResponse' from JSON`,
  );
}
