/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type RedisStopRequest = {
  redisId: string;
};

export const RedisStopApplicationStatus = {
  Idle: "idle",
  Running: "running",
  Done: "done",
  Error: "error",
} as const;
export type RedisStopApplicationStatus = ClosedEnum<
  typeof RedisStopApplicationStatus
>;

export type RedisStopProject = {
  createdAt: string;
  description: string | null;
  env: string;
  name: string;
  organizationId: string;
  projectId: string;
};

export type RedisStopEnvironment = {
  createdAt: string;
  description: string | null;
  env: string;
  environmentId: string;
  name: string;
  project: RedisStopProject;
  projectId: string;
};

export type RedisStopHealthCheckSwarm = {
  interval?: number | undefined;
  retries?: number | undefined;
  startPeriod?: number | undefined;
  test?: Array<string> | undefined;
  timeout?: number | undefined;
};

export type RedisStopGlobal = {};

export type RedisStopGlobalJob = {};

export type RedisStopReplicated = {
  replicas?: number | undefined;
};

export type RedisStopReplicatedJob = {
  maxConcurrent?: number | undefined;
  totalCompletions?: number | undefined;
};

export type RedisStopModeSwarm = {
  global?: RedisStopGlobal | undefined;
  globalJob?: RedisStopGlobalJob | undefined;
  replicated?: RedisStopReplicated | undefined;
  replicatedJob?: RedisStopReplicatedJob | undefined;
};

export const RedisStopServiceType = {
  Application: "application",
  Postgres: "postgres",
  Mysql: "mysql",
  Mariadb: "mariadb",
  Mongo: "mongo",
  Redis: "redis",
  Compose: "compose",
} as const;
export type RedisStopServiceType = ClosedEnum<typeof RedisStopServiceType>;

export const RedisStopType = {
  Bind: "bind",
  Volume: "volume",
  File: "file",
} as const;
export type RedisStopType = ClosedEnum<typeof RedisStopType>;

export type RedisStopMount = {
  applicationId: string | null;
  composeId: string | null;
  content: string | null;
  filePath: string | null;
  hostPath: string | null;
  mariadbId: string | null;
  mongoId: string | null;
  mountId: string;
  mountPath: string;
  mysqlId: string | null;
  postgresId: string | null;
  redisId: string | null;
  serviceType: RedisStopServiceType;
  type: RedisStopType;
  volumeName: string | null;
};

export type RedisStopDriverOpts = {};

export type RedisStopNetworkSwarm = {
  aliases?: Array<string> | undefined;
  driverOpts?: RedisStopDriverOpts | undefined;
  target?: string | undefined;
};

export type RedisStopPlatform = {
  architecture: string;
  os: string;
};

export type RedisStopSpread = {
  spreadDescriptor: string;
};

export type RedisStopPreference = {
  spread: RedisStopSpread;
};

export type RedisStopPlacementSwarm = {
  constraints?: Array<string> | undefined;
  maxReplicas?: number | undefined;
  platforms?: Array<RedisStopPlatform> | undefined;
  preferences?: Array<RedisStopPreference> | undefined;
};

export type RedisStopRestartPolicySwarm = {
  condition?: string | undefined;
  delay?: number | undefined;
  maxAttempts?: number | undefined;
  window?: number | undefined;
};

export type RedisStopRollbackConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

export const RedisStopMetricsConfigEnum = {
  Null: "null",
} as const;
export type RedisStopMetricsConfigEnum = ClosedEnum<
  typeof RedisStopMetricsConfigEnum
>;

export type RedisStopMetricsConfigUnion1 =
  | string
  | number
  | boolean
  | RedisStopMetricsConfigEnum;

export type RedisStopMetricsConfigUnion2 =
  | string
  | number
  | boolean
  | RedisStopMetricsConfigEnum
  | Array<any>
  | { [k: string]: any };

export const RedisStopServerStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
export type RedisStopServerStatus = ClosedEnum<typeof RedisStopServerStatus>;

export type RedisStopServer = {
  appName: string;
  command: string;
  createdAt: string;
  description: string | null;
  enableDockerCleanup: boolean;
  ipAddress: string;
  metricsConfig:
    | string
    | number
    | boolean
    | RedisStopMetricsConfigEnum
    | Array<any>
    | { [k: string]: any };
  name: string;
  organizationId: string;
  port: number;
  serverId: string;
  serverStatus: RedisStopServerStatus;
  sshKeyId: string | null;
  username: string;
};

export type RedisStopUpdateConfigSwarm = {
  delay?: number | undefined;
  failureAction?: string | undefined;
  maxFailureRatio?: number | undefined;
  monitor?: number | undefined;
  order: string;
  parallelism: number;
};

/**
 * Successful response
 */
export type RedisStopResponseBody = {
  appName: string;
  applicationStatus: RedisStopApplicationStatus;
  command: string | null;
  cpuLimit: string | null;
  cpuReservation: string | null;
  createdAt: string;
  databasePassword: string;
  description: string | null;
  dockerImage: string;
  env: string | null;
  environment: RedisStopEnvironment;
  environmentId: string;
  externalPort: number | null;
  healthCheckSwarm: RedisStopHealthCheckSwarm | null;
  labelsSwarm: { [k: string]: string } | null;
  memoryLimit: string | null;
  memoryReservation: string | null;
  modeSwarm: RedisStopModeSwarm | null;
  mounts: Array<RedisStopMount>;
  name: string;
  networkSwarm: Array<RedisStopNetworkSwarm> | null;
  placementSwarm: RedisStopPlacementSwarm | null;
  redisId: string;
  replicas: number;
  restartPolicySwarm: RedisStopRestartPolicySwarm | null;
  rollbackConfigSwarm: RedisStopRollbackConfigSwarm | null;
  server: RedisStopServer | null;
  serverId: string | null;
  updateConfigSwarm: RedisStopUpdateConfigSwarm | null;
};

export type RedisStopResponse = RedisStopResponseBody | models.ErrorT;

/** @internal */
export type RedisStopRequest$Outbound = {
  redisId: string;
};

/** @internal */
export const RedisStopRequest$outboundSchema: z.ZodType<
  RedisStopRequest$Outbound,
  z.ZodTypeDef,
  RedisStopRequest
> = z.object({
  redisId: z.string(),
});

export function redisStopRequestToJSON(
  redisStopRequest: RedisStopRequest,
): string {
  return JSON.stringify(
    RedisStopRequest$outboundSchema.parse(redisStopRequest),
  );
}

/** @internal */
export const RedisStopApplicationStatus$inboundSchema: z.ZodNativeEnum<
  typeof RedisStopApplicationStatus
> = z.nativeEnum(RedisStopApplicationStatus);

/** @internal */
export const RedisStopProject$inboundSchema: z.ZodType<
  RedisStopProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  name: z.string(),
  organizationId: z.string(),
  projectId: z.string(),
});

export function redisStopProjectFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopProject' from JSON`,
  );
}

/** @internal */
export const RedisStopEnvironment$inboundSchema: z.ZodType<
  RedisStopEnvironment,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string(),
  description: z.nullable(z.string()),
  env: z.string(),
  environmentId: z.string(),
  name: z.string(),
  project: z.lazy(() => RedisStopProject$inboundSchema),
  projectId: z.string(),
});

export function redisStopEnvironmentFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopEnvironment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopEnvironment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopEnvironment' from JSON`,
  );
}

/** @internal */
export const RedisStopHealthCheckSwarm$inboundSchema: z.ZodType<
  RedisStopHealthCheckSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Interval: z.number().optional(),
  Retries: z.number().optional(),
  StartPeriod: z.number().optional(),
  Test: z.array(z.string()).optional(),
  Timeout: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Interval": "interval",
    "Retries": "retries",
    "StartPeriod": "startPeriod",
    "Test": "test",
    "Timeout": "timeout",
  });
});

export function redisStopHealthCheckSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopHealthCheckSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopHealthCheckSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopHealthCheckSwarm' from JSON`,
  );
}

/** @internal */
export const RedisStopGlobal$inboundSchema: z.ZodType<
  RedisStopGlobal,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function redisStopGlobalFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopGlobal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopGlobal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopGlobal' from JSON`,
  );
}

/** @internal */
export const RedisStopGlobalJob$inboundSchema: z.ZodType<
  RedisStopGlobalJob,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function redisStopGlobalJobFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopGlobalJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopGlobalJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopGlobalJob' from JSON`,
  );
}

/** @internal */
export const RedisStopReplicated$inboundSchema: z.ZodType<
  RedisStopReplicated,
  z.ZodTypeDef,
  unknown
> = z.object({
  Replicas: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Replicas": "replicas",
  });
});

export function redisStopReplicatedFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopReplicated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopReplicated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopReplicated' from JSON`,
  );
}

/** @internal */
export const RedisStopReplicatedJob$inboundSchema: z.ZodType<
  RedisStopReplicatedJob,
  z.ZodTypeDef,
  unknown
> = z.object({
  MaxConcurrent: z.number().optional(),
  TotalCompletions: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "MaxConcurrent": "maxConcurrent",
    "TotalCompletions": "totalCompletions",
  });
});

export function redisStopReplicatedJobFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopReplicatedJob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopReplicatedJob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopReplicatedJob' from JSON`,
  );
}

/** @internal */
export const RedisStopModeSwarm$inboundSchema: z.ZodType<
  RedisStopModeSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Global: z.lazy(() => RedisStopGlobal$inboundSchema).optional(),
  GlobalJob: z.lazy(() => RedisStopGlobalJob$inboundSchema).optional(),
  Replicated: z.lazy(() => RedisStopReplicated$inboundSchema).optional(),
  ReplicatedJob: z.lazy(() => RedisStopReplicatedJob$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "Global": "global",
    "GlobalJob": "globalJob",
    "Replicated": "replicated",
    "ReplicatedJob": "replicatedJob",
  });
});

export function redisStopModeSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopModeSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopModeSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopModeSwarm' from JSON`,
  );
}

/** @internal */
export const RedisStopServiceType$inboundSchema: z.ZodNativeEnum<
  typeof RedisStopServiceType
> = z.nativeEnum(RedisStopServiceType);

/** @internal */
export const RedisStopType$inboundSchema: z.ZodNativeEnum<
  typeof RedisStopType
> = z.nativeEnum(RedisStopType);

/** @internal */
export const RedisStopMount$inboundSchema: z.ZodType<
  RedisStopMount,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.nullable(z.string()),
  composeId: z.nullable(z.string()),
  content: z.nullable(z.string()),
  filePath: z.nullable(z.string()),
  hostPath: z.nullable(z.string()),
  mariadbId: z.nullable(z.string()),
  mongoId: z.nullable(z.string()),
  mountId: z.string(),
  mountPath: z.string(),
  mysqlId: z.nullable(z.string()),
  postgresId: z.nullable(z.string()),
  redisId: z.nullable(z.string()),
  serviceType: RedisStopServiceType$inboundSchema,
  type: RedisStopType$inboundSchema,
  volumeName: z.nullable(z.string()),
});

export function redisStopMountFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopMount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopMount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopMount' from JSON`,
  );
}

/** @internal */
export const RedisStopDriverOpts$inboundSchema: z.ZodType<
  RedisStopDriverOpts,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function redisStopDriverOptsFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopDriverOpts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopDriverOpts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopDriverOpts' from JSON`,
  );
}

/** @internal */
export const RedisStopNetworkSwarm$inboundSchema: z.ZodType<
  RedisStopNetworkSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Aliases: z.array(z.string()).optional(),
  DriverOpts: z.lazy(() => RedisStopDriverOpts$inboundSchema).optional(),
  Target: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "Aliases": "aliases",
    "DriverOpts": "driverOpts",
    "Target": "target",
  });
});

export function redisStopNetworkSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopNetworkSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopNetworkSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopNetworkSwarm' from JSON`,
  );
}

/** @internal */
export const RedisStopPlatform$inboundSchema: z.ZodType<
  RedisStopPlatform,
  z.ZodTypeDef,
  unknown
> = z.object({
  Architecture: z.string(),
  OS: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Architecture": "architecture",
    "OS": "os",
  });
});

export function redisStopPlatformFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopPlatform, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopPlatform$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopPlatform' from JSON`,
  );
}

/** @internal */
export const RedisStopSpread$inboundSchema: z.ZodType<
  RedisStopSpread,
  z.ZodTypeDef,
  unknown
> = z.object({
  SpreadDescriptor: z.string(),
}).transform((v) => {
  return remap$(v, {
    "SpreadDescriptor": "spreadDescriptor",
  });
});

export function redisStopSpreadFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopSpread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopSpread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopSpread' from JSON`,
  );
}

/** @internal */
export const RedisStopPreference$inboundSchema: z.ZodType<
  RedisStopPreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  Spread: z.lazy(() => RedisStopSpread$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Spread": "spread",
  });
});

export function redisStopPreferenceFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopPreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopPreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopPreference' from JSON`,
  );
}

/** @internal */
export const RedisStopPlacementSwarm$inboundSchema: z.ZodType<
  RedisStopPlacementSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Constraints: z.array(z.string()).optional(),
  MaxReplicas: z.number().optional(),
  Platforms: z.array(z.lazy(() => RedisStopPlatform$inboundSchema)).optional(),
  Preferences: z.array(z.lazy(() => RedisStopPreference$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "Constraints": "constraints",
    "MaxReplicas": "maxReplicas",
    "Platforms": "platforms",
    "Preferences": "preferences",
  });
});

export function redisStopPlacementSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopPlacementSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopPlacementSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopPlacementSwarm' from JSON`,
  );
}

/** @internal */
export const RedisStopRestartPolicySwarm$inboundSchema: z.ZodType<
  RedisStopRestartPolicySwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Condition: z.string().optional(),
  Delay: z.number().optional(),
  MaxAttempts: z.number().optional(),
  Window: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    "Condition": "condition",
    "Delay": "delay",
    "MaxAttempts": "maxAttempts",
    "Window": "window",
  });
});

export function redisStopRestartPolicySwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopRestartPolicySwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopRestartPolicySwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopRestartPolicySwarm' from JSON`,
  );
}

/** @internal */
export const RedisStopRollbackConfigSwarm$inboundSchema: z.ZodType<
  RedisStopRollbackConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function redisStopRollbackConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopRollbackConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopRollbackConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopRollbackConfigSwarm' from JSON`,
  );
}

/** @internal */
export const RedisStopMetricsConfigEnum$inboundSchema: z.ZodNativeEnum<
  typeof RedisStopMetricsConfigEnum
> = z.nativeEnum(RedisStopMetricsConfigEnum);

/** @internal */
export const RedisStopMetricsConfigUnion1$inboundSchema: z.ZodType<
  RedisStopMetricsConfigUnion1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  RedisStopMetricsConfigEnum$inboundSchema,
]);

export function redisStopMetricsConfigUnion1FromJSON(
  jsonString: string,
): SafeParseResult<RedisStopMetricsConfigUnion1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopMetricsConfigUnion1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopMetricsConfigUnion1' from JSON`,
  );
}

/** @internal */
export const RedisStopMetricsConfigUnion2$inboundSchema: z.ZodType<
  RedisStopMetricsConfigUnion2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.union([
    z.string(),
    z.number(),
    z.boolean(),
    RedisStopMetricsConfigEnum$inboundSchema,
  ]),
  z.array(z.any()),
  z.record(z.any()),
]);

export function redisStopMetricsConfigUnion2FromJSON(
  jsonString: string,
): SafeParseResult<RedisStopMetricsConfigUnion2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopMetricsConfigUnion2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopMetricsConfigUnion2' from JSON`,
  );
}

/** @internal */
export const RedisStopServerStatus$inboundSchema: z.ZodNativeEnum<
  typeof RedisStopServerStatus
> = z.nativeEnum(RedisStopServerStatus);

/** @internal */
export const RedisStopServer$inboundSchema: z.ZodType<
  RedisStopServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  command: z.string(),
  createdAt: z.string(),
  description: z.nullable(z.string()),
  enableDockerCleanup: z.boolean(),
  ipAddress: z.string(),
  metricsConfig: z.union([
    z.union([
      z.string(),
      z.number(),
      z.boolean(),
      RedisStopMetricsConfigEnum$inboundSchema,
    ]),
    z.array(z.any()),
    z.record(z.any()),
  ]),
  name: z.string(),
  organizationId: z.string(),
  port: z.number(),
  serverId: z.string(),
  serverStatus: RedisStopServerStatus$inboundSchema,
  sshKeyId: z.nullable(z.string()),
  username: z.string(),
});

export function redisStopServerFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopServer' from JSON`,
  );
}

/** @internal */
export const RedisStopUpdateConfigSwarm$inboundSchema: z.ZodType<
  RedisStopUpdateConfigSwarm,
  z.ZodTypeDef,
  unknown
> = z.object({
  Delay: z.number().optional(),
  FailureAction: z.string().optional(),
  MaxFailureRatio: z.number().optional(),
  Monitor: z.number().optional(),
  Order: z.string(),
  Parallelism: z.number(),
}).transform((v) => {
  return remap$(v, {
    "Delay": "delay",
    "FailureAction": "failureAction",
    "MaxFailureRatio": "maxFailureRatio",
    "Monitor": "monitor",
    "Order": "order",
    "Parallelism": "parallelism",
  });
});

export function redisStopUpdateConfigSwarmFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopUpdateConfigSwarm, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopUpdateConfigSwarm$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopUpdateConfigSwarm' from JSON`,
  );
}

/** @internal */
export const RedisStopResponseBody$inboundSchema: z.ZodType<
  RedisStopResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  appName: z.string(),
  applicationStatus: RedisStopApplicationStatus$inboundSchema,
  command: z.nullable(z.string()),
  cpuLimit: z.nullable(z.string()),
  cpuReservation: z.nullable(z.string()),
  createdAt: z.string(),
  databasePassword: z.string(),
  description: z.nullable(z.string()),
  dockerImage: z.string(),
  env: z.nullable(z.string()),
  environment: z.lazy(() => RedisStopEnvironment$inboundSchema),
  environmentId: z.string(),
  externalPort: z.nullable(z.number()),
  healthCheckSwarm: z.nullable(
    z.lazy(() => RedisStopHealthCheckSwarm$inboundSchema),
  ),
  labelsSwarm: z.nullable(z.record(z.string())),
  memoryLimit: z.nullable(z.string()),
  memoryReservation: z.nullable(z.string()),
  modeSwarm: z.nullable(z.lazy(() => RedisStopModeSwarm$inboundSchema)),
  mounts: z.array(z.lazy(() => RedisStopMount$inboundSchema)),
  name: z.string(),
  networkSwarm: z.nullable(
    z.array(z.lazy(() => RedisStopNetworkSwarm$inboundSchema)),
  ),
  placementSwarm: z.nullable(
    z.lazy(() => RedisStopPlacementSwarm$inboundSchema),
  ),
  redisId: z.string(),
  replicas: z.number(),
  restartPolicySwarm: z.nullable(
    z.lazy(() => RedisStopRestartPolicySwarm$inboundSchema),
  ),
  rollbackConfigSwarm: z.nullable(
    z.lazy(() => RedisStopRollbackConfigSwarm$inboundSchema),
  ),
  server: z.nullable(z.lazy(() => RedisStopServer$inboundSchema)),
  serverId: z.nullable(z.string()),
  updateConfigSwarm: z.nullable(
    z.lazy(() => RedisStopUpdateConfigSwarm$inboundSchema),
  ),
});

export function redisStopResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopResponseBody' from JSON`,
  );
}

/** @internal */
export const RedisStopResponse$inboundSchema: z.ZodType<
  RedisStopResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => RedisStopResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function redisStopResponseFromJSON(
  jsonString: string,
): SafeParseResult<RedisStopResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RedisStopResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RedisStopResponse' from JSON`,
  );
}
