/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const RegistryCreateRegistryType = {
  Cloud: "cloud",
} as const;
export type RegistryCreateRegistryType = ClosedEnum<
  typeof RegistryCreateRegistryType
>;

export type RegistryCreateRequest = {
  imagePrefix: string | null;
  password: string;
  registryName: string;
  registryType: RegistryCreateRegistryType;
  registryUrl: string;
  serverId?: string | undefined;
  username: string;
};

/** @internal */
export const RegistryCreateRegistryType$outboundSchema: z.ZodNativeEnum<
  typeof RegistryCreateRegistryType
> = z.nativeEnum(RegistryCreateRegistryType);

/** @internal */
export type RegistryCreateRequest$Outbound = {
  imagePrefix: string | null;
  password: string;
  registryName: string;
  registryType: string;
  registryUrl: string;
  serverId?: string | undefined;
  username: string;
};

/** @internal */
export const RegistryCreateRequest$outboundSchema: z.ZodType<
  RegistryCreateRequest$Outbound,
  z.ZodTypeDef,
  RegistryCreateRequest
> = z.object({
  imagePrefix: z.nullable(z.string()),
  password: z.string(),
  registryName: z.string(),
  registryType: RegistryCreateRegistryType$outboundSchema,
  registryUrl: z.string(),
  serverId: z.string().optional(),
  username: z.string(),
});

export function registryCreateRequestToJSON(
  registryCreateRequest: RegistryCreateRequest,
): string {
  return JSON.stringify(
    RegistryCreateRequest$outboundSchema.parse(registryCreateRequest),
  );
}
