/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type RollbackDeleteRequest = {
  rollbackId: string;
};

/** @internal */
export type RollbackDeleteRequest$Outbound = {
  rollbackId: string;
};

/** @internal */
export const RollbackDeleteRequest$outboundSchema: z.ZodType<
  RollbackDeleteRequest$Outbound,
  z.ZodTypeDef,
  RollbackDeleteRequest
> = z.object({
  rollbackId: z.string(),
});

export function rollbackDeleteRequestToJSON(
  rollbackDeleteRequest: RollbackDeleteRequest,
): string {
  return JSON.stringify(
    RollbackDeleteRequest$outboundSchema.parse(rollbackDeleteRequest),
  );
}
