/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type SecurityDeleteRequest = {
  securityId: string;
};

/**
 * Successful response
 */
export type SecurityDeleteResponseBody = {
  applicationId: string;
  createdAt: string;
  password: string;
  securityId: string;
  username: string;
};

export type SecurityDeleteResponse = SecurityDeleteResponseBody | models.ErrorT;

/** @internal */
export type SecurityDeleteRequest$Outbound = {
  securityId: string;
};

/** @internal */
export const SecurityDeleteRequest$outboundSchema: z.ZodType<
  SecurityDeleteRequest$Outbound,
  z.ZodTypeDef,
  SecurityDeleteRequest
> = z.object({
  securityId: z.string(),
});

export function securityDeleteRequestToJSON(
  securityDeleteRequest: SecurityDeleteRequest,
): string {
  return JSON.stringify(
    SecurityDeleteRequest$outboundSchema.parse(securityDeleteRequest),
  );
}

/** @internal */
export const SecurityDeleteResponseBody$inboundSchema: z.ZodType<
  SecurityDeleteResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
  createdAt: z.string(),
  password: z.string(),
  securityId: z.string(),
  username: z.string(),
});

export function securityDeleteResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SecurityDeleteResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SecurityDeleteResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SecurityDeleteResponseBody' from JSON`,
  );
}

/** @internal */
export const SecurityDeleteResponse$inboundSchema: z.ZodType<
  SecurityDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => SecurityDeleteResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function securityDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<SecurityDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SecurityDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SecurityDeleteResponse' from JSON`,
  );
}
