/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type SecurityUpdateRequest = {
  password: string;
  securityId: string;
  username: string;
};

/**
 * Successful response
 */
export type SecurityUpdateResponseBody = {
  applicationId: string;
  createdAt: string;
  password: string;
  securityId: string;
  username: string;
};

export type SecurityUpdateResponse = SecurityUpdateResponseBody | models.ErrorT;

/** @internal */
export type SecurityUpdateRequest$Outbound = {
  password: string;
  securityId: string;
  username: string;
};

/** @internal */
export const SecurityUpdateRequest$outboundSchema: z.ZodType<
  SecurityUpdateRequest$Outbound,
  z.ZodTypeDef,
  SecurityUpdateRequest
> = z.object({
  password: z.string(),
  securityId: z.string(),
  username: z.string(),
});

export function securityUpdateRequestToJSON(
  securityUpdateRequest: SecurityUpdateRequest,
): string {
  return JSON.stringify(
    SecurityUpdateRequest$outboundSchema.parse(securityUpdateRequest),
  );
}

/** @internal */
export const SecurityUpdateResponseBody$inboundSchema: z.ZodType<
  SecurityUpdateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  applicationId: z.string(),
  createdAt: z.string(),
  password: z.string(),
  securityId: z.string(),
  username: z.string(),
});

export function securityUpdateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<SecurityUpdateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SecurityUpdateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SecurityUpdateResponseBody' from JSON`,
  );
}

/** @internal */
export const SecurityUpdateResponse$inboundSchema: z.ZodType<
  SecurityUpdateResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => SecurityUpdateResponseBody$inboundSchema),
  models.ErrorT$inboundSchema,
]);

export function securityUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<SecurityUpdateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SecurityUpdateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SecurityUpdateResponse' from JSON`,
  );
}
