/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ServerOneRequest = {
  serverId: string;
};

/** @internal */
export type ServerOneRequest$Outbound = {
  serverId: string;
};

/** @internal */
export const ServerOneRequest$outboundSchema: z.ZodType<
  ServerOneRequest$Outbound,
  z.ZodTypeDef,
  ServerOneRequest
> = z.object({
  serverId: z.string(),
});

export function serverOneRequestToJSON(
  serverOneRequest: ServerOneRequest,
): string {
  return JSON.stringify(
    ServerOneRequest$outboundSchema.parse(serverOneRequest),
  );
}
