/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SettingsCleanStoppedContainersRequest = {
  serverId?: string | undefined;
};

/** @internal */
export type SettingsCleanStoppedContainersRequest$Outbound = {
  serverId?: string | undefined;
};

/** @internal */
export const SettingsCleanStoppedContainersRequest$outboundSchema: z.ZodType<
  SettingsCleanStoppedContainersRequest$Outbound,
  z.ZodTypeDef,
  SettingsCleanStoppedContainersRequest
> = z.object({
  serverId: z.string().optional(),
});

export function settingsCleanStoppedContainersRequestToJSON(
  settingsCleanStoppedContainersRequest: SettingsCleanStoppedContainersRequest,
): string {
  return JSON.stringify(
    SettingsCleanStoppedContainersRequest$outboundSchema.parse(
      settingsCleanStoppedContainersRequest,
    ),
  );
}
