/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SettingsReadTraefikFileRequest = {
  path: string;
  serverId?: string | undefined;
};

/** @internal */
export type SettingsReadTraefikFileRequest$Outbound = {
  path: string;
  serverId?: string | undefined;
};

/** @internal */
export const SettingsReadTraefikFileRequest$outboundSchema: z.ZodType<
  SettingsReadTraefikFileRequest$Outbound,
  z.ZodTypeDef,
  SettingsReadTraefikFileRequest
> = z.object({
  path: z.string(),
  serverId: z.string().optional(),
});

export function settingsReadTraefikFileRequestToJSON(
  settingsReadTraefikFileRequest: SettingsReadTraefikFileRequest,
): string {
  return JSON.stringify(
    SettingsReadTraefikFileRequest$outboundSchema.parse(
      settingsReadTraefikFileRequest,
    ),
  );
}
