/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SettingsSetupGPURequest = {
  serverId?: string | undefined;
};

/** @internal */
export type SettingsSetupGPURequest$Outbound = {
  serverId?: string | undefined;
};

/** @internal */
export const SettingsSetupGPURequest$outboundSchema: z.ZodType<
  SettingsSetupGPURequest$Outbound,
  z.ZodTypeDef,
  SettingsSetupGPURequest
> = z.object({
  serverId: z.string().optional(),
});

export function settingsSetupGPURequestToJSON(
  settingsSetupGPURequest: SettingsSetupGPURequest,
): string {
  return JSON.stringify(
    SettingsSetupGPURequest$outboundSchema.parse(settingsSetupGPURequest),
  );
}
