/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SettingsToggleDashboardRequest = {
  enableDashboard?: boolean | undefined;
  serverId?: string | undefined;
};

/** @internal */
export type SettingsToggleDashboardRequest$Outbound = {
  enableDashboard?: boolean | undefined;
  serverId?: string | undefined;
};

/** @internal */
export const SettingsToggleDashboardRequest$outboundSchema: z.ZodType<
  SettingsToggleDashboardRequest$Outbound,
  z.ZodTypeDef,
  SettingsToggleDashboardRequest
> = z.object({
  enableDashboard: z.boolean().optional(),
  serverId: z.string().optional(),
});

export function settingsToggleDashboardRequestToJSON(
  settingsToggleDashboardRequest: SettingsToggleDashboardRequest,
): string {
  return JSON.stringify(
    SettingsToggleDashboardRequest$outboundSchema.parse(
      settingsToggleDashboardRequest,
    ),
  );
}
