/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SettingsSaveSSHPrivateKeyRequest = {
  sshPrivateKey: string | null;
};

/** @internal */
export type SettingsSaveSSHPrivateKeyRequest$Outbound = {
  sshPrivateKey: string | null;
};

/** @internal */
export const SettingsSaveSSHPrivateKeyRequest$outboundSchema: z.ZodType<
  SettingsSaveSSHPrivateKeyRequest$Outbound,
  z.ZodTypeDef,
  SettingsSaveSSHPrivateKeyRequest
> = z.object({
  sshPrivateKey: z.nullable(z.string()),
});

export function settingsSaveSSHPrivateKeyRequestToJSON(
  settingsSaveSSHPrivateKeyRequest: SettingsSaveSSHPrivateKeyRequest,
): string {
  return JSON.stringify(
    SettingsSaveSSHPrivateKeyRequest$outboundSchema.parse(
      settingsSaveSSHPrivateKeyRequest,
    ),
  );
}
