/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SettingsCheckGPUStatusRequest = {
  serverId?: string | undefined;
};

/** @internal */
export type SettingsCheckGPUStatusRequest$Outbound = {
  serverId?: string | undefined;
};

/** @internal */
export const SettingsCheckGPUStatusRequest$outboundSchema: z.ZodType<
  SettingsCheckGPUStatusRequest$Outbound,
  z.ZodTypeDef,
  SettingsCheckGPUStatusRequest
> = z.object({
  serverId: z.string().optional(),
});

export function settingsCheckGPUStatusRequestToJSON(
  settingsCheckGPUStatusRequest: SettingsCheckGPUStatusRequest,
): string {
  return JSON.stringify(
    SettingsCheckGPUStatusRequest$outboundSchema.parse(
      settingsCheckGPUStatusRequest,
    ),
  );
}
