/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SettingsGetTraefikPortsRequest = {
  serverId?: string | undefined;
};

/** @internal */
export type SettingsGetTraefikPortsRequest$Outbound = {
  serverId?: string | undefined;
};

/** @internal */
export const SettingsGetTraefikPortsRequest$outboundSchema: z.ZodType<
  SettingsGetTraefikPortsRequest$Outbound,
  z.ZodTypeDef,
  SettingsGetTraefikPortsRequest
> = z.object({
  serverId: z.string().optional(),
});

export function settingsGetTraefikPortsRequestToJSON(
  settingsGetTraefikPortsRequest: SettingsGetTraefikPortsRequest,
): string {
  return JSON.stringify(
    SettingsGetTraefikPortsRequest$outboundSchema.parse(
      settingsGetTraefikPortsRequest,
    ),
  );
}
