/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SettingsUpdateTraefikConfigRequest = {
  traefikConfig: string;
};

/** @internal */
export type SettingsUpdateTraefikConfigRequest$Outbound = {
  traefikConfig: string;
};

/** @internal */
export const SettingsUpdateTraefikConfigRequest$outboundSchema: z.ZodType<
  SettingsUpdateTraefikConfigRequest$Outbound,
  z.ZodTypeDef,
  SettingsUpdateTraefikConfigRequest
> = z.object({
  traefikConfig: z.string(),
});

export function settingsUpdateTraefikConfigRequestToJSON(
  settingsUpdateTraefikConfigRequest: SettingsUpdateTraefikConfigRequest,
): string {
  return JSON.stringify(
    SettingsUpdateTraefikConfigRequest$outboundSchema.parse(
      settingsUpdateTraefikConfigRequest,
    ),
  );
}
