/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const SshKeyGenerateType = {
  Rsa: "rsa",
  Ed25519: "ed25519",
} as const;
export type SshKeyGenerateType = ClosedEnum<typeof SshKeyGenerateType>;

export type SshKeyGenerateRequest = {
  type?: SshKeyGenerateType | undefined;
};

/** @internal */
export const SshKeyGenerateType$outboundSchema: z.ZodNativeEnum<
  typeof SshKeyGenerateType
> = z.nativeEnum(SshKeyGenerateType);

/** @internal */
export type SshKeyGenerateRequest$Outbound = {
  type?: string | undefined;
};

/** @internal */
export const SshKeyGenerateRequest$outboundSchema: z.ZodType<
  SshKeyGenerateRequest$Outbound,
  z.ZodTypeDef,
  SshKeyGenerateRequest
> = z.object({
  type: SshKeyGenerateType$outboundSchema.optional(),
});

export function sshKeyGenerateRequestToJSON(
  sshKeyGenerateRequest: SshKeyGenerateRequest,
): string {
  return JSON.stringify(
    SshKeyGenerateRequest$outboundSchema.parse(sshKeyGenerateRequest),
  );
}
