/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type UserGetUserByTokenRequest = {
  token: string;
};

/** @internal */
export type UserGetUserByTokenRequest$Outbound = {
  token: string;
};

/** @internal */
export const UserGetUserByTokenRequest$outboundSchema: z.ZodType<
  UserGetUserByTokenRequest$Outbound,
  z.ZodTypeDef,
  UserGetUserByTokenRequest
> = z.object({
  token: z.string(),
});

export function userGetUserByTokenRequestToJSON(
  userGetUserByTokenRequest: UserGetUserByTokenRequest,
): string {
  return JSON.stringify(
    UserGetUserByTokenRequest$outboundSchema.parse(userGetUserByTokenRequest),
  );
}
