/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type UserOneRequest = {
  userId: string;
};

/** @internal */
export type UserOneRequest$Outbound = {
  userId: string;
};

/** @internal */
export const UserOneRequest$outboundSchema: z.ZodType<
  UserOneRequest$Outbound,
  z.ZodTypeDef,
  UserOneRequest
> = z.object({
  userId: z.string(),
});

export function userOneRequestToJSON(userOneRequest: UserOneRequest): string {
  return JSON.stringify(UserOneRequest$outboundSchema.parse(userOneRequest));
}
