/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type UserCheckUserOrganizationsRequest = {
  userId: string;
};

/** @internal */
export type UserCheckUserOrganizationsRequest$Outbound = {
  userId: string;
};

/** @internal */
export const UserCheckUserOrganizationsRequest$outboundSchema: z.ZodType<
  UserCheckUserOrganizationsRequest$Outbound,
  z.ZodTypeDef,
  UserCheckUserOrganizationsRequest
> = z.object({
  userId: z.string(),
});

export function userCheckUserOrganizationsRequestToJSON(
  userCheckUserOrganizationsRequest: UserCheckUserOrganizationsRequest,
): string {
  return JSON.stringify(
    UserCheckUserOrganizationsRequest$outboundSchema.parse(
      userCheckUserOrganizationsRequest,
    ),
  );
}
