/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type UserDeleteApiKeyRequest = {
  apiKeyId: string;
};

/** @internal */
export type UserDeleteApiKeyRequest$Outbound = {
  apiKeyId: string;
};

/** @internal */
export const UserDeleteApiKeyRequest$outboundSchema: z.ZodType<
  UserDeleteApiKeyRequest$Outbound,
  z.ZodTypeDef,
  UserDeleteApiKeyRequest
> = z.object({
  apiKeyId: z.string(),
});

export function userDeleteApiKeyRequestToJSON(
  userDeleteApiKeyRequest: UserDeleteApiKeyRequest,
): string {
  return JSON.stringify(
    UserDeleteApiKeyRequest$outboundSchema.parse(userDeleteApiKeyRequest),
  );
}
